### ISSUE TITLE
Playnite crashes when trying to sort by category

### ISSUE THREAD

**Issue by Pluven** [JosefNemec/Playnite#722] opened 2018-07-26 19:45 UTC
Sorted all games in easy categories yet crash occurs when trying to group by category.
[Issue.zip](https://github.com/JosefNemec/Playnite/files/2233361/Issue.zip)

**Comment by JosefNemec** [comment] 2018-07-27 07:01
How large is your game library? And does it occur every time, specifically are you able to reproduce this on demand? We've had this crash popup in past, but I was unable to reproduce it, so additional information would help a lot.

Also if you are able to reproduce it on demand would you be willing to share your [library db file](https://github.com/JosefNemec/Playnite/wiki/Frequently-Asked-Questions#where-can-i-find-library-file-with-all-games) with me?

**Comment by Pluven** [comment] 2018-07-27 09:38
My game library is 790 games including games from steam, gog, battle.net & origin.
I can reproduce it, it happens every time I try to group by category.
Now that you mention it, I do have my library file on my local NAS so it could be accessed from multiple PC's in my network.

Anyway below the link to the library db file:
https://we.tl/3zFZNiHNrU

**Comment by Pluven** [comment] 2018-08-13 11:31
Update:

I found the problem: for some reason while applying a category to multiple games, it applied the same category a massive amount of times to the same game. I assume this caused an overload when trying to group by category. By removing the categories and creating new ones the problem was solved.

**Comment by JosefNemec** [comment] 2018-08-13 11:45
Interesting, thank you very much for investigating this.

**Comment by Pluven** [comment] 2018-08-13 11:47
No problem, hopefully you can fix it because i'm loving the app.

**Comment by JosefNemec** [comment] 2018-09-27 09:46
Released in 4.5

**Closed by JosefNemec** 2018-09-27 09:46 UTC
Labels: bug
