### ISSUE TITLE
Constant crashing when changing a number of games Categories

### ISSUE THREAD

**Issue by DennoCoil** [JosefNemec/Playnite#796] opened 2018-10-20 14:37 UTC
d7337951-434e-428d-a15a-6187258734e7

Honestly, I could keep sending in report after report after report with how much crashing changing a game's Category does.

EDIT:
10 minutes of this
fc0b823b-3a32-447a-8cee-0dfc828e35fc
524418b6-b6b4-4f35-a060-399ac62bd0dc
13cbaad7-8f79-4d69-91ae-71fc37804d92
a96d44bf-c3a1-40eb-b43d-18aca95b6b1a
3737ddd1-2653-4654-a9d0-ebfed5b58678
4756cd7f-2daa-4e79-bda1-4f0be5b9fe2e
9e389d62-3a76-46d6-bb12-a52caeec1f08
3c07107b-9181-4593-9f36-d1010553bad4

**Comment by JosefNemec** [comment] 2018-10-20 15:47
That's really weird, there was no change in that part of code, plus it crashes in .NET library long after categories are already set. I really don't know what to do with this since I'm unable to reproduce it on any of my systems. Does it crash every time? Even if you set just single category to single game? Or does it happen in some specific cases only?

**Comment by DennoCoil** [comment] 2018-10-20 15:51
It crashes on some games.  Doesn't crash on others.  Recently it just likes to crash a lot.  Like setting Lone Survivor: Director's Cut from "2D Games" to "Psuedo-Retro" causes it to crash without fail.
fe6d5f01-6eae-41f6-a51c-7e33b55447b7

I could give you my database.

**Comment by JosefNemec** [comment] 2018-10-20 15:52
Yes, please send me your database file.

**Comment by DennoCoil** [comment] 2018-10-20 15:58
It's a good thing it just crashes the .NET library after setting the categories otherwise the Category system would be useless.

280MB download
https://www.dropbox.com/s/sbxl1qbidxzu0v8/games.db?dl=0

**Comment by JosefNemec** [comment] 2018-10-20 17:03
Fix released in 4.57

**Closed by JosefNemec** 2018-10-20 17:03 UTC
Labels: bug
