### ISSUE TITLE
Playnite fullscreen size on 4k tv

### ISSUE THREAD

**Issue by limitlessbritt** [JosefNemec/Playnite#785] opened 2018-10-06 20:16 UTC
I have 3 displays hooked up to my computer. 2 1080p monitors and 1 4k tv. When i want to play off the tv i set as my main display. When i launch playnite in fullscreen it expends past the tv down to the monitors. 
![2018-10-06_16-10-55](https://user-images.githubusercontent.com/37319328/46575435-f0578880-c982-11e8-8fab-4935c718d43f.jpg)
 

As you can see from the screenshot where the two taskbars are is where the 2 1080p monitors start.

Is there a way to fix this?

Thanks!

**Comment by JosefNemec** [comment] 2018-10-06 21:03
This will be fixed by #739, Playnite currently doesn't properly respect main display and it's resolution.

**Comment by JosefNemec** [comment] 2018-10-11 07:02
I'm reopening this, I found possible fix for this before we implement #739

**Comment by JosefNemec** [comment] 2018-10-16 09:34
I'm having issues reproducing this, what's the specific layout you have set up? This is what I'm testing on:
![image](https://user-images.githubusercontent.com/3874087/47006209-b1b98f00-d135-11e8-8e75-a40f7a3a93c7.png)

It's not a real hardware (but virtual machine), since I don't have 4k screen to test on.

**Comment by limitlessbritt** [comment] 2018-10-17 01:48
My layout is like that, my primary display is number 3.  The bug only happens sometimes. So I'm not sure what causes it. 
![2018-10-16_21-47-53](https://user-images.githubusercontent.com/37319328/47057072-2cfa5f80-d18d-11e8-8622-fac7807e13f8.jpg)

**Comment by spektor56** [comment] 2018-11-05 20:52
could be from the non-standard scaling setting? (125%)

**Comment by JosefNemec** [comment] 2018-11-05 20:57
Probably not, I tried changing DPI scaling and was still unable to reproduce it no matter what it was set to.

**Comment by JosefNemec** [comment] 2018-12-05 16:19
Turns out that it was caused by DPI scaling. When I was testing it Windows didn't set scaling properly on my dev machine for some reason, but I was able to reproduce it on another installation.

There's now new option in 4.62 to disable DPI scaling, which fixes this issue. Just note that it will disable scaling in Desktop mode as well. Currently Desktop and Fullscreen modes run from the same process, which means there's no way to just disable it for Fullscreen mode. I will be separating then in next major version.

**Closed by JosefNemec** 2018-12-05 16:19 UTC
Labels: bug
