### ISSUE TITLE
Failed to import games from Twitch

### ISSUE THREAD

**Issue by Caf** [JosefNemec/Playnite#963] opened 2019-02-03 16:47 UTC
Hello,

I tried everything but I still have "failed to import game from Twitch, an item with the same key has already been added". Don't know what that means exactly and where to search to find the problem.  :( 

I don't import uninstalled games. I did try to do that on Twitch. It does work, but it can't "see" the installed ones, same bug.

diagnostics ID:
0c7be4f5-f60c-4b7a-92ca-03e39be6c384

I hope it helps. :)

**Comment by JosefNemec** [comment] 2019-02-03 17:13
Thanks for diag. id. I think I know where the problem is, I'll try to fix in next update (coming on Friday).

**Comment by JosefNemec** [comment] 2019-02-08 10:05
Fixed in 4.71

**Closed by JosefNemec** 2019-02-08 10:05 UTC
Labels: bug
