### ISSUE TITLE
Sorting and grouping doesn't update properly after updating game field

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1407] opened 2019-09-07 00:46 UTC
**To Reproduce**
Delete the Sorting name in any title and it won't move to the correct position in the list. Updating any metadata field as seen in the video, in which I edit the Description of another game, updates the list and places the game where it should be.

An issue related to this ( #1292 ) was closed but the problem persists.

**Screenshots**

![2019-09-06_19-30-16-p1dk4iobqs1kpb9811dna35](https://user-images.githubusercontent.com/1389286/64467494-c2bd1700-d0de-11e9-9b28-7ed306fe64c3.gif)

**Comment by JosefNemec** [comment] 2019-09-25 08:10
I've updated title because it affects all fields, seemingly randomly.

**Comment by JosefNemec** [comment] 2020-02-01 17:11
After some investigation I found that this is sadly caused by some issue in WPF (CollectionView specifically). I have plans to rework how sorting and grouping works using custom collection system (for better performance and features like natural sorting), but I will have to postpone this to Playnite 8.

**Comment by SAH7777** [comment] 2022-02-06 10:37
also please see/check-on this scenario: https://playnite.link/forum/thread-1120.html

thank you.

**Comment by JosefNemec** [comment] 2022-05-31 07:45
Fixed indirectly by adc6846a8d54ef18740f973acada4a5dd6f5be1c in devel.

**Closed by JosefNemec** 2022-05-31 07:45 UTC
Labels: bug
