### ISSUE TITLE
P9 Beta: Opening menus invoke the MenuItem functions of powershell extensions

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#2466] opened 2021-09-08 08:13 UTC
**Describe the bug**
Opening menus invoke the MenuItem functions of powershell extensions

**To Reproduce**
- Use the MenuItem of a powershell script extension to trigger a function
- I'm not fully sure, but it seems to happen after reloading all scripts with `F12`, probably pressing it several times helps to trigger the issue
- Open a menu and the last used function will probably be triggered.

I've not found a way to reliably reproduce, it only happens very very rarely. It should be noted that I might have experienced this issue before Playnite 9, when it very rarely triggered the issue the first time a menu was opened, but in Playnite 9 the functions are being invoked every time I open a menu until I reload the scripts with `F12`

**Screenshots**

https://user-images.githubusercontent.com/1389286/132471651-1fb17037-0b71-467e-b0a5-00817c41686c.mp4

https://user-images.githubusercontent.com/1389286/132471705-7f6183e2-8cba-46e0-b678-350564b528c0.mp4

**Comment by JosefNemec** [comment] 2021-09-15 15:30
I have no idea how this is even possible and I could not reproduce it (tried spam reloading extensions).

This could IMO only happen if you would put code to execute your extension into `GetMainMenuItems` instead of just returning menu items.

**Comment by darklinkpower** [comment] 2021-09-15 15:32
I'm 100% sure this is not an issue of having code in the MenuItems function. The functions being invoked here are functions that can only be started via menu items.

**Comment by darklinkpower** [comment] 2021-09-15 15:34
Here is the extension from the first video. The highlighted menuItem is what was being activated in the video https://github.com/darklinkpower/PlayniteExtensionsCollection/blob/master/source/Generic/SteamGameImporter/SteamGameImporter.psm1#L7-L10

**Comment by joyrider3774** [comment] 2021-10-05 19:22
This extension will trigger it, i did not verify if it really called the menu item again but does make it seem like it does.
The extension will show a small xaml windows with a button, when you click the button i make a fault happen on purpose during showmessage (from playnite api) when you click ok on that error and then right click any game, (it would seem that) the window and thus right click menu item functionality is called again. I think the cause are powershell extensions erroring out though at least if it's this behaviour that was seen.

To test use following plugin, right click any game choose Test bug -> test then click Trigger button click ok on the error then right click any game in details view it will keep showing this same window again making it seem as if the right click menu item is triggered again, but i did not really verify if it really does this, 

```
function GetGameMenuItems
{
    param(
        $scriptGameMenuItemActionArgs
    )

    $menuItem = New-Object Playnite.SDK.Plugins.ScriptGameMenuItem
    $menuItem.Description =  "test"
    $menuItem.FunctionName = "Invoke-test"
    $menuItem.MenuSection = "test bug"

    return $menuItem
}

function Invoke-test
{
	param(
        $scriptGameMenuItemActionArgs
    )
    # Load assemblies
    Add-Type -AssemblyName PresentationCore
    Add-Type -AssemblyName PresentationFramework

    # Set Xaml
    [xml]$Xaml = @"
<Grid xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation">
	<StackPanel>
		<Label Content="The bug happens if a powershell extension gets an error during showmessage, click button below" />
		<Label Content="you'll get error click it away then right click any games in the details list" />
		<Button Content="trigger bug" HorizontalAlignment="Center" Name="ButtonTriggerBug" IsDefault="False"/>
	</StackPanel>
</Grid>
"@
	# Load the xaml for controls
	$XMLReader = [System.Xml.XmlNodeReader]::New($Xaml)
	$XMLForm = [Windows.Markup.XamlReader]::Load($XMLReader)

	# Make variables for each control
	$Xaml.FirstChild.SelectNodes("//*[@Name]") | ForEach-Object {Set-Variable -Name $_.Name -Value $XMLForm.FindName($_.Name) }

	# Set Window creation options
	$windowCreationOptions = New-Object Playnite.SDK.WindowCreationOptions
	$windowCreationOptions.ShowCloseButton = $true
	$windowCreationOptions.ShowMaximizeButton = $False
	$windowCreationOptions.ShowMinimizeButton = $False

	# Create window
	$window = $PlayniteApi.Dialogs.CreateWindow($windowCreationOptions)
	$window.Content = $XMLForm
	$window.Width = 900
	$window.Height = 600
	$window.Title = "Test bug"
	$window.WindowStartupLocation = "CenterScreen"

	# Handler for pressing "Search" button
	$ButtonTriggerBug.Add_Click(
	{
		#will error out because i did not provide enough params for {1} and then it will trigger the bug
		$PlayniteApi.Dialogs.ShowMessage("test {0} {1}" -f "test", "Bug")
	})

	# Show Window
	$window.ShowDialog()
}


```

**Comment by JosefNemec** [comment] 2021-10-06 14:49
Fixed in master.

**Closed by JosefNemec** 2021-10-06 14:49 UTC
Labels: bug
