### ISSUE TITLE
Grid View "Scroll amount modifier" doesn't accept decimal numbers

### ISSUE THREAD

**Issue by UrbanCMC** [JosefNemec/Playnite#2789] opened 2022-02-02 11:54 UTC
### Bug Description

I saw the bug report on Discord and tried it on my Playnite instance, because I suspected it might be related to regional formatting of decimal numbers.

On the one hand, I can reproduce the bug and am now unable to set the scroll amount modifier back to 1.5.
But on the other, it does not appear to be a formatting issue, because neither `1.5` nor `1,5` work.

I tried it with both a custom and the default theme. Same results.
Disabling all of my extensions similarly didn't affect the issue.

### Diagnostics ID

13e11199-72e8-41c3-a513-c6b0d228258a

### Screenshots

https://user-images.githubusercontent.com/9725089/152147958-9c1d6c6a-da19-4cb7-8747-c81dc36c2a46.mp4

**Comment by JosefNemec** [comment] 2022-02-02 12:12
Can't reproduce. I have no idea what might be the issue on your system with this.

https://user-images.githubusercontent.com/3874087/152151457-ad326b9a-9cd0-420c-a8ca-47f3b431d035.mp4

**Comment by UrbanCMC** [comment] 2022-02-02 12:15
Good to know. It doesn't really bother me, since I don't use the Grid View, and was really just surprised that I could reproduce it.

I may take a look at the code if I get some time, and see if I can figure out what is going on.

**Comment by JosefNemec** [comment] 2022-02-02 12:25
What are your regional and units settings? I'll try to replicate it in a VM with those.

**Comment by UrbanCMC** [comment] 2022-02-02 12:30
Nothing outrageous as far as I'm aware.
![image](https://user-images.githubusercontent.com/9725089/152153767-2ba60576-7b2b-47d5-a8a9-4a833372a3bf.png)

**Comment by UrbanCMC** [comment] 2022-02-02 15:14
Looks like a "simple" parsing bug, where you always replace `.` with `,` before parsing the numbers. Then .NET applies the system settings for determining the decimal separator, so the `,` is treated as the thousands-separator and ignored.
https://github.com/JosefNemec/Playnite/blob/950be21db0a8d6a15fcb637038d89eca3affdd02/source/Playnite.DesktopApp/Controls/NumericDoubleBox.cs#L124

https://github.com/JosefNemec/Playnite/blob/950be21db0a8d6a15fcb637038d89eca3affdd02/source/Playnite.DesktopApp/Controls/NumericDoubleBox.cs#L170

**Comment by JosefNemec** [comment] 2022-02-14 07:08
Fixed in devel.

**Closed by JosefNemec** 2022-02-14 07:08 UTC
Labels: bug
