### ISSUE TITLE
Games launching on the integrated GPU instead of the dedicated GPU.

### ISSUE THREAD

**Issue by Neamow** [JosefNemec/Playnite#875] opened 2018-12-14 19:16 UTC
I have a gaming laptop with both an integrated GPU (Intel HD graphics) and a dedicated GPU (an Nvidia GeForce). Now all game launchers have no troubles dealing with this and always start games on the dedicated GPU.

However for some reason any games started trough Playnite run on the integrated GPU, which as you can imagine impacts performance significantly.

I tried forcing Playnite itself to start on the dedicated GPU in the Nvidia Control Panel - usually when a game is launched from a parent application, it follows its GPU settings, so I expected any games launched through Playnite to also launch on the dedicated GPU, but nothing changed, they still run on the integrated one.

**Comment by Neamow** [comment] 2018-12-14 19:38
Thanks for the reply. I tried that, but it had no effect.

Unfortunately unless this is fixed, Playnite is unusable for me :(

Was this never reported before? Quite a lot of notebooks run this way, and a lot of desktop CPUs also offer iGPUs.

**Comment by JosefNemec** [comment] 2018-12-14 19:50
No, this is the first time I'm hearing about this. It's also weird that disabling HW acceleration doesn't fix this because that forces Playnite to use CPU only, I don't see how it could be Playnite issue in that case (if some GPU inheritance is the root cause).

Also I don't think that this would be an issue on desktops, because they don't have enabled iGPU at all if dedicated one is present (in majority of cases at least). Also quick googling revealed that nvidia doesn't even support Optimus on desktop.

If this is some GPU settings inheritance issue then I'm not sure I would be able to fix this without completely reworking how games are started. And that's not even possible in some cases, for example for Steam and Twitch games.

**Comment by Neamow** [comment] 2018-12-14 19:56
OK so not sure what's changed, but games are now launching on the dedicated GPU, when "Disable hardware acceleration" is checked.

The only difference between now and previous runs is that I restarted the laptop because it froze when I was alt-tabbing out of Rocket League to go Task Manager to check the GPU usage.

So I guess a PC restart is necessary? Maybe not for Playnite, but some Nvidia settings, who knows.

**Comment by JosefNemec** [comment] 2019-06-06 14:16
I'm closing this because we have no control over what apps are run on what GPU. Even in case of Playnite we can't choose what GPU will be used because we don't have access to DirectX context creation.

**Closed by JosefNemec** 2019-06-06 14:16 UTC
Labels: bug
