### ISSUE TITLE
Playnite Crashes when downloading Humble Library 

### ISSUE THREAD

**Issue by thealmightypatx** [JosefNemec/Playnite#2514] opened 2021-10-02 12:17 UTC
**Before creating bug report**
Tested in both regular mode and Safe mode. All other Libraries download without issue.
- Check list of known issues https://github.com/JosefNemec/Playnite/wiki/Known-Issues

**Integration issues**
If an issue is related to library integrations, use separate [extensions repository](https://github.com/JosefNemec/PlayniteExtensions) to file a report.

**Describe the bug**
Playnite Crashes (Exits) when downloading Humble Library.
I've uninstalled and re installed the humble plugin

**To Reproduce**
Click Update Library > Humble, Nothing will happen for a few seconds then playnite exits.

**Screenshots**

**Diagnostics ID**
a016229b-4181-4eff-a154-8b7c3680ad6d

**Comment by JosefNemec** [comment] 2021-10-02 12:28
If you are not getting Playnite's crash dialog and Playnite just exists, then it means that it's not happening in our code. I suggest disabling all non-builtin extensions and switching to default theme since this looks to me like an issue caused by a theme or extension.

**Comment by JosefNemec** [comment] 2021-10-02 12:34
Also, I don't know what your setup is but there are weird errors in logs related to multiple instances of Playnite starting at the same time and conflicting (being force via cmdline to run as main instance). Are you using some non-standard way of launching Playnite?

**Comment by thealmightypatx** [comment] 2021-10-02 14:40
I've disabled all extensions, and switched to the default theme, and
rebooted.
I'm only seeing one instance of Playnite.DesktopApp.exe in task manager,
and playnite still exits when downloading from humble.

**Comment by JosefNemec** [comment] 2021-10-02 14:48
I can't reproduce it and there's no crash info in your logs. Playnite just existing means that it doesn't crash in any part of code we can affect, otherwise you would get Playnite's crash dialog. This looks like some 3rd party causing this.

Can you possibly upload your whole Playnite installation for me somewhere? Both `%appdata%\playnite` and `%localappdata%\playnite` folders.

**Comment by thealmightypatx** [comment] 2021-10-02 14:48
found this in event viewer

Log Name:      Application
Source:        .NET Runtime
Date:          10/1/2021 4:08:15 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Wonderfizzle
Description:
Application: Playnite.DesktopApp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Windows.Window.set_DialogResult(System.Nullable`1<Boolean>)
   at
Playnite.Windows.WindowFactory+<>c__DisplayClass18_0.<Close>b__0(System.Object)
   at
System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate,
System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object,
System.Delegate, System.Object, Int32, System.Delegate)
   at
System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority,
System.TimeSpan, System.Delegate, System.Object, Int32)
   at
System.Windows.Threading.DispatcherSynchronizationContext.Send(System.Threading.SendOrPostCallback,
System.Object)
   at Playnite.Windows.WindowFactory.Close(System.Nullable`1<Boolean>)
   at Playnite.DesktopApp.ViewModels.AddonsViewModel.ConfirmDialog()
   at
Playnite.DesktopApp.ViewModels.AddonsViewModel.<get_ConfirmCommand>b__37_0(System.Object)
   at Playnite.SDK.RelayCommand`1[[System.__Canon, mscorlib,
Version=4.0.0.0, Culture=neutral,
PublicKeyToken=b77a5c561934e089]].Execute(System.Object)
   at
MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(System.Windows.Input.ICommandSource,
Boolean)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at
System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(System.Object,
System.Windows.Input.MouseButtonEventArgs)
   at
System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate,
System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate,
System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object,
System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object,
System.Windows.RoutedEventArgs, Boolean)
   at
System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject,
System.Windows.RoutedEventArgs, System.Windows.RoutedEvent)
   at System.Windows.UIElement.OnMouseUpThunk(System.Object,
System.Windows.Input.MouseButtonEventArgs)
   at
System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate,
System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate,
System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object,
System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object,
System.Windows.RoutedEventArgs, Boolean)
   at
System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject,
System.Windows.RoutedEventArgs)
   at
System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs,
Boolean)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at
System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at
System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr,
System.Windows.Input.InputMode, Int32,
System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr,
MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32,
IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean
ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at
System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate,
System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object,
System.Delegate, System.Object, Int32, System.Delegate)
   at
System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority,
System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at
MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG
ByRef)
   at
System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at
System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Window.ShowHelper(System.Object)
   at System.Windows.Window.Show()
   at System.Windows.Window.ShowDialog()
   at
Playnite.Windows.WindowFactory+<>c__DisplayClass13_0.<CreateAndOpenDialog>b__0(System.Object)
   at
System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate,
System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object,
System.Delegate, System.Object, Int32, System.Delegate)
   at
System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority,
System.TimeSpan, System.Delegate, System.Object, Int32)
   at
System.Windows.Threading.DispatcherSynchronizationContext.Send(System.Threading.SendOrPostCallback,
System.Object)
   at Playnite.Windows.WindowFactory.CreateAndOpenDialog(System.Object)
   at
Playnite.DesktopApp.ViewModels.DesktopAppViewModel.<InitializeCommands>b__287_47(System.Object)
   at Playnite.SDK.RelayCommand`1[[System.__Canon, mscorlib,
Version=4.0.0.0, Culture=neutral,
PublicKeyToken=b77a5c561934e089]].Execute(System.Object)
   at
MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(System.Windows.Input.ICommandSource,
Boolean)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(System.Object)
   at
System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate,
System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object,
System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at
System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at
MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at
System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object, Boolean)
   at
System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object, Boolean)
   at
System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object)
   at
MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext,
System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32,
IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean
ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at
System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate,
System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object,
System.Delegate, System.Object, Int32, System.Delegate)
   at
System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority,
System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at
MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG
ByRef)
   at
System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at
System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at Playnite.DesktopApp.ProgramEntry.Main(System.String[])


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-10-01T21:08:15.4508229Z" />
    <EventRecordID>15075</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Wonderfizzle</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: Playnite.DesktopApp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at
System.Windows.Window.set_DialogResult(System.Nullable`1&lt;Boolean&gt;)
   at
Playnite.Windows.WindowFactory+&lt;&gt;c__DisplayClass18_0.&lt;Close&gt;b__0(System.Object)
   at
System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate,
System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object,
System.Delegate, System.Object, Int32, System.Delegate)
   at
System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority,
System.TimeSpan, System.Delegate, System.Object, Int32)
   at
System.Windows.Threading.DispatcherSynchronizationContext.Send(System.Threading.SendOrPostCallback,
System.Object)
   at Playnite.Windows.WindowFactory.Close(System.Nullable`1&lt;Boolean&gt;)
   at Playnite.DesktopApp.ViewModels.AddonsViewModel.ConfirmDialog()
   at
Playnite.DesktopApp.ViewModels.AddonsViewModel.&lt;get_ConfirmCommand&gt;b__37_0(System.Object)
   at Playnite.SDK.RelayCommand`1[[System.__Canon, mscorlib,
Version=4.0.0.0, Culture=neutral,
PublicKeyToken=b77a5c561934e089]].Execute(System.Object)
   at
MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(System.Windows.Input.ICommandSource,
Boolean)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at
System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(System.Object,
System.Windows.Input.MouseButtonEventArgs)
   at
System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate,
System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate,
System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object,
System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object,
System.Windows.RoutedEventArgs, Boolean)
   at
System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject,
System.Windows.RoutedEventArgs, System.Windows.RoutedEvent)
   at System.Windows.UIElement.OnMouseUpThunk(System.Object,
System.Windows.Input.MouseButtonEventArgs)
   at
System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate,
System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate,
System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object,
System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object,
System.Windows.RoutedEventArgs, Boolean)
   at
System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject,
System.Windows.RoutedEventArgs)
   at
System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs,
Boolean)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at
System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at
System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr,
System.Windows.Input.InputMode, Int32,
System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr,
MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32,
IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean
ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at
System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate,
System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object,
System.Delegate, System.Object, Int32, System.Delegate)
   at
System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority,
System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at
MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG
ByRef)
   at
System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at
System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Window.ShowHelper(System.Object)
   at System.Windows.Window.Show()
   at System.Windows.Window.ShowDialog()
   at
Playnite.Windows.WindowFactory+&lt;&gt;c__DisplayClass13_0.&lt;CreateAndOpenDialog&gt;b__0(System.Object)
   at
System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate,
System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object,
System.Delegate, System.Object, Int32, System.Delegate)
   at
System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority,
System.TimeSpan, System.Delegate, System.Object, Int32)
   at
System.Windows.Threading.DispatcherSynchronizationContext.Send(System.Threading.SendOrPostCallback,
System.Object)
   at Playnite.Windows.WindowFactory.CreateAndOpenDialog(System.Object)
   at
Playnite.DesktopApp.ViewModels.DesktopAppViewModel.&lt;InitializeCommands&gt;b__287_47(System.Object)
   at Playnite.SDK.RelayCommand`1[[System.__Canon, mscorlib,
Version=4.0.0.0, Culture=neutral,
PublicKeyToken=b77a5c561934e089]].Execute(System.Object)
   at
MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(System.Windows.Input.ICommandSource,
Boolean)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(System.Object)
   at
System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate,
System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object,
System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at
System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at
MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at
System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object, Boolean)
   at
System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object, Boolean)
   at
System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object)
   at
MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext,
System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32,
IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean
ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at
System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate,
System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object,
System.Delegate, System.Object, Int32, System.Delegate)
   at
System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority,
System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at
MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG
ByRef)
   at
System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at
System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at Playnite.DesktopApp.ProgramEntry.Main(System.String[])

</Data>
  </EventData>
</Event>
-Patrick

**Comment by JosefNemec** [comment] 2021-10-02 14:51
That's some crash after closing add-ons window, which should have resulted in Playnite crash dialog. Definitely not something that happened after updating Humble library.

**Comment by thealmightypatx** [comment] 2021-10-02 14:55
Playnite TS
<https://drive.google.com/drive/folders/10xeuGi51O1XtviMJHwckEqQrX1-tEuOK>
google drive link

-Patrick

**Comment by JosefNemec** [comment] 2021-10-02 14:59
There nothing there, all folders are empty.

**Comment by thealmightypatx** [comment] 2021-10-02 16:53
Data should be there now.

-Patrick

**Comment by JosefNemec** [comment] 2021-10-04 19:58
Thanks for the files. It works properly on my PC, no crash after syncing Humble library.

**Comment by thealmightypatx** [comment] 2021-10-04 20:23
I did a clean install. Deleted both appdata filders, uninstalled, and rebooted. Installed the latest version, enabling only the Humble library, no other extensions.  Got the same results.

However, this isn't too big of a deal for me, and I don't feel like doing a lot more troubleshooting. I'm going to just disable the Humble library, and call it a day. Thanks for all your help.

-Patrick
________________________________

**Comment by JosefNemec** [comment] 2021-10-05 08:31
Can you please try it [with this](https://playnite.link/download/cef94.zip) Playnite build? One person on Discord had similar issue with GOG sync and we probably found out the root cause.

**Comment by thealmightypatx** [comment] 2021-10-05 12:53
It worked. Thanks
-Patrick

**Comment by JosefNemec** [comment] 2021-10-05 12:57
Great, thanks for testing. Closing as fixed by c7c68936153cd771b56d53471a3af9466251a72a

**Closed by JosefNemec** 2021-10-05 12:57 UTC
Labels: bug
