### ISSUE TITLE
Possible Memory leak on library refresh

### ISSUE THREAD

**Issue by arandomguysomewhere** [JosefNemec/Playnite#3637] opened 2023-12-27 17:00 UTC
### Bug Description

I added over 5800 games to the library and tried downloading metadata for these. I had set the sorting to descending on date modified and noticed that with this setting the memory usage of Playnite went up from around 300 MB to over 1.5 GB as more games were being updated (at that point about 2000 had been updated). The growth rate reduced a lot (a few megabytes every few 100 entries) after setting the sort to ascending by name which caused less refreshes. Interestingly, after a hibernate and resume with the download process still ongoing the memory usage dropped by over a GB back down to around 500 MB. I do have several library source extensions and am using some more to go with the Default Extended theme but this seems to be sync related as I stopped touching those after noticing their memory impact during the download (e.g. loading the HowLongToBeat extension global screen several times caused a massive memory spike so didn't do that after but memory usage kept going up).

After some time the metadata download seemed to have frozen (I couldn't see what went wrong) so I closed the program and restarted which is the diag package attached.

### Diagnostics ID

443db25e-ce5d-42fa-9889-9e30c19fe964

**Comment by JosefNemec** [comment] 2023-12-27 17:06
You have a lot of extensions installed so this can be easily caused by one of those. Please retest with Playnite running in safe mode.

**Comment by JosefNemec** [comment] 2023-12-27 17:07
main menu -> help -> restart in safe mode

**Comment by arandomguysomewhere** [comment] 2023-12-27 17:14
Hi, I tried again in safe mode, same behaviour, here's the diag ID: 39dbf43b-dfa3-4ea6-8cef-923cdff10a79

I retested by selecting a few hundred Steam games with no metadata for a metadata download and after 22 out of 138 metadata downloads memory usage jumped by over 20 MB and continues to grow with the sort setting of descending by date modified.

**Comment by JosefNemec** [comment] 2023-12-27 17:28
> memory usage jumped by over 20 MB

Increase in memory usage is expected when you start functionality like metadata downloads, those features need memory. Playnite is also written in C# which is garbage collected language which doesn't always immediately release memory once it's not used, it may take some time depending on what the app is doing.

Lastly, Playnite is currently being completely rewritten for Playnite 11 version so it's unlikely I'll be looking into this more for P10. Metadata downloads worked like this for years now and it wasn't an issue so it's not wort it digging into it now (when the code is being rewritten anyways), imo. I will make sure there are no leaks in P11 when it comes to this.

**Comment by arandomguysomewhere** [comment] 2023-12-27 17:30
Ok thanks, seemed like some garbage collection related problem for large scale libraries so hopefully this helps P11 functionality. A hibernate and resume seems to have triggered the GC. If possible please add an option to pause and view logs for metadata downloads so we can know what's wrong in the future versions, would be very handy especially for large and diverse libraries!

**Comment by JosefNemec** [comment] 2024-04-04 16:25
Closing as I don't think this is memory leak on our side.

**Closed by JosefNemec** 2024-04-04 16:25 UTC
Labels: bug
