### ISSUE TITLE
itch softwares installed in folders other than ~\AppData\Roaming\itch\apps aren't detcted

### ISSUE THREAD

**Issue by azumukupoe** [JosefNemec/Playnite#1059] opened 2019-03-01 15:25 UTC

**Comment by JosefNemec** [comment] 2020-02-01 17:20
Is this still an issue? I've tested this with latest itch client version installed to custom location and everything seems to work properly.

**Comment by JosefNemec** [comment] 2020-02-12 16:24
Closing, I can't reproduce it with latest version, it was probably fixed on itch's side.

**Closed by JosefNemec** 2020-02-12 16:24 UTC
Labels: bug
