### ISSUE TITLE
Random deleting game from the list

### ISSUE THREAD

**Issue by sekuka925** [JosefNemec/Playnite#352] opened 2017-12-22 17:24 UTC
While i was editing description text  and adding some screenshots in games from internet source (see pic), playnite became blank, refreshed the overlay but the game that i was editing was deleted from the list with its saved info. Maybe its too much info for the program and it became unstable? however, after continuing with other games everything seems normal, at least for now
![1](https://user-images.githubusercontent.com/4690548/34306768-25086c5a-e745-11e7-9697-1cdd904f8059.jpg)
![2](https://user-images.githubusercontent.com/4690548/34306774-2787eed8-e745-11e7-879b-b45dd3ff5d4d.jpg)

**Comment by sekuka925** [comment] 2017-12-23 08:55
the game reapeared after restarting PC

**Comment by JosefNemec** [comment] 2017-12-23 09:01
PC restart have nothing to do with it, you probably deleted official game (like Steam one). These games are re-imported automatically when deleted at each Playnite startup or if you reload the library manually (from menu or by F5);

**Comment by sekuka925** [comment] 2017-12-23 09:03
the game was manually added, it was non client game, but still, i didnt remove it from the list

**Comment by JosefNemec** [comment] 2017-12-23 09:07
Are you sure you didn't enable filter by mistake? Anyway can you please attach diagnostics package (crated from "About" menu)?

**Comment by sekuka925** [comment] 2017-12-23 09:09
i checked filter, it cant be that... how can i create diagnostic package?

**Comment by sekuka925** [comment] 2017-12-23 09:13
[package.zip](https://github.com/JosefNemec/Playnite/files/1584005/package.zip)
found it, dont know if it will be helpful as its not happening right now

**Comment by JosefNemec** [comment] 2018-01-08 10:25
I'm unable to reproduce this, the logs show way too many game deletion records to be any helpful. I'm closing this for now. Please feel free to reopen if you find a way how to reproduce this on demand.

**Closed by JosefNemec** 2018-01-08 10:25 UTC
Labels: bug
