### ISSUE TITLE
time played not working as intended

### ISSUE THREAD

**Issue by dumpysauce** [JosefNemec/Playnite#703] opened 2018-07-11 05:09 UTC
The time tracking is not working correctly. Some games it counts and some it does not. For example I added a shortcut for fortnite. I then played for about a hour. It says 10 seconds played. 
It also does this for other games. Most my other games are from steam, and sometimes it wont count time for those games either. 
And yes I am launching all the games from playnite. 
Thanks

**Comment by JosefNemec** [comment] 2018-07-17 16:15
Can you post examples of games that are having this issue? Specifically how the play action is setup. Also it's weird that you are having issue with Steam games as well, because we detect if the game is running (and count time based on that) from data that Steam itself provides. Can you specify what Steam games are having problems?

**Comment by dumpysauce** [comment] 2018-07-17 19:03
So I found that the first time I run the game from playnite it does not properly track the time. But all the times after that it works correctly.

**Comment by kilometrix** [comment] 2018-12-19 18:33
I manually added the game to Playnite library and then edited the play time for it. Later I noticed that the play time did not change after a couple of game sessions. However, if I open the edit window for the game I see that play time _in seconds_ changes correctly.

**Comment by JosefNemec** [comment] 2019-08-05 13:58
Can somebody verify if this is still an issue with Playnite 5?

**Comment by Takobyte** [comment] 2019-08-15 00:27
I think this might be the case for games that run from a launcher like Minecraft.

**Comment by afaf123** [comment] 2019-09-01 04:45
Still an issue. I recently tried opening a game by launching through Playnite via the play button, and it didn't record the amount of time. It still states that the game has not been played.

**Comment by afaf123** [comment] 2019-09-01 07:11
> I think this might be the case for games that run from a launcher like Minecraft.
> Execution Path + Time Played showing Not Played: https://i.imgur.com/dPMnVR9.png
> When you hit play: https://i.imgur.com/ziOQrtX.png

Were these games added to Steam as Non-Steam games?

**Comment by JosefNemec** [comment] 2019-11-06 09:50
This should work with Playnite 5 according to my tests. I'm going to close this since I'm unable to reproduce it. If you have issues with play time counter then make sure you have `Installation Directory` also set for the game. The best solution would to import game by dragging and dropping executable onto Playnite's window. That should setup everything properly for you.

If you still have with play time counter not working properly then please open new issue for that game specifically. Thank you

**Closed by JosefNemec** 2019-11-06 09:50 UTC
Labels: bug
