### ISSUE TITLE
Fullscreen mode: Randomly can't interact with the options menu sometimes

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1272] opened 2019-07-27 03:28 UTC
When using the desktop mode, sometimes if you press the options menu immediately after moving to a game cover, the menu opens, but moving the pad keeps moving between covers instead of interacting with the opened options menu. 

Check the video to see what I mean:

![option bug](https://user-images.githubusercontent.com/1389286/61989399-5be31300-aff4-11e9-9349-af2603dbc6d2.gif)

Higher quality video here:
https://gfycat.com/glisteningcompetentbaboon

**edit:** I'm not to sure if selecting it instantly is the cause, because it has randomly happened even when not moving fast and also when switching tabs, but I've found that moving fast is the easiest way to reproduce the bug.

**Comment by JosefNemec** [comment] 2019-07-29 12:30
I found a way how to reproduce this easily, but it looks like some weird bug in WPF :(

**Comment by sengtsan** [comment] 2020-05-25 14:36
I think I encounter this, or a related bug. The options menu for the game persists even when you exit the game. This error seems to pop up at random. 99% of the time everything works as expected. 

I have attached a video. 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/63714826/82822194-47cea300-9e9d-11ea-978e-82d8398930ed.gif)

**Comment by JosefNemec** [comment] 2020-09-24 08:11
Will have to postpone this to Playnite 9. All the menus will have to be reworked as separate window entities to make this 100% reliable.

**Comment by JosefNemec** [comment] 2021-02-09 17:24
Fixed in devel9.

**Closed by JosefNemec** 2021-02-09 17:24 UTC
Labels: bug
