### ISSUE TITLE
Playnite Icon when starting a game

### ISSUE THREAD

**Issue by PhrozenByte** [JosefNemec/Playnite#354] opened 2017-12-22 18:15 UTC
If Playnite isn't running and one starts it with the `-command` option (i.e. to immediately launch a game), Playnite uses the game's icon as window icon (visible in e.g. Windows' taskbar) rather than its own icon. This persists even when closing/minimizing Playnite to the tray and bringing it up again, and when launching another game. I'm using Windows 10 Pro 1709 x64.

**Comment by JosefNemec** [comment] 2017-12-23 08:56
I can't reproduce it, what game does it? Some custom or official one (from Steam for example).

**Comment by PhrozenByte** [comment] 2017-12-23 12:50
Basically any game no matter where it is from (Steam, Origin, Uplay, GOG or custom).

It looks like this issue is related to the game's icon, what apparently seems to be a bit broken. When creating a desktop shortcut for a game without a icon, Playnite sometimes creates a shortcut with Windows' "empty file" icon (e.g. Medal of Honor Pacific Assault via Origin), sometimes it uses Playnite's icon (e.g. Assassin's Creed IV Black Flag via Uplay). However, even a desktop shortcut for a custom game that uses the executable's icon (e.g. MTA San Andreas) ends up with Windows' "empty file" icon. Some other games (e.g. Grand Theft Auto V via Steam) do have the correct icon. Playnite always uses the icon depending on the above when starting Playnite with the `-command` option.

Here's how it looks like when starting Grand Theft Auto V:

![playnite-command-windowicon](https://user-images.githubusercontent.com/920356/34319561-c78bd9d0-e7e5-11e7-9da8-29e259b694f3.png)

**Comment by JosefNemec** [comment] 2018-10-04 10:54
I'm going to close this. I think this is Windows issue since Playnite starts games using standard way any other .Net applications would do it and changing game startup procedure would make it impossible to track play time.

**Closed by JosefNemec** 2018-10-04 10:54 UTC
Labels: bug
