### ISSUE TITLE
Failed to import installed Steam games - error after latest update to PlayNite

### ISSUE THREAD

**Issue by dragonscythe** [JosefNemec/Playnite#450] opened 2018-01-26 23:40 UTC
Failed to import installed Steam games. Could not find a part of the path 'D:\PlaynitePortable\steamapps\libraryfolders.vdf'.

I received this error initially when I first installed PlayNite (the previous version to the latest). I resolved the issue then by uninstalling it and trying the Portable version.

I was prompted to update a few days ago and went ahead and allowed the update to install and it caused this error to begin happening on launch once again.

![image](https://user-images.githubusercontent.com/35371465/35465131-932c5f6c-02bf-11e8-8ade-36c9635c3e8c.png)

I resolved the issue by downloading the latest version of the Portable version and extracting that on top of the installation folder.

I forgot to get the diagnostics, but I think the issue may be caused by the fact that I log in with a non-administrator secondary account on my computer. I have it set so that I have to enter the Administrator account's password for UAC (probably totally unnecessary, but something I do for security).

I'm good to go, but FYI in case this helps anyone.

**Comment by JosefNemec** [comment] 2018-01-27 09:09
This looks like Playnite is unable to locale Steam's installation folder. There was no change to this detection in last update, so I'm not sure what might be causing it. Could you try to reinstall Steam to see if it fixes the issue?

btw it's Playnite, not PlayNite :D

**Comment by dragonscythe** [comment] 2018-01-27 20:58
Sorry to be unclear (and for the wrong stylization of the name "Playnite" :) ). I don't think it is an issue with the latest update.

I had the same problem with the previous version (which was the first one that I installed). I fixed it by switching to the portable version, initially. It only happened again after the update, which I'm assuming converted me from the portable version to the full-installed version. Downloading the latest portable version and extracting that on top of my installation folder resolved the issue.

I only think it might be the way I'm set up because I'm wondering if on the installed version it is having to use my Admin credentials to install but Steam was not installed using my Admin credentials (Steam was installed before I separated my Windows accounts out).

Not a big issue and, if that really is what is causing it, could be an extremely rare case. It is resolved for me and if anyone else does happen to run into the same error, I would suggest they try the portable version of Playnite.

**Comment by JosefNemec** [comment] 2018-01-29 10:33
This sounds like an edge case scenario. I'll look more into it when I get more time, it doesn't look it would affect many users right now.

**Comment by JosefNemec** [comment] 2018-05-23 16:28
I'm closing this since I'm unable to reproduce it. If you find a way how to reliably reproduce this then feel free to reopen.

**Closed by JosefNemec** 2018-05-23 16:28 UTC
Labels: bug

**Comment by pianosaurus** [comment] 2018-10-02 21:13
Any chance we could reopen this? My steps to reproduce is trivial: Don't have Steam installed.

With GOG (haven't tried the others for this particular issue), this works fine. I get a complete listing of the games I own on the service, with nothing installed. It would be nice if this was possible for Steam too, since I don't want Steam installed on this particular system. Without this, I will have to check the Steam web site separately to find out if I already own a game.
