### ISSUE TITLE
More control over the available filters

### ISSUE THREAD

**Issue by RagnarokAeon** [JosefNemec/Playnite#2024] opened 2020-09-28 01:32 UTC
There are a lot of platforms that I don't use, so I'd like to limit the dropdown to the five platforms that I do actually use, the same could go for genres. There are a lot of options that I personally use that are in the way of the filters that I do use. Just in general I'd think it would be nice to have more control over the filter options as far as what is viewed.

**Comment by darklinkpower** [comment] 2020-09-28 02:26
Duplicate of https://github.com/JosefNemec/Playnite/issues/1301

**Comment by JosefNemec** [comment] 2020-09-29 08:18
Definitely duplicate to #1301. I don't see a point of having an option to hide fields that are in use. I can see that causing issues where user would hide a field, forget about it, and then be confused why they can't filter by it.

**Closed by JosefNemec** 2020-09-29 08:18 UTC
Labels: enhancement
