### ISSUE TITLE
Playnite 10 game importation after opening is slower than Playnite 9

### ISSUE THREAD

**Issue by ppvnf** [JosefNemec/Playnite#3108] opened 2022-09-27 21:53 UTC
### Bug Description

First I would like to say that I like Playnite 10 a lot. However, the initial library scan is much slower than in Playnite 9 (it was pretty much instateneous). I am not sure this is a bug or a feature, but I preferred Playnite 9 in this regard.

https://user-images.githubusercontent.com/73800734/192641274-5fe5eff9-fba8-416b-8132-4331c5e06917.mp4

### To Reproduce

Use same library on Playnite 9 and 10 and compare how long it takes for the library to update in Playnite 10. On the video I didn't use a clean install for Playnite 10, just Playnite 9, but I did after and the result was the same.

### Diagnostics ID

d36ef5ec-69e9-4b2c-b4d1-9350348d03fe and e3b7c4f7-2d8e-4d9e-b208-e3c0ca25b8e7

**Comment by JosefNemec** [comment] 2022-09-27 22:02
Most likely because P10 by default checks for game file changes to calculate install size of games. You can test this by disabling install size calculation on library update in general settings.

**Comment by ppvnf** [comment] 2022-09-27 22:17
> Most likely because P10 by default checks for game file changes to calculate install size of games. You can test this by disabling install size calculation on library update in general settings.

It would make sense. However it didn't affect P10 opening speed. Only by changing this setting to manual I could make it faster:

![Captura de tela 2022-09-27 191551](https://user-images.githubusercontent.com/73800734/192647450-a21d646d-8b7f-43b8-a3d8-94a897de8704.png)

**Comment by JosefNemec** [comment] 2022-10-24 17:32
I'm unable to reproduce this myself. Can you please upload all `.db` files from `library` folder from Playnite's install folder?

**Comment by ppvnf** [comment] 2022-10-24 17:39
You mean those?
[library.zip](https://github.com/JosefNemec/Playnite/files/9853978/library.zip)

**Comment by JosefNemec** [comment] 2022-10-25 15:58
Fixed in master. It's close now performance wise to what it was in P9, but new scan features introduced in P10 still cause some slowdown. There is still a lot of room for improvement, but it will have to be done in P11 because it requires breaking changes to the SDK.

**Closed by JosefNemec** 2022-10-25 15:58 UTC
Labels: bug

**Comment by ppvnf** [comment] 2022-10-25 16:02
> Fixed in master. It's close now performance wise to what it was in P9, but new scan features introduced in P10 still cause some slowdown. There is still a lot of room for improvement, but it will have to be done in P11 because it requires breaking changes to the SDK.

Thanks for your awesome work!!
