### ISSUE TITLE
Parts of UI not themable / using static theme references.

### ISSUE THREAD

**Issue by Bigfootmech** [JosefNemec/Playnite#1595] opened 2019-12-17 19:28 UTC
I went through renaming every variable from Constants to find out which parts of the UI used what.

As well as to order stuff for myself.

I found that some parts of the UI were inaccessible (on purpose) such as the Settings screen.

However, some of the controls were using static references, rather than the theme ones (unintended).

Here's a list of parts that I believe to be hard coded as far as the theme is concerned:

Search box magnifying glass, and "clear text" (backspace) button.

Filter panel Name box "clear text" (backspace) button
Filter panel dropdown boxes

Settings window text on starred* lines
Settings window editable text boxes
Settings window "Save" and "Cancel" buttons (bottom right)
Settings window metadata tab dropdown boxes
Settings window metadata tab text to the right of boxes
Settings window separator/border centre vertical, bottom horisontal, and the right part of top horisontal lines (but the left part of the top horisontal line is controlled in DefaultControls/TreeView.xaml)

There may be other parts that I missed, though I tried to be thorough.

I'm attaching a theme with which these can be tested. If you open Blend, and "search in entire solution" for the "hacky" variables, they should not appear anywhere else.

[PlainWhite.zip](https://github.com/JosefNemec/Playnite/files/3975063/PlainWhite.zip)

**Comment by Bigfootmech** [comment] 2019-12-17 19:55
Hmm. Some of this might actually be to do with the generated/default style not changing things from an even previously inherited style?

Ie: The Default style falls back to -something-

Here's a list of files not touched by my changes so far:

CustomControls/HtmlTextView.xaml
CustomControls/NullableIntBox.xaml
CustomControls/NumericBox.xaml
CustomControls/SliderEx.xaml

DefaultControls/Border.xaml
DefaultControls/Popup.xaml

DerivedStyles/BottomButton.xaml
DerivedStyles/DetailsHyperlink.xaml
DerivedStyles/DetailsScrollViewer.xaml

Images/applogo.ico
Images/applogo.png
Images/applogo_black.ico
Images/applogo_dark.png
Images/applogo_white.ico
Images/csharp.ico
Images/custom_cover_background.png
Images/discord.png
Images/patreon.png
Images/powershell.ico
Images/python.ico
Images/reddit.png
Images/twitter.png

Views/Library.xaml
Views/LibraryGridView.xaml
Views/LibraryListView.xaml
Views/MainWindow.xaml
Views/Sidebar.xaml

**Comment by JosefNemec** [comment] 2020-02-10 14:20
> Search box magnifying glass, and "clear text" (backspace) button.
> Filter panel Name box "clear text" (backspace) button

I added media icon resources for them, they should be changeable now.

> Filter panel dropdown boxes

Those are just CheckBoxes, changing CheckBox style will update them as well (it worked when I tried it).

> Settings window text on starred* lines

Those inherited from `FontSize`, `FontFamily` and `TextBrush`. I made a slight alteration and they will now base itself on `BaseTextBlockStyle`.

> Settings window editable text boxes

Those relate to `NullableIntBox` and `NullableIntBox` and static reference issue I mention later.

> Settings window "Save" and "Cancel" buttons (bottom right)

You need to change `BottomButton` style (I know it's a stupid name, but I can't change it now without breaking things).

> Settings window metadata tab dropdown boxes

Again, those are just CheckBoxes.

> Settings window metadata tab text to the right of boxes

Fixed.

> Settings window separator/border centre vertical, bottom horisontal, and the right part of top horisontal lines (but the left part of the top horisontal line is controlled in DefaultControls/TreeView.xaml)

Fixed, all borders there now use `NormalBorderBrush`.

> All mentioned ico, png image files.

I can't reproduce that. Adding different image file under the same name to custom theme changes it in the application.

> DefaultControls/Border.xaml
> DefaultControls/Popup.xaml

As far as I understand it they are handled in a special way by WPF and you need to create custom one with unique key name for each change. I'm not sure I can do anything about that.

> DerivedStyles/BottomButton.xaml
> DerivedStyles/DetailsHyperlink.xaml
> DerivedStyles/DetailsScrollViewer.xaml
> Views/Library.xaml
> Views/LibraryGridView.xaml
> Views/LibraryListView.xaml
> Views/MainWindow.xaml
> Views/Sidebar.xaml

Can't reproduce. Changing those changes properly in the application (Sidebar is not used anywhere right now, that's intentional).

> CustomControls/HtmlTextView.xaml

All supported properties are being overwritten on every place of use  (all two of them). That's why global changes have no effect.

> CustomControls/NullableIntBox.xaml
> CustomControls/NumericBox.xaml
> CustomControls/SliderEx.xaml

The problem is `StaticResource` reference. To fix this I'm now not including BasedOn for those, but they have their own full style definition. I think I could do something about those statics not working, but it would require a lot of breaking changes.

**Comment by JosefNemec** [comment] 2020-02-12 16:23
I'm going to close this for Playnite 7 release. If you find some other similar problems then please open new issue for it. Thank you

**Closed by JosefNemec** 2020-02-12 16:23 UTC
Labels: bug
