### ISSUE TITLE
Missing line in fullscreen mode

### ISSUE THREAD

**Issue by Evene174** [JosefNemec/Playnite#608] opened 2018-05-15 20:38 UTC
In fullscreen, if user insert in detail mode and back again to cover mode - Playnite automatically scrolls down and loses the top line with the games.
![before detail mode](https://user-images.githubusercontent.com/26068083/40082229-ce973708-58a9-11e8-89fc-9a0c12f054c7.png)
![back to cover](https://user-images.githubusercontent.com/26068083/40082234-d27d006e-58a9-11e8-8592-242fe60bc09f.png)

**Comment by JosefNemec** [comment] 2018-05-16 10:52
I've seen this, but I'm unable to reproduce this reliably. Does it happen every time for you?

**Comment by Evene174** [comment] 2018-05-16 13:54
@JosefNemec  I make video, I hope it will help to recreate the bug.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/26068083/40121245-8cf2a4f4-593a-11e8-9253-4d65672c8ceb.gif)

Occurs with different number of rows and columns.

**Comment by JosefNemec** [comment] 2018-06-06 13:47
Released in 4.30

**Closed by JosefNemec** 2018-06-06 13:47 UTC
Labels: bug
