### ISSUE TITLE
Failed to import games from Battle.net. Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by networldsystems** [JosefNemec/Playnite#2021] opened 2020-09-26 03:17 UTC
Ran into this alert while doing an library update. 
![playnite](https://user-images.githubusercontent.com/26266261/94328937-55478700-ff7c-11ea-8f3d-b24a653eb5a5.jpg)
Running Playnite 7.9. 

First encountered the issue when updating libraries via F5. Tried updating just Battle.net. Same result. Just prior to noticing this issue, games were successfully added from Battle.net.

I searched the bug reports for "battle.net" and "Object reference not set to an instance of an object." before reporting.

Thanks.

**Comment by JosefNemec** [comment] 2020-09-26 06:48
Please attach diagnostics package that was requested in issue template.

**Comment by networldsystems** [comment] 2020-09-26 08:01
62ed193a-bf60-48d7-94fc-36d9eb67a25e

    On Saturday, September 26, 2020, 1:48:35 AM CDT, Josef Nemec <notifications@github.com> wrote:  
 
 


Please attach diagnostics package that was requested in issue template.

**Comment by networldsystems** [comment] 2020-09-26 19:41
Update:
After a reboot (and launching the battle.net client) I was able to update battle.net library individually. Immediately following, an F5 update produced the same alert (exception).
New diag package: 0440338e-ba6c-4d48-80ef-1cd7a354b219
Please let me know if you do not wish to receive any further reports. 

Coincidentally, last Thursday I was teaching a class about unanticipated exceptions, handling, etc. in .NET. This issue serves to illustrate that lesson - good job!

Thanks,
Steve

    On Saturday, September 26, 2020, 1:48:35 AM CDT, Josef Nemec <notifications@github.com> wrote:  
 
 


Please attach diagnostics package that was requested in issue template.

**Comment by JosefNemec** [comment] 2020-09-29 08:35
Please reproduce it again with [this debug build](https://github.com/JosefNemec/Playnite/files/5297569/BnetDebug.zip) of battle.net plugin (extract into `%localappdata%\Playnite\Extensions\BattleNetLibrary\`) and generate new diagnostics package. Thanks

**Comment by networldsystems** [comment] 2020-09-30 16:38
I have not encountered that exception since my last report. I've tried every I can think of without disconnecting from the Internet. Perhaps it was a transient issue on the battle.net side?
I'll keep trying daily. If I see it, I'll try it with the supplied build.
Thanks,
Steve

    On Tuesday, September 29, 2020, 3:35:30 AM CDT, Josef Nemec <notifications@github.com> wrote:  
 
 


Please reproduce it again with this debug build of battle.net plugin (extract into %localappdata%\Playnite\Extensions\BattleNetLibrary\) and generate new diagnostics package. Thanks

**Comment by darklinkpower** [comment] 2020-09-30 20:11
I think I had this same issue with either GOG or Epic plugin when their servers were down so maybe it's a similar thing.

**Comment by JosefNemec** [comment] 2020-10-02 07:13
Thanks for additional info, I'm closing this for now.

**Closed by JosefNemec** 2020-10-02 07:13 UTC
Labels: bug

**Comment by networldsystems** [comment] 2020-10-19 01:19
Ran into this issue again after updating to Playnite 8.3
Diag Package: f6051350-81ba-493b-89a9-c844043c4ab8
Thanks

    On Friday, October 2, 2020, 2:13:35 AM CDT, Josef Nemec <notifications@github.com> wrote:  
 
 


Closed #2021.

**Comment by JosefNemec** [comment] 2020-10-19 05:59
There was no change to battle.net integration in 8.3. I'm pretty sure this issue is somehow connected to either network issues or outage on battle.net's side, because it always starts to work for people after a while.
