### ISSUE TITLE
Add Game > Scan Automatically > Scan Folder picks up executables already in the library

### ISSUE THREAD

**Issue by nodakamakadon** [JosefNemec/Playnite#1050] opened 2019-02-24 23:33 UTC
It would be good to also exclude other files detected in locations of existing library items.

**Comment by whismerhill** [comment] 2019-02-25 00:32
good idea, no idea how feasable that is however since I don't know a thing about the stores API and if you can retrieve the executables' path

could also be mitigated by https://github.com/JosefNemec/Playnite/issues/1044
IF games were installed inside organized subfolders that is

**Comment by JosefNemec** [comment] 2020-10-09 13:23
I'm not sure about this, it would slow down import process quite a lot.

**Comment by bastus1986** [comment] 2022-12-31 08:47
I was wondering if any progress has been made on this issue. I have been working with Playnite for a week or so. I think I have a unique situation where I have 5 separate windows users on my PC and am using Playnite to give everyone access to shared  libraries like search of our Steam accounts, as well as individual account like Epic and Xbox PC. It's working pretty well but I have had issues with the more obscure launchers like Legacy and Amazon Games when it comes to installations across multiple Windows accounts, Amazon requires a weird authentication or something that requires each Windows users to have a unique installation library, these more problematic launchers have a simple workaround. Just create a games shortcut folder and add a shortcut from the games installation folder into this shortcut folder. Then Scan this folder for your shortcuts. We still have the duplication issue, but I'ma able to mitigate that by removing the scanned shortcuts after Playnite inports them successful. Being able to treat this folder just like a library would be ideal as it gives me a work around for almost any problematic launcher or Windows user conflicts. Gonna jump on the Patreon and see if I can bring a little more light to the issue. Keep it up guys, this software really is great.

**Comment by JosefNemec** [comment] 2022-12-31 10:03
I plan to do this in the next P10 update.

As far as library integration that's based around folders, that would be imo better to be implemented as a 3d party plugin, because everybody's setup will be different.

**Comment by KL13NT** [comment] 2023-05-09 14:56
Is there any progress on this request? It seems this issue may be a duplicate of #1044. If you don't have time to work on it point me in the right direction and I'll work on it myself.

**Comment by JosefNemec** [comment] 2023-05-09 15:05
One of the recent updates added an option to hide already imported games from this dialog.

**Closed by JosefNemec** 2023-05-09 15:05 UTC
Labels: enhancement

**Comment by live-onlinebuild** [comment] 2025-01-03 04:34
> 我计划在下一次 P10 更新中执行此操作。
> 
> 基于文件夹的每个库集成，我认为最好将其作为第三方插件来实现，因为人们的设置会有所不同。

非常抱歉，我没有找到有关过滤的插件，请问是否已经实现，他的名字是什么？
亦或者是某个配置里面添加正则表达来过滤吗

**Comment by JosefNemec** [comment] 2025-01-03 08:59
English only here please, thank you.

**Comment by live-onlinebuild** [comment] 2025-01-04 09:15
> English only here please, thank you.

I'm very sorry, I couldn't find a plugin related to filtering. Has it already been implemented, and what is its name?
Or is it a matter of adding a regex in some configuration to perform the filtering?
