### ISSUE TITLE
Disable automatic HDR revert after game closes

### ISSUE THREAD

**Issue by yngccc** [JosefNemec/Playnite#3724] opened 2024-04-03 14:14 UTC
### Feature description

After a game is closed HDR will always revert back to the state before the game is launched, is there a way to disable this behavior? If a game turns on HDR I want it to stay on after the game is closed.

**Comment by JosefNemec** [comment] 2024-04-03 15:52
Closed by mistake.

Don't know if it makes sense to not turn off HDR if it wasn't enabled prior to launching a game. We are reverting to the state that was before game was launched, which only makes sense to me.

**Comment by yngccc** [comment] 2024-04-03 16:12
In my case my monitor goes blank for a few seconds with switching in and out of HDR, it is annoying when I need to open and close a game multiple times to change some settings.

**Comment by lscholte** [comment] 2024-04-10 16:31
@yngccc based on your use case, I have 2 possible suggestions for you:
1) Disable the HDR checkbox in Playnite until you have finalized all the game settings you want. This will disable Playnite's automatic management of your monitor's HDR
2) Keep the HDR checkbox enabled in Playnite, but also enable HDR on your monitor manually (e.g. via windows settings). As long as you've done this, then Playnite should not be disabling HDR on the monitor upon exiting the game. Once you have finalized your game settings, you could turn off HDR on your monitor in Windows settings and let Playnite do the automatic management of HDR.

**Comment by JosefNemec** [comment] 2024-04-15 11:34
Closing as this is very niche use case not worth adding extra options and complexity to cover it.

**Closed by JosefNemec** 2024-04-15 11:34 UTC
Labels: enhancement

**Comment by Trusty88** [comment] 2024-05-26 08:24
Please re-open this thread. 

I'm having the same issue” after the W11 24H2 update:  "after a game is closed, HDR will always revert back to the state before the game is launched".

**Comment by lscholte** [comment] 2024-05-26 18:30
> Please re-open this thread.
> 
> I'm having the same issue” after the W11 24H2 update: "after a game is closed, HDR will always revert back to the state before the game is launched".

That is how the feature is intended to work. After the game exits, Playnite is supposed to revert HDR back into the state it was in prior to launching the game.

Are you saying there was a change in behaviour after you did a Windows update?

**Comment by Trusty88** [comment] 2024-05-27 14:03
Yes, 
24H2 with Windows Update (May 25 , no issues before the update!)

The HDR/AutoHDR function (on Windows) is OFF. 

HDR and AutoHDR (Windows) off --> Playnite launch --> automatic switch to the special nVidia DLDSR resolution  --> I play the game --> I quit the game --> Windows returns to the standard resolution, but in HDR mode!

**Comment by lscholte** [comment] 2024-05-31 04:04
24H2 is not in general availability yet. Whenever it is fully rolled out, I will then update my system and see if I can reproduce this behaviour and debug it.

**Comment by Manu270891** [comment] 2024-11-01 12:03
Now that Windows 11 24H2 is out, this issue has not been resolved. My monitor (LG 27GP95R-B) has HDR cappabilities, but since it's a LCD monitor, HDR is just a mess, I never turn it on (Windows or ingame). After closing a game that has been launched with Playnite, HDR turn on. The "Enable HDR Support" checkbox is unchecked in every game.

**Comment by lscholte** [comment] 2024-11-01 16:13
@Manu270891 I have seen a report that windows has an "automatically manage color for apps" setting that has caused HDR to turn on after a game exits. Can you take a look for this setting and see if it fixes your issue?

<img width="666" alt="image" src="https://github.com/user-attachments/assets/cbfbc88d-df8b-4bd3-9014-26f6e582744c">

**Comment by brunobf2** [comment] 2024-11-03 01:09
> @Manu270891 I have seen a report that windows has an "automatically manage color for apps" setting that has caused HDR to turn on after a game exits. Can you take a look for this setting and see if it fixes your issue?
> 
> <img alt="image" width="666" src="https://private-user-images.githubusercontent.com/6503344/382336427-cbfbc88d-df8b-4bd3-9014-26f6e582744c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1OTY0MDIsIm5iZiI6MTczMDU5NjEwMiwicGF0aCI6Ii82NTAzMzQ0LzM4MjMzNjQyNy1jYmZiYzg4ZC1kZjhiLTRiZDMtOTAxNC0yNmY2ZTU4Mjc0NGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDNUMDEwODIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWQwNTk0MDIzY2U0MmRkNzczY2ViNWYzNDQ0ZDc1NzU5Y2RlYWNkZGQyMjk4ODVhNjEwOTQxZjU5MmYxNTI2OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.fC-vM3ExeRR6hNRxAK0lANZArJlObZCKRnvu_7r0Zdk">

solved, thanks!

**Comment by Durabys** [comment] 2025-03-20 20:59
> Now that Windows 11 24H2 is out, this issue has not been resolved. My monitor (LG 27GP95R-B) has HDR cappabilities, but since it's a LCD monitor, HDR is just a mess, I never turn it on (Windows or ingame). After closing a game that has been launched with Playnite, HDR turn on. The "Enable HDR Support" checkbox is unchecked in every game.

THIS! The same damn problem! I deactivated Windows 11 HDR because it sucks harder than the vacuum of space and after I turn off the game and leave it....Playnite activates my Windows settings HDR on its own!

**Comment by lscholte** [comment] 2025-03-21 04:56
> > Now that Windows 11 24H2 is out, this issue has not been resolved. My monitor (LG 27GP95R-B) has HDR cappabilities, but since it's a LCD monitor, HDR is just a mess, I never turn it on (Windows or ingame). After closing a game that has been launched with Playnite, HDR turn on. The "Enable HDR Support" checkbox is unchecked in every game.
> 
> THIS! The same damn problem! I deactivated Windows 11 HDR because it sucks harder than the vacuum of space and after I turn off the game and leave it....Playnite activates my Windows settings HDR on its own!

You have 2 paths forward to resolve this:

1. Update to Playnite 10.35. This would be sufficient if you have no intention of ever wanting Playnite to toggle HDR whatsoever.
2. Or follow what is described in an earlier comment and disable automatic colour management in Windows. This would be necessary if you do plan on having Playnite toggle HDR.

**Comment by Durabys** [comment] 2025-03-21 16:27
> 2\. automatic colour management in Windows

Was already disabled long ago.
