### ISSUE TITLE
Option to disable game scripts

### ISSUE THREAD

**Issue by redactedscribe** [JosefNemec/Playnite#3604] opened 2023-11-14 16:01 UTC
### Bug Description

Pretty simple, the checkbox for a game's Global Script, at least for "Execute before starting a game" (maybe the other two too), has no effect. The script will always run.

### Diagnostics ID

-

### Screenshots

![Playnite DesktopApp_2023-11-14_17-37-16](https://github.com/JosefNemec/Playnite/assets/25013746/d96ac1c5-c332-4e08-bb5c-63d7e974d610)

**Comment by JosefNemec** [comment] 2023-11-14 20:20
Can't reproduce, disabling that option doesn't run global pre-script for me. 

Please attach diagnostics ID that was requested in issue template.

**Comment by redactedscribe** [comment] 2023-11-15 14:11
What if you add `$answer = $playniteapi.dialogs.showmessage("Message", "Title", "OKCancel", "information")` to the game's global script, ensure its Execute checkbox is unchecked, Save, then hit Play? My expectation is that the dialogue message window should not appear, but it does.

I have tried this with games of differing types, Battle.net ones, and ones manually added which just launch an executable. It's the same behaviour.

```
15-11 15:46:45.234|INFO |GamesEditor:Starting Diablo IV, b63b2753-14f6-4f1e-8515-a77a54877adc, Fen, e3c26a3d-d695-4cb7-a769-5ff7612c7edd
15-11 15:46:45.243|DEBUG|GamesEditor:Using plugin to start a game.
15-11 15:46:46.714|WARN |GamesEditor:Game startup cancelled by game script.
```

```
15-11 16:08:48.960|INFO |GamesEditor:Starting OpenRCT2, e871e85d-3893-436c-900d-a7c97f9ad9c3, 94df8ebb118db84f8085ed9a13a18897, 00000000-0000-0000-0000-000000000000
15-11 16:08:48.960|DEBUG|GamesEditor:Using generic controller start a game.
15-11 16:08:50.459|WARN |GamesEditor:Game startup cancelled by game script.
```

Any idea what could cause this?

**Comment by JosefNemec** [comment] 2023-11-15 14:21
>  to the game's global script,

There's nothing like "game global script". There are global scripts (configured in app settings) and game scripts. That checkbox disabled execution of global scripts, game script is always executed not matter what.

**Comment by JosefNemec** [comment] 2023-11-15 14:23
https://api.playnite.link/docs/manual/features/scriptingSupport/scriptingSupportOverview.html

**Comment by redactedscribe** [comment] 2023-11-15 15:49
> > to the game's global script,
> 
> There's nothing like "game global script". There are global scripts (configured in app settings) and game scripts. That checkbox disabled execution of global scripts, game script is always executed not matter what.

Right, the "Execute global script" for a game script is shown under each of the three game scripts (before, after, after exit). I thought these checkboxes toggled the scripts in each of these text fields, but that assumption is wrong. I didn't realise these checkboxes were all labelled the same.

To disable a game script from running I must remove the script from the text field (or comment every line), correct?

If so, maybe in the future we can have additional checkboxes which enable/disable these games scripts so that the script doesn't need to be removed/commented to be disabled.

**Comment by JosefNemec** [comment] 2023-11-15 16:13
> To disable a game script from running I must remove the script from the text field (or comment every line), correct?

Yes

**Comment by redactedscribe** [comment] 2023-11-15 16:44
Could this also get the enhancement label instead? Thanks for you help!

**Comment by JosefNemec** [comment] 2024-08-12 11:19
Closing as this is imo too niche of a feature plus you can achieve this by:

- adding `return` statement at the start of the script which will immediately exit the script
- commenting the code

**Closed by JosefNemec** 2024-08-12 11:19 UTC
Labels: bug
