### ISSUE TITLE
Can't auto update

### ISSUE THREAD

**Issue by L1cardo** [JosefNemec/Playnite#335] opened 2017-12-20 08:43 UTC
You said: Every time you start Playnite it checks for new version, downloads it in background and offers you update installation. Once you started Playnite it periodically checks for update every 4 hours.
But my playnite never checks for new version, I had to download new version and install it manually . I don't know if this is a bug or something .

**Comment by JosefNemec** [comment] 2017-12-20 08:45
Can you go to "About" menu, create diagnostics package and upload it here? Thank you

**Comment by L1cardo** [comment] 2017-12-20 13:06
[1.zip](https://github.com/JosefNemec/Playnite/files/1575593/1.zip)

**Comment by JosefNemec** [comment] 2017-12-21 09:12
Looks like Playnite can't reach update server. Can you check if [this URL](http://www.playnite.link/update/update.json) is available via browser? And also check if firewall is blocking Playnite?

**Comment by L1cardo** [comment] 2017-12-21 11:23
The URL is available via my browser ,and I added Playnite to the firewall list ,waiting for the next update to check if this will work.

**Comment by JosefNemec** [comment] 2017-12-21 12:22
You can also download 3.0 and check if it updates to 3.2 automatically.

**Comment by L1cardo** [comment] 2017-12-22 09:20
3.2 didn't auto update to 3.3.  
I downloaded 3.0 and it didn't auto update to the latest version as well....

It would be better if you add:
1. a update  button to update manually 
2. a download process bar for update download

**Comment by evgdovg1996** [comment] 2017-12-22 13:06
I can confirm that sometimes this bug occurs.
This happened for me when I was waiting for an update from 2.9 to 3.0.
The update button would be cool.

**Comment by JosefNemec** [comment] 2017-12-23 09:10
The update button will not solve this, the problem is that Playnite can't access update server for some reason.

**Comment by JosefNemec** [comment] 2018-01-05 14:53
Released in 3.4, there are now fallback addresses when connection to the main one fails. Please feel free to reopen this if the issue still occurs when (not)updating from 3.4 onward. Thanks

**Closed by JosefNemec** 2018-01-05 14:53 UTC
Labels: bug
