### ISSUE TITLE
Newly added game not launching

### ISSUE THREAD

**Issue by janforster** [JosefNemec/Playnite#526] opened 2018-04-22 17:28 UTC
Hey,

Related to 4.0 release: I am not able to launch a steam game that I have newly added after the update. Instead of starting-up, I get the following message: "Cannot start game: Object reference not set to an instance of an object".

Cheers

**Comment by JosefNemec** [comment] 2018-04-22 18:38
I can't reproduce it, could you please go to `About` menu and create diagnostics package for me? Also what do you mean by newly added, automatically imported game that was just added into your Steam library?

**Comment by janforster** [comment] 2018-04-22 19:55
Hmm, when I was restarting Playnite to change the theme it seems to have resolved the issue itself, so I cannot reproduce it now either :( .

It was a newly imported game that I have added to my steam library. I guess it does not make sense to send the diagnostic package in this case, right?

Sorry to bother you. I will keep an eye on it in case it happens again.

**Comment by JosefNemec** [comment] 2018-06-06 13:47
Released in 4.30

**Closed by JosefNemec** 2018-06-06 13:47 UTC
Labels: bug
