### ISSUE TITLE
Games Not hiding, duplicates of same platform, blurry images and more, oh my!

### ISSUE THREAD

**Issue by Scaledish** [JosefNemec/Playnite#1657] opened 2020-02-14 19:15 UTC
https://i.imgur.com/56BKAUu.mp4

**Comment by JosefNemec** [comment] 2020-02-14 19:30
Do you have a "Group by" enabled? There's an issue that duplicates may show on Grid view if it's enabled in Playnite 6. It's been fixed in Playnite 7.

**Comment by JosefNemec** [comment] 2020-02-14 19:32
The hiding issue is probably connected to the duplicate issue. I can't reproduce it on my system when I try to hide game that's not duplicated.

Other then that I don't know what's happening in the video, you just scroll bunch of times and mouse over some games. I'm not sure what should I take from that. Please clarify.

**Comment by JosefNemec** [comment] 2020-02-26 18:24
Closing since there's no response from original reporter.

**Closed by JosefNemec** 2020-02-26 18:24 UTC
Labels: bug
