### ISSUE TITLE
Close Playnite when a game starts, and restart Playnite when the game ends.

### ISSUE THREAD

**Issue by billybruiser** [JosefNemec/Playnite#147] opened 2017-10-08 15:42 UTC
This would be very useful for low performance computers like the GPD Win.  One sort of example of this is the Steam UI, where if you minimize it while a game is running, it frees up a large chunk of memory.

**Comment by nichols-356** [comment] 2017-10-08 16:21
This is already planned. https://github.com/JosefNemec/Playnite/issues/60

**Comment by JosefNemec** [comment] 2017-10-08 16:27
#60 it's not the same, that's when you close Playnite window manually. It's not related to launching game as this issue requests.

**Comment by thomaschampagne** [comment] 2017-12-24 09:37
@JosefNemec Is there any chance to have at least the following quick win "Close Playnite when a game starts"? Where "Close Playnite when a game starts" equals to existing "Exit" behavior.

I tried to build your project in VS2017 in order to make you a PR for this. But got errors :(. 

Thanks for your job @JosefNemec. Your software is near the perfection to me ;)

Tom

**Comment by JosefNemec** [comment] 2017-12-24 14:38
@thomaschampagne  yeah, that could be added easily, I'll try to add it into next version.

**Comment by thomaschampagne** [comment] 2017-12-24 15:50
@JosefNemec Sounds great ! Thanks in advance !

**Comment by thomaschampagne** [comment] 2017-12-30 16:49
You are the man !

**Comment by JosefNemec** [comment] 2018-01-05 14:46
Option to close the app has been released in 3.4, I'll leave this open until option to start it again is implemented.

@thomaschampagne VS 2017 should be enough to compile it, all dependencies are either NuGet packages or directly in repository. What errors are you getting? The best would be to contact me on [Discord](https://discord.gg/hSFvmN6), just post into `#development` channel what the issue is.

**Comment by Evene174** [comment] 2018-01-06 10:14
@JosefNemec Great function,thanks!
I don't know, maybe you already have some solution to resolve the problem, but:
I wrote simple bat code,that help you with implemention function re-open

@echo off
taskkill /f /im:"PlayniteUI.exe"
start "" /d "C:\Program Files (x86)\Kodi" /WAIT "Kodi.exe" (<--any path and program only for example)
start "" "C:\Program Files (x86)\Playnite\PlayniteUI.exe"

Thus, when user select "the close" option, you just need to assign this start code for a specific program.
I think the main difficulty is finding out the correct name of the program process.

**Comment by JosefNemec** [comment] 2018-01-06 14:03
That will only work if the Play action is set to executable, it won't work for Steam or Battle.net games that execute via url.

**Comment by Evene174** [comment] 2018-01-06 15:20
@JosefNemec It's works with url, but there is a slight delay before restarting:
@echo off
taskkill /f /im:"PlayniteUI.exe"
start steam://run/367670
timeout /t 10 /nobreak (time for guaranteed launch of any application)
:repeat
timeout /t 5 /nobreak (delay for unloading the processor from continuous process monitoring)
tasklist | find "ControllerCompanion.exe"
if not errorlevel 1 GOTO repeat
start "" "C:\Program Files (x86)\Playnite\PlayniteUI.exe"

So,this solution spends only 8-9 MB of memory to monitoring  process instead of 90-100 mb by Playnite

**Comment by JosefNemec** [comment] 2023-05-20 11:47
Closing. We are already quite low on resource usage (practically 0% CPU usage and sub 100MB of memory usage, while a game is running when closed to tray) so this is not worth doing.

You can see high memory footprint with a lot of extensions, but that's an extension issue and you probably shouldn't be installing them on low power device anyways.

Resource usage (mainly memory) will also be greatly improved in P11 once #1141 is done.

**Closed by JosefNemec** 2023-05-20 11:47 UTC
Labels: enhancement
