### ISSUE TITLE
Failed to download metadata (IGDB)

### ISSUE THREAD

**Issue by chidniu** [JosefNemec/Playnite#2088] opened 2020-10-30 16:06 UTC
When trying to download the IGDB Metadata for "Ghostrunner"  I get the error "Failed to download metadata: Object reference not set to an instance of an object.". Other games seem to work fine.

![Clipboard01](https://user-images.githubusercontent.com/5339604/97727667-f623e780-1ad0-11eb-86bd-462aa7977c5f.png)

I am using Playnite 8.5 on Windows 10 2004.

**Comment by JosefNemec** [comment] 2020-10-30 16:52
It's an issue with IGDB's data, they have invalid screenshot assigned to that game. I've submitted change to their db, it will start working once it's accepted.

I'll add some fail safe to Playnite to handle this case gracefully.

**Comment by JosefNemec** [comment] 2020-11-01 09:37
Fixed in 8.6

**Closed by JosefNemec** 2020-11-01 09:37 UTC
Labels: bug

**Comment by kb01guy** [comment] 2021-01-21 10:42
This happens again in 8.11, in my case on the game Valorant

**Comment by JosefNemec** [comment] 2021-01-21 14:29
Yes, it's the same issue, the game has some invalid screenshot assigned to it (if you edit the game on IGDB, you can see screenshot with no image). I don't why my workaround for this scenario doesn't work, but it's definitely caused by invalid data on IGDB's side.
