### ISSUE TITLE
Launching Mass Effect without Origin running causes issue

### ISSUE THREAD

**Issue by Silent-Hunter** [JosefNemec/Playnite#2063] opened 2020-10-17 23:23 UTC
**Describe the bug**
If Origin is not running, when I click the Play button on Mass Effect in Playnite, Origin starts, and immediately tries to update. The update always fails. From then on, even if Playnite isn't running anymore, trying to start Origin makes it think it needs to update, and the update always fails. The only fix is to reinstall. If I then close Origin, and try to launch Mass Effect in Playnite again, it happens again, even though I just 'updated' Origin manually. I assume this probably happens with any Origin game.

Launching Origin first solves the problem, but sort of defeats the purpose of even having Playnite.

**To Reproduce**
Launch Mass Effect from Playnite without Origin already running.

**Diagnostics ID**
7fe62095-946b-4f1c-9be1-f78020c8d70b

**Comment by JosefNemec** [comment] 2020-10-18 08:59
I can't reproduce it. The game launches just fine for me, not even starting Origin at all.

Overall, Playnite just starts game's executable and then it's up to the game what happens next. We have no control over Origin's startup procedure.

**Comment by JosefNemec** [comment] 2020-10-27 12:10
Fixed in 8.4

**Closed by JosefNemec** 2020-10-27 12:10 UTC
Labels: bug
