### ISSUE TITLE
Crash when switching from Fullscreen mode to Desktop mode 

### ISSUE THREAD

**Issue by Tiller** [JosefNemec/Playnite#1609] opened 2019-12-27 13:26 UTC
Similar issue than #1378

When trying to exit fullscreen mode to desktop mode, it often (9 out of 10 times?) silently crashes. The fullscreen app closes, but the desktop app never opens, and no playnite process is still running in the background

[playnite.log](https://github.com/JosefNemec/Playnite/files/4005368/playnite.log)

Playnite 6.4

**Comment by JosefNemec** [comment] 2020-01-04 10:22
I don't see any crash info in that log file, so it's probably not a crash, the Desktop process just doesn't start for some reason. Sadly I'm unable to reproduce it on my end.

**Comment by Le-Barbu** [comment] 2020-02-06 02:42
I have exactly the same issue with library plugins throwing "ArgumentNullException: La valeur ne peut pas être null"
my system is in french too
I tried uninstalling, removing the settings folder and reinstalling different versions (6.5, 5.8, 5.6, 4.74) they all crash at launch
It is weird because I have been using Playnite for months now

**Comment by JosefNemec** [comment] 2020-02-06 07:36
What library plugin is causing the crash? Also please go to"About Playnite" menu and create diagnostics package for me, thanks.

**Comment by JosefNemec** [comment] 2020-02-15 10:44
Can you try deleting `%appdata%\playnite\windowPositions.json` file to see if it fixes the issue?

**Comment by JosefNemec** [comment] 2020-02-26 18:34
Closing since there's no answer to my latest questions. However I have made some startup fixes in Playnite 7, so this might by fixed by them.

**Closed by JosefNemec** 2020-02-26 18:34 UTC
Labels: bug
