### ISSUE TITLE
A  feature to store the 'savegames' in the Playnite64 folder

### ISSUE THREAD

**Issue by Cyberavater** [JosefNemec/Playnite#1623] opened 2020-01-10 14:57 UTC
If Playnite64 could somehow fool the game to store the save game data in its own User folder rather than C:\Users\Bla\bla\bla... It would be very useful for making games portable, Thanks!

**Comment by JosefNemec** [comment] 2020-01-10 15:21
You can already do that without any support from Playnite by creating symbolic link to the original save folder (there are also GUI tools for it, just google "windows symlink gui").

I'm not sure if it would be worth adding support for this into Playnite since you would still need to manually specify all folders that should be linked and there are already tools for doing that.

**Comment by Cyberavater** [comment] 2020-01-10 15:27
> I'm not sure if it would be worth adding support for this into Playnite since **you would still need to manually specify all folders that should be linked and there are already tools for doing that**.

Can't you do something about the **manually specify all folders** part?
BTW, thanks for working Playnite, I really appreciate it.

**Comment by Cyberavater** [comment] 2020-01-10 15:47
Umm, how about specifying all possible folders built-in?, so that whenever a game doing a save would fall under this feature, and all I have to do is nothing more than tick the 'Savegames in the Playnite64 folder'.

How about that?

**Comment by Cyberavater** [comment] 2020-01-10 16:08
And shouldn't just specifying 'C:\Users' would work? Since all savegames are deep with the subfolder of this folder. If Playnite can fake this folder shouldn't all game save in this folder and use from it as well?

**Comment by JosefNemec** [comment] 2020-01-10 16:31
There's no way we can automatically (and reliably) detect where the game's save files are stored. The only options would be to pull that info PCGamingWiki, which will still require you to specify wiki game to pull the info from (which will be done as part of #124).

Redirecting complete c:\users would redirect all user files (for ALL applications) to Playnite's folder, which is definitely something you don't want to do. Plus it's not technically possible since it stores some files that can't be moved under normal circumstances (like user registry entries).

**Comment by Cyberavater** [comment] 2020-01-10 17:49
> Redirecting complete c:\users would redirect all user files (for ALL applications) to Playnite's folder, which is definitely something you don't want to do. Plus it's not technically possible since it stores some files that can't be moved under normal circumstances (like user registry entries).

Well, how about making that function more specific? i.e. Applications that are running trough Playnite and have this feature ticked would only use this feature.

Also, I've seen the usage of portable registry for making portable apps. Tho, I don't know the detail of such coding since am not a programmer. But it is possible as I have many of those portable programs (which aren't officially portable) with file associates with many extensions, which only activates when running the program and deactivates on closing the program. (I can send you such application if you test it and understand the code yourself).

**Comment by Cyberavater** [comment] 2020-01-30 12:27
After giving some thoughts about it, I think you got the wrong idea to suggest "windows symlink GUI"
While in this case 'sandbox-like isolated operating environment' is required.
Check here;  https://www.sandboxie.com/PortableSandbox

<a href="https://www.sandboxie.com/">Sandboxie</a> should be open-source soon. Hope you'd look into it.

P.S. plz reply if you find this suggestion useful or garbage.

**Comment by JosefNemec** [comment] 2020-01-30 12:42
I don't think you understand what the core issue with your original request is. Any solution would require Playnite to know where the actual game data (save files) are stored. And there's no reliable automatic way of detecting that.

So in the end you would have to manually tell Playnite where those files are and then we could technically create a symlink (that's the only solution that would not break the game) to Playnite's folder if you want to save files to be stored there. But the question then is if it's worth adding such feature into Playnite since you can basically do the same by creating symlink with already existing tools.

Sandboxes are total overkill for this and it's not what they were designed for. They are designed to isolate real OS environment from the application, mainly used for security reasons.

**Comment by Cyberavater** [comment] 2020-01-30 13:39
>I don't think you understand what the core issue with your original request is. Any solution would require Playnite to know where the actual game data (save files) are stored. And there's no reliable automatic way of detecting that.

Maybe I failed to elaborate my **original** request. My request was to add a feature for local savegame support for easy portability. Manually Adding every directory is just insanely overwork and against my goal, to be honest.

> Sandboxes are total overkill for this and it's not what they were designed for. They are designed to isolate the real OS environment from the application, mainly used for security reasons.

It might be a little overkill but it would remove the need to detecting/knowing the save location and also solve the 'user registry entries' issue. And since you'll add it built-in you wouldn't be adding features that aren't necessary.

**Comment by JosefNemec** [comment] 2020-01-30 14:00
Using sandbox is just not an option, you would end up with a lot more data then just save files. It's just not what it's designed for.

I'm going to close this since it's basically a duplicate of #124.

There's just no way we can implement this in a way that it would work automatically with every (or even most) game automatically. It's just not possible.

**Closed by JosefNemec** 2020-01-30 14:00 UTC
Labels: enhancement
