### ISSUE TITLE
Twitch connection when importing games : error 400

### ISSUE THREAD

**Issue by xsresat** [JosefNemec/Playnite#1957] opened 2020-08-14 16:29 UTC
Hello,

I'm a French user of your great software. Since a few weeks, I have the same error code when I try to import my Twitch games.

Trnslation from my French screenshot : failure of import from Twitch : the distant server returned an error : (400) incorrect demand.

I tried many times to check the connection by launching the client itself (like said in the client menu), but it's still on "required authentification".

Is there something I can do, or is it a real new issue ? Can the change into Amazon prime gaming be the cause of this ?

My diagnostic folder is b799192e-8139-4651-9dad-afbc58e33bc5.

Best regards and congratulations for your  sofwtare.

![twitch 1](https://user-images.githubusercontent.com/69687755/90271356-fb6f7f80-de5b-11ea-826e-d0b4a6d264ba.JPG)
![twitch 2](https://user-images.githubusercontent.com/69687755/90271357-fc081600-de5b-11ea-809b-388cbaeea846.JPG)
![twitch 3](https://user-images.githubusercontent.com/69687755/90271361-fc081600-de5b-11ea-914f-6086d8886046.JPG)
![twitch 4](https://user-images.githubusercontent.com/69687755/90271362-fca0ac80-de5b-11ea-84d3-7a64c48626d4.JPG)

**Comment by JosefNemec** [comment] 2020-08-14 17:34
I can reproduce it myself, but I've prepared [debug build](https://github.com/JosefNemec/Playnite/files/5076077/TwitchDebug.zip) of Twitch plugin. Please reproduce the issue with it and generate new diag. package. Thanks

Extract it to `%localappdata%\Playnite\Extensions\TwitchLibrary\`.

**Comment by EustaceCS** [comment] 2020-08-16 10:34
If I remember correctly, all Twitch library games are about to be migrated into Amazon Games (even better, all games you own from Twitch can be fetched through Amazon plugin at a moment).
Since Twitch is abandoning stuff not related to streaming directly (mods support is being moved to Overwolf, games to Amazon Games...) it's probably not worth the effort in pondering Twitch integration bugs.

**Comment by JosefNemec** [comment] 2020-08-16 12:10
Do you have some link that confirms that mods support and game download support is being removed from Twitch app? If that's the case, then I can see us dropping Twitch App support, because there would be no reason to use it anymore.

Back to the issue. The problem is that I can't reproduce this and I haven't received any other reports that it's not working, other then this one. So my guess is that it's some localized issue.

**Comment by EustaceCS** [comment] 2020-08-16 12:33
Mod support: https://blog.twitch.tv/en/2020/06/22/announcing-a-new-home-for-curse-forge/
Games transition: somehow, I'm unable to dig official announcement out yet (will keep looking, 100% sure I seen it somewhere but their documents are a mess). From recent news: https://lifehacker.com/play-your-free-twitch-prime-games-with-amazons-new-game-1844208153

**Comment by JosefNemec** [comment] 2020-09-29 08:29
Closing since requested information from debug plugin was not provided.

**Closed by JosefNemec** 2020-09-29 08:29 UTC
Labels: bug
