### ISSUE TITLE
Playnite Crashes on grid view if selecting with high zoom

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1807] opened 2020-05-11 02:16 UTC
**Describe the bug**
Playnite Crashes on grid view if selecting with high zoom

**To Reproduce**
Set a high zoom and keep selecting games. I've found that it happens when the zoom is more than 80%

**Screenshots**
Starts happening around this zoom
![imagen](https://user-images.githubusercontent.com/1389286/81518340-5e082b00-9303-11ea-8237-4bd3004893fb.png)

Video on how to reproduce
https://gfycat.com/infantilegreedyhamster

Playnite shows as not responding on Task Manager, but CPU % keeps changing and memory usage keeps increasing
![imagen](https://user-images.githubusercontent.com/1389286/81517306-23e95a00-9300-11ea-988e-4b6a543bccb8.png)

![2020-05-10_21-02-27](https://user-images.githubusercontent.com/1389286/81517820-b5a59700-9301-11ea-948a-420d4031cc86.gif)

**Diagnostics ID**
Diagnostics ID generated after killing app in task manager and rebooting
aba62ddd-13b1-41a2-926c-0bdfe90a69a3

**Comment by JosefNemec** [comment] 2021-12-16 11:29
I just can't reproduce this. No idea what to do with this. Especially since it's not a crash and it just freezes according to your video.

**Comment by JosefNemec** [comment] 2022-01-22 09:35
Still can't reproduce it. Can you upload your library for me somewhere if you are still able to reproduce it on demand? I think it might be related to some specific image files you have in your library.

**Comment by JosefNemec** [comment] 2023-12-03 11:45
Closing since I still can't reproduce it and this view will be completely replaced in P11 anyways.

**Closed by JosefNemec** 2023-12-03 11:45 UTC
Labels: bug
