### ISSUE TITLE
Fullscreen Controller or Window focus Bug (?) / Can be replicated, after every Resume from Sleep State 

### ISSUE THREAD

**Issue by Rincemac** [JosefNemec/Playnite#2073] opened 2020-10-23 14:29 UTC
Not sure if this might be related to some other things like "lost" focus when Playnite is in Fullscreen mode and my system wakes from Sleep state, since Playnite 8 a weird bug happens after every single resume:

### Behavior:

- Playnite is in fullscreen mode. 
- System resumes from sleep state
- Playnite gets back into focus
- Playnite Window is apparently correctly in focus
- However, as soon as Controller _directional input_ is used, instead of navigating on the game grid, the Windows system "top window" (for Playnite window control, since the menu bar is invisible in full screen) pops up as per Screenshot 
- Pushing **A** moves correctly into the sub-screen of currently marked title in grid. In this example, Horizon Zero Dawn is selected and can be navigated to, **B** Button cancels back out. Another push of A in sub-screen starts the game correctly.

 **BUG:** 
- No directional navigation possible in game grid. Up/Down navigate in the sub (Windows) menu. I can't "escape" out of the menu.
- When starting a title, this behavior is gone and normal navigation is possible again (Windows system menu does not pop up again after Playnite regains focus once game is exited)
- alternative: attach a keyboard, mouse to cancel out of menu.

Notes: 
- No other program's windows are open, ie. available in Task Switcher, when this happens to exclude any other program interfering with this.
- I am running ReWASD, but so far this has not messed with any Playnite functions.

Can you please take a look at what might cause this? I never had this behavior before Playnite 8. Might have something to do with focus falling on the (invisible) Playnite full screen top menu bar instead of navigation grid is my personal assumption?

Let me know if you want me to attach any log files. Happy to update here if needed.

![PlayNite_FullScreen_Bug](https://user-images.githubusercontent.com/24958093/97014744-02e19200-154b-11eb-91a7-3ff45b497239.png)

**Comment by JosefNemec** [comment] 2020-10-23 14:41
That menu will popup if ALT key is pressed. If it only happens when using ReWASD, then it's not an issue in Playnite.

**Comment by Rincemac** [comment] 2020-10-23 15:48
Thanks for the reply.

I just confirmed that ReWASD is not the source of this for me - I switched the tray tool off completely and retested the behavior.

I still get the "ALT" menu somehow after the **first** resume from sleep state, after starting a game it's gone and normal usage is possible.

For ReWASD: I have been running it since first using Playnite v7 a long time ago without that particular issue. But I can live without it as it has become redundant for a lot of modern games anyway.

As for this menu popup:
It started happening after updating to Playnite 8.1 sometime last week. 

I didn't change any other tools/software/drivers, so I posted here just in case it's something you might be able to look into.Very strange since I didn't change any other settings or software since weeks on the system (outside Windows updates, currently on Build 2004/Win10 Pro).

Also not sure what could send the "ALT" key to the system all of a sudden after resume from sleep. 
Of course this might be coincidental as these things go with Windows and Updates etc.

Let me know if you want to see a log, but I cannot find any hints in it currently that point to any faulty behaviors -> not sure if I can raise logging level somehow to capture control inputs?

**Comment by JosefNemec** [comment] 2020-10-23 16:00
There was no change to input handling in Playnite 8 or any change to Fullscreen mode overall that could cause this (only small UI fixes were made).

I'll try to reproduce this myself, but I can't see how this could be caused by Playnite, since Playnite doesn't simulate ALT key at all and mainly handles XInput input in Fullscreen mode.

**Comment by Rincemac** [comment] 2020-10-23 16:59
Let me know if you need any testing or logs (event logs etc.) from me, happy to help. I will monitor this as well and update here in case I find another culprit responsible for this. 

I know testing and confirming something like this is very much needle in haystack at this point.

**Comment by leftweet** [comment] 2020-11-18 23:04
Just wanted to add my experience with this bug, because I began noticing it on a fresh install of Windows last night.

The issue I saw seems to be the same as described by OP: Suspending the computer with Playnite in fullscreen will cause the ALT key to apparently become triggered when awakening the computer. I was able to replicate this every time the computer resumed from sleep.

I tried using different controllers, both a DS4 controller with DS4Windows enabled and an Xbox One controller over bluetooth, and I continued to experience the bug. I also tried disconnecting my bluetooth keyboard, but nothing changed. I also tried closing various background programs (such as Steam, DS4Windows, or Nvidia settings), but to no avail. Tapping the ALT key fixes the issue until the computer is suspended again.

What I have discovered is that if you take the focus away from Playnite at least once (such as tapping the Windows key or launching Task Manager) before suspending the computer, the bug does not occur after awakening the computer. So if you tap the Windows key, tap the Windows key again to return to Playnite, suspend the computer via Playnite, and then awaken the computer, Playnite should function as expected (ie without the ALT key having been triggered).

I have been unable to replicate the bug after focus has been taken away from Playnite at least once, so I am still uncertain what actually causes it. Stopping and the relaunching Playnite in fullscreen will cause the bug to return, as will restarting the computer (both of which are to be expected).

This was all tested on Playnite 8.7 last night, and nothing has changed in version 8.8 in my experience.

**Comment by JosefNemec** [comment] 2020-11-19 06:30
Thanks for additional information. It still doesn't explain why is this happening. Playnite itself never triggers ALT key to be pressed, so it's probably some 3rd part causing it. I don't even know if I can workaround this somehow.

**Comment by leftweet** [comment] 2020-11-19 20:36
So I did some more testing last night and I can confirm that it was indeed an application outside of Playnite causing the issue (at least in my specific situation). 

For me, it turns out that the Logitech Options application was trigging the ALT key keypress somehow. I realized that I had overlooked the application in my initial troubleshooting, but unchecking Logitech Options in the list of startup apps and restarting the computer resolved the issue. I’ve gone ahead and uninstalled Logitech Options since it’s not very important for my setup. 

Just wanting to post this update for Josef’s sake as well as for anyone with a similar issue who happens across this thread in the future. Not sure exactly what this might mean for other instances of the ghost ALT key keypress, but it does seem to be caused by a 3rd party based on my experience.

**Comment by Rincemac** [comment] 2020-11-25 09:37
Just back and seeing this:
I didn't even consider Logitech Options as a culprit, but can confirm I have it on that same system, so it is consistent. 
How did you test to see what key presses were sent to the system to find Logitech Options, out of personal curiosity? I've never had to catch "ghost key presses" so it's a great thing to learn.

The interesting/funny part in my case is: 
I had Logitech Options on that system for a long time, way before updating to the PlayNite 8.0 branch, even. But have not been using PlayNite Full Screen and then going back to it directly from suspend state much before 8.0, and if I never must have realized that this was a potential issue with that menu popping up. I recently started using it as "main frontend" due to several reasons, one of them being the ability to execute scripts on start/stop of a specific title (like "trigger HDR" on and off).

Problem for me is I will need Logitech Options unless I get rid of vast special buttons functions my Multimedia Keyboard, but I have to do some testing here what would work without using the program. Gotta die one death here it seems.

I wonder if it's just coincidence or if I just missed it happening before 8.0. 

One thought:
Is it possible to "reset" the Full Screen Experience Window to a "neutral" state on a suspend after a certain wait timer after wake-up and coming in focus? Maybe it can be an Option in Settings, so only people who experience that specific issue can "catch it"? It could even be a very simple "sent ESC" key after X sec. when resuming from sleep (to cancel that specific menu), unelegant but it might just work.

**Comment by JosefNemec** [comment] 2020-11-25 10:07
There was no change to input handling in Playnite 8, it's a coincidence if you didn't notice it before (or something else changed on your system).

I don't like adding workarounds like you propose, especially if it's to solve bugs in 3rd party apps. The problem with simulating additional inputs is that it could cause unforeseen issues. Especially if we are talking about critical keys like ESC, that could, for example, close dialogs that you might want not to be closed (the input has to be simulated system wide in this case).

**Comment by Rincemac** [comment] 2020-11-25 13:40
Yes, I assume it was coincidental with more use. 
I get it, it adds unwanted complexities when it's not directly necessary, no worries. Nothing else changed - outside of me actually updating to Win 10/2004 build, but I would rule that one out for this specific issue.

I can just close this now we have found the cause, it seems.

**Comment by JosefNemec** [comment] 2021-01-06 11:14
I'm closing this based on our previous conversation. I don't like adding workarounds to solve issues in 3rd party apps and simulating additional inputs could cause unforeseen issues somewhere else.

**Closed by JosefNemec** 2021-01-06 11:14 UTC
Labels: bug
