### ISSUE TITLE
a couple GOG games not showing up in Playnite

### ISSUE THREAD

**Issue by SteveS73** [JosefNemec/Playnite#1393] opened 2019-08-28 07:43 UTC
I have at least two GOG games that are not getting imported into Playnite. Both are games that I received as a backer for The Bard's Tale IV. There may be something unique about how GOG added these to my library that causes them to not be listed in Playnite?

(I have about 340 GOG games and haven't verified whether there are others missing.) 

Screenshot: 
![Capture](https://user-images.githubusercontent.com/54618476/63835481-0f7a5280-c967-11e9-9034-8e81212dd8ed.JPG)

**Comment by JosefNemec** [comment] 2019-09-03 13:23
Do you see them on your GOG profile page? I noticed this with Ion Fury, it doesn't show up in my profile page and the API we use doesn't report the game as well. But it is visible in the library.

**Comment by SteveS73** [comment] 2019-09-03 19:29
Hi, Josef. Thanks for the reply. Yes, they show in my GOG games profile. The screen capture I attached to my original post shows the Playnite window overlaying my GOG game profile page. Both have the search field set to "the bard".

**Comment by JosefNemec** [comment] 2019-09-06 07:30
That's not the profile page but library page. This is how you get to your profile page:
![image](https://user-images.githubusercontent.com/3874087/64409346-02591400-d089-11e9-86d8-0313c3f12901.png)

**Comment by SteveS73** [comment] 2019-09-06 20:08
Bingo. Neither of The Bard's Tale IV games are listed in my profile.

**Comment by JosefNemec** [comment] 2019-09-11 12:33
I figured out where the problem is, it will be fixed in 5.7. However you will need to use authentication method for linking GOG account, not the account name.

**Comment by SteveS73** [comment] 2019-09-11 23:54
Thanks, Josef. 
I'm already using authentication for GOG in Playnite 5.6 so I'll watch for 5.7 and let you know if all is well after updating.

**Comment by JosefNemec** [comment] 2019-09-18 10:02
Fixed in 5.7

**Closed by JosefNemec** 2019-09-18 10:02 UTC
Labels: bug

**Comment by SteveS73** [comment] 2019-09-18 20:31
Thanks! 5.7 fixed it.
