### ISSUE TITLE
Slow filtering of some game fields

### ISSUE THREAD

**Issue by shakeyourbunny** [JosefNemec/Playnite#1941] opened 2020-08-01 14:46 UTC
**Existing issue**
PlayNite gets a bit sluggish if it has to manage more than 4000-5000 games (in my case there are 10000 entries).

**Describe the solution you'd like**
Replace the current local database with a generic database layer and allow handling of database access through extensions. The database itself should handle all data and media files directly in it. Also provide a documentation which functions, structures and API calls should be implemented to have extensions for SQlite, MySQL/MariaDB, PostgreSQL, MS SQL(Express) possible to be written. Perhaps provide instead of a MySQL/MariaDB connector with a generic ODBC/JDBC one (which in turn is configurable in the system settings).

The database extension should have the basic stuff be configurable (if applicable), namely database user, database password, database name, database server and there should be a checkbox to enable have the connection encrypted (TLS/SSL).

PlayNite itself should ship with the current LiteDB / local filesystem implementation as such database extension, but it would be neat if a basic MySQL/MariaDB extensions would also be provided.

**Comment by JosefNemec** [comment] 2020-08-01 14:59
What operations specifically are slow for you? What system configuration do you have? I have testing database with over 20k games and I don't see any major slowdown (except with initial database load). I will need very specific description of the issue you are having.

I don't plan to add support for custom database engines. That's something that would bring very little value to end user and would complicate the whole application architecture a lot.

Lastly, it's Playnite, not PlayNite :)

**Comment by JosefNemec** [comment] 2020-08-01 15:02
I forgot to mention that there are two known performance issues currently present that are being fixed in Playnite 8:
- deleting unassigned game fields takes a very long time
- bulk editing game fields takes long time

Both of those will be fixed in Playnite 8.

**Comment by shakeyourbunny** [comment] 2020-08-01 17:42
Filtering is a bit laggy with about 15000 games, but I think this caused through initial loading I guess.

**Comment by Deide** [comment] 2020-08-02 12:23
Does the current database have an index? If not, that might help a lot with loading

**Comment by shakeyourbunny** [comment] 2020-08-02 14:38
I guess the database (or at least the index) is not kept in memory.

So every time I filter something, Playnite freezes for about 10 seconds and then loads.

After looking into the library folder, the main problem I see is that there is no real index and every other information is put into literally thousands of single json files. 

My suggestion is:
- make a proper index which is updated on changes (and keep it in memory, perhaps flush memory if the application is 5 minutes idle or so (maybe configurable)).
- don't use json files for everything, you parsing of (literally) 44000 JSON files takes time and this is slow even on a SSD.
- replace these folders with a single JSON file (if you insist using): categories, companies, features, games, genres, platforms, sources, tags.

**Comment by JosefNemec** [comment] 2020-08-02 14:56
All library data (except media files) are kept completely in memory, those json files are loaded only once during application startup (and as I mentioned there will be a big performance improvement to that initial load in Playnite 8). Also, we are not using LiteDB to store any library data, I don't know where you saw that.

The reason we are using this solution is because there is a big number of people using things like OneDrive or Google Drive to sync their library across multiple PCs. Having all data in a single file is bad for this scenario since even smallest change in library would force complete re-sync of the library file.

Filtering taking 10 seconds is definitely not a standard with current implementation. This is the first time I'm getting report like this and I can't reproduce it with my test libraries. Can you package your library and send it to me for analysis? Also please go to "About Playnite" menu and generate diag. package, thanks.

**Comment by JosefNemec** [comment] 2020-08-02 14:59
Also please specify what filtering is causing slowdown (what fields).

**Comment by JosefNemec** [comment] 2020-08-02 15:07
I've some additional testing and it seems that there is some slowdown happening (around 4 or so seconds on my machine with 8k games library), when filtering fields that allow assignment of multiple values (genres, developers etc.). Single value fields filter instantly for me.

This would point to some issue with filtering algorithm, I'll look into it.

**Comment by JosefNemec** [comment] 2020-09-01 12:22
Done in `devel8`.

**Closed by JosefNemec** 2020-09-01 12:22 UTC
Labels: bug
