### ISSUE TITLE
Sims 4 Never Discovered As Installed

### ISSUE THREAD

**Issue by faulkenberryjacob** [JosefNemec/Playnite#1617] opened 2020-01-03 15:25 UTC
**Describe the bug**
Sims 4 is installed on my other SSD (not C:) using the typical installation path (Origin\Sims 4). Playnite easily finds Battlefield V which is installed the same way - in the same Origin folder - however refuses to acknowledge Sims 4 is installed. Also, when manually checking 'Installed' under Settings -> Installation, that only fixes it temporarily. This seems to be reset - presumably when Playnite refreshes my library.

**To Reproduce**
Install Sims 4 on another drive (not C:) using default Origin installation configuration. If not found, manually set Installed then refresh Origin library.

**Screenshots**
![Sims4_Uninstalled](https://user-images.githubusercontent.com/37002363/71731636-dff2bf80-2e0a-11ea-97f9-f27dff8841aa.png)

**Comment by JosefNemec** [comment] 2020-01-03 16:07
Can you try repairing Sims 4 installation in Origin client? I'm unable to reproduce this.

**Comment by faulkenberryjacob** [comment] 2020-01-03 16:25
I'll give it a shot once I get home. Thanks for the speedy reply. Seemed
like a niche issue but wasn't sure if it could fester into an origin-wide
problem.

**Comment by faulkenberryjacob** [comment] 2020-01-03 21:22
I've done the following:

   1. Repaired Sims 4 in the Origin client.
   2. Closed Origin client.
   3. Removed Sims 4 from Playnite.
   4. Restarted Playnite.
   5. Refreshed Origin library inside Playnite.
   6. Verified Sims 4 was re-added, however was still marked as
   'Uninstalled'.

When I click the 'Install' icon on Playnite (shown below) it just runs Sims
4 like normal, yet even after closing Sims 4 it refuses to recognize it's
installed.
[image: image.png]

It seems to be functioning fine, so there's a plus! Just a minor issue with
the 'installed' variable not flagging.
My last job was in C# so I tried looking at the source code and seeing if
mine was some exception, though I didn't find anything amiss. Also, my lack
of time and attention might have contributed to that, haha.

Thanks for looking! Love Playnite, by the way. Has filled that itch I've
been wanting for years.

*Jacob Faulkenberry*
*faulkenberryjacob@gmail.com <faulkenberryjacob@gmail.com>*

**Comment by Foshitz** [comment] 2020-01-26 05:57
I´m having the same issue.

I have tried to manually point to the installation-folder and mark as installed, but after restarting Playnite and updating the library the game dissappears again.
Dragon Age, Mass Effect and Need for Speed (installed the same way) are all discovered and shown as Installed.

If it might help, here is the ID for my diagnostic package.
**e5bb152b-8646-47f5-9113-bb1b1ca5bdae**

Tested right before the package was made:
1. Repairing the files.
2. Moving the files to a temporary location.
3. Waiting until Origin has recognized that the files are missing, and is showing "Install" instead of "Play"
4. Restarting PC.
5. Moving the files back to it original location (E:\Games\Origin\The Sims 4)
6. Clicking "Install" in Playnite to start the install (or at least force the file-check/repair procedure that normally starts when files already exist) starts the game directly, regardless if Origin is running or not.

I don´t know if Origin does that with all their games, but it looks like Playnite is going around the start-procedure in Origin and uses the executable "ts4.exe".
But if I start a game from any of the other clients (Steam, Uplay, Epic, BattleNET) it always starts the game through the client [or starts the client first and then the game, if the client wasn´t running]


I hope this info helps :)

**Comment by JosefNemec** [comment] 2020-02-08 16:56
Can you try to completely uninstall the game (I know it sucks) and reinstall it in Origin (not doing repair, but clean install)? Because I'm unable to reproduce this on any of my systems and attached diag. info doesn't show any errors.

There was an issue int past where it was not possible to launch Deluxe Edition (it was still properly detected as installed though), but that was fixed in 6.4 (issue #1571).

**Comment by Foshitz** [comment] 2020-02-09 06:26
Just tried a clean install, restarted computer and then started a new installation in Origin. No luck.
I don't have the Deluxe Edition, but recently added Get To Work.

Dug a little deeper in Playnite by adding the game manually through _Add Game -> Scan Automatically -> Detect Installed._
It get´s added under Playnite in the library (instead of Origin), but at least Playnites sees it as Installed and pointing to _"E:\Games\Origin\The Sims 4\Game\Bin_LE"_

> Where does your Playnite point to, when it automatically sees the game as Installed?

**Comment by JosefNemec** [comment] 2020-02-11 17:57
Can you please reproduce it again with [this build](https://playnite.link/download/6_5_debug.zip) and generate new diag. package? Also please attach `\The Sims 4\__Installer\installerdata.xml` file.

BTW are you using Legacy edition (32-bit version) or standard one?

**Comment by JosefNemec** [comment] 2020-03-08 10:55
I'm closing this. I can't diagnose it any further without information I asked for in my previous comment.

**Closed by JosefNemec** 2020-03-08 10:55 UTC
Labels: bug

**Comment by Foshitz** [comment] 2020-03-08 11:49
Sorry, I´ve had a lot of other stuff going on the last few weeks.
Would´ve been nice if you sent a reminder or two.

But to get back to business:
I tried this on my laptop, with Origin installing the game to the default location [_C:\Program Files (x86)\Origin Games_]
No issues there!

I´ll also try what you asked for last time, with the alternative build on my desktop (where the issue happens)

**Comment by Foshitz** [comment] 2020-03-08 12:28
It worked in that build (6_5_debug) :)
Diag.package 2fed00fd-0086-477b-b30d-7a2c2ffa0ec9

Also see attached zip-file with my installerdata.xml
[foshitz_ts4_installerdata.zip](https://github.com/JosefNemec/Playnite/files/4303185/foshitz_ts4_installerdata.zip)

**Comment by JosefNemec** [comment] 2020-03-08 13:23
Since it worked with that debug build, can you try it with latest 7.2 to see if it's fixed?

**Comment by JosefNemec** [comment] 2020-03-08 13:25
Also since you said that the correct folder is `Bin_LE`, does it mean that you were using legacy edition instead of standard one? Does it happen with legacy version only?

**Comment by Foshitz** [comment] 2020-03-08 14:05
When I add the game through `Add Game -> Scan automatically -> Detect Installed`, then that is the only executable for The Sims 4 that Playnite discovers.
Origin creates both of the folders during the initial installation, which means that `Bin` (containing ts4_x64.exe) is installed alongside `Bin_LE` from the start.

But that part feels irrelevant, since the issue where Playnite does not discover it as installed happens before even trying to start the game.
Like I said earlier, this is the only Origin-game that has this issue.

When checking the Installation Directory (Installation-tab under Game Details) on my laptop, Playnite points to `C:\Program Files (x86)\Origin Games\The Sims 4\` which suggests that it should look for any  executable in any of the sub-folders.


**Tried in stable version 7.2, issue persists..**

**Comment by Foshitz** [comment] 2020-03-08 14:12
> Since it worked with that debug build, can you try it with latest 7.2 to see if it's fixed?

Tried in stable version 7.2, issue persists.
For the 6.5-debug build, it only takes a few seconds for it to discover The Sims 4 automatically.

**Comment by JosefNemec** [comment] 2020-03-08 14:33
Can you try it with [this version](https://playnite.link/download/OriginDebug.zip) of Origin extension and Playnite 7.2? You need to replace files inside `Extensions\OriginLibrary\` subfolder inside Playnite's install folder. After you reproduce it, please generate new diagnostics package for me. Thanks

**Comment by Foshitz** [comment] 2020-03-08 16:55
Sorry, no obvious change on my side.
Diag.package `e5a0fa7b-95d6-45bf-b6fa-61d93b515718`

**Comment by JosefNemec** [comment] 2020-03-08 19:32
It fails because Playnite detects game to be installed in `E:\Games\Origin\The Sims 4\`, but fails to find its executable `E:\Games\Origin\The Sims 4\Game\Bin\TS4.exe`. Is that file present there?

**Comment by JosefNemec** [comment] 2020-03-08 19:43
Also can you try deleting `%appdata%\Playnite\ExtensionsData\85dd7072-2f20-4e76-a007-41035e390724\origincache\` folder to see if it fixes the issue?

**Comment by Foshitz** [comment] 2020-03-09 15:36
> It fails because Playnite detects game to be installed in `E:\Games\Origin\The Sims 4\`, but fails to find its executable `E:\Games\Origin\The Sims 4\Game\Bin\TS4.exe`. Is that file present there?

Well, that sure does sound like an sissue with the cache, since i´m not using that folder for the installation anymore..
In my folder `E:\Games\Origin\The Sims 4\Game\Bin\` the file is called "ts4_x64" and not "ts4.exe"

Before I try and clear the cache, I tried setting the installation folder back to that folder path (just to see what Playnite does) but Playnite still doesn´t discover it.


> Also can you try deleting `%appdata%\Playnite\ExtensionsData\85dd7072-2f20-4e76-a007-41035e390724\origincache\` folder to see if it fixes the issue?

I´ll try that next, and then reinstall TS4 once again.

**Comment by Foshitz** [comment] 2020-03-09 15:52
**Deleted the cache-folder, now it works :)**

**Comment by JosefNemec** [comment] 2020-03-09 16:18
Thanks, I was worried that cache was the issue, but at least we know what's causing it. Permanent fix will be in next update.
