### ISSUE TITLE
Playnite wrongly tags games as uninstalled after start, even after manual correction 

### ISSUE THREAD

**Issue by bettafo** [JosefNemec/Playnite#1288] opened 2019-07-27 22:00 UTC
After installing version 5.0, Playnite started reporting an abnormally large number of uninstalled games at launch. I manually corrected the situation game by game (most would launch correctly after I checked the 'installed' checkbox, a few had indeed been moved and therefore also required the installation directory to be updated). However, after I close and restart Playnite the same games revert to uninstalled status (installed tickbox unchecked). The games for which I corrected the installation path still retain the corrected installation path, so it is not a matter of Playnite not saving my changes but of it reverting the status to uninstalled at startup.

**To Reproduce**
The following may hopefully help to reproduce the problem:
My installation is portable. I installed version 5.0 (now upgraded to 5.2 through the 'check for a new version' menu) by following the recommended procdure: I made a copy of my old portable installation and pasted the content of the Playnite.zip in the installation directory, replacing all the older files. 
I launch Playnite with admin permissions because I noticed that it prevents some crashes from happening (like when deleting some entries in the Library Management menu).
Most of my games are GoG games. The problem occurs with games from GOG or Steam indifferently. Once the 'uninstalled' status is corrected, the games launch fine without need for any further correction until the next restart of Playnite upon which the same games get marked as uninstalled again.
It would seem that many (maybe all?) of the games that are wrongfully tagged as uninstalled are games that had been relatively recently updated / reinstalled (via Steam or full uninstallation + reinstallation for GOG games). However these updates / reinstallations had occured prior to installing v5.0.

Thank you for your great work!
Cheers

**Comment by JosefNemec** [comment] 2019-07-29 09:53
There was a change in 5.0 where we now update states for all games not just those that have been imported as installed. Which is why the settings is getting overwritten. We might need to revert that change.

However I think the more important issue is that some games are not being properly imported as installed automatically. Have you tried verifying game installation for those games (you can do that in both Steam and GOG)?

**Comment by T-0pel** [comment] 2019-07-29 11:03
Hi @bettafo, I added this functionality so I will investigate tonight, sorry for the inconvenience.

I will try to reproduce the issue using the steps that you have outlined. Could you let me know which games are causing this issue for you? It might be a game-specific issue that the game does not get recognized as installed by the plugin.

**Comment by T-0pel** [comment] 2019-07-29 11:39
Could you please also let us know whether you are using the "Import installed games" setting of the plugin or the "Import uninstalled games" as well? Thank you.

**Comment by bettafo** [comment] 2019-07-29 14:45
Good day,
Let me start with thanking you both (T-0pel and JosefNemec) and all the other contributors for your work on Playnite and follow-up on user's feedback. I previously used Razer's Cortex as my 'One launcher to rule them all [games]). I abandonned it for Playnite which is by far superior imho.

To T-0pel:As a general case I starting cataloging my games (including those that are now wrongly being tagged as uninstalled) with much earlier versions of Playnite (probably 3.x). I would let the program detect what it could by itslef on startup and then manually add the (quite many at the time) games it would have missed (using menu Add game > Scan automatically > Scan folder). 

I have only be using the "import installed games" setting of the plugin. However I am not sure that this or the other setting even existed at the time when I catalogued the games that are now wrongly being tagged.

What those games wrongly being tagged as uninstalled have in common is that the have been indeed uninstalled and then reinstalled at some point (to move them to another drive and/or to perform a large update). However this most likely was while Playnite was still pre 4.x. I have not noticed the problem of the wrongly tagged games until 5.0 but that may be because i did not look closely enough (my games laibrary is large).

I hope it helps. I stand ready to provide further information or perform test as may be of help to you.
Cheers

**Comment by bettafo** [comment] 2019-07-29 16:17
To T-0pel: **examples of games** (NB: these are games that you can use easily for testing because I have them in free version but I can provide more examples upon request)

Dr. Langeskov, The Tiger, and The Terribly Cursed Emerald: A Whirlwind Heist [Steam]
The Awesome Adventures of Captain Spirit [Steam]

**Comment by bettafo** [comment] 2019-07-29 16:39
There is something interesting happening: while listing the games in cause, I noticed that their number had went down from 74 to 63. I am positive that I have not done anything in the meantime however: no update of Playnite, ,no modifying settings or metadata... So just of curiosity I went through that list of 63 games still causing problem and manually checked the 'installed' tickbox. An,d Lo and Behold.. after restaring, the list is now only 59 games long. Oo
In particular, the two games that I listed earlier are now solved. 

Could it be something like, with many games spread on different hard drives (some of them possibly in resting state when Playnite does the scan at startup) the scan may miss games pseudo randomely?

**Comment by bettafo** [comment] 2019-07-29 17:08
I did another test and seem to be narrowing down the issue:
I tagged once again 2 of the other problematic games (Ash of Gods: Redemption [GOG] and 
Battle Brothers [GOG]) as installed and then launched and closed them before closing and relaunching Playnite (as opposed to closing and relaunching Playnite after tagging them as installed but without launching them in the meantime).
And these two games are not reverted to 'uninstalled' anymore and my list is down to 57 games?. I am going to do the same for each of them and see.

**Comment by T-0pel** [comment] 2019-07-29 17:17
Yeah, I did some experiments and it seems to be an issue with the game files integrity. As JosefNemec mentioned, you can just do an integrity verification, that should fix the issue, you do not need to run the game.
[Verify integrity - Steam link](https://support.steampowered.com/kb_article.php?ref=2037-QEUH-3335)
Verify integrity - GOG:
![verify](https://user-images.githubusercontent.com/9216020/62068000-05ace480-b22d-11e9-9436-50aeaf6cb513.png)
Let me know if that helps. I will post more details from my analysis later.

**Comment by bettafo** [comment] 2019-07-29 17:52
Well I went through the list and ran all the games after correcting their status manually and now I have no problematic game left. So I guess the issue can be considered solved and that ticket can be closed. If the problem arises again (it probably will with new updates) I will try the file integrity checking method.

Thank you.
Cheers

**Comment by JosefNemec** [comment] 2019-08-07 14:39
Closing per last comment.

**Closed by JosefNemec** 2019-08-07 14:39 UTC
Labels: bug
