### ISSUE TITLE
Disable automatic checking for updates

### ISSUE THREAD

**Issue by redactedscribe** [JosefNemec/Playnite#2685] opened 2021-12-01 02:08 UTC
**Describe the solution you'd like**
I couldn't find an option to be able to disable Playnite from automatically checking for updates. Being able to would be beneficial for those that use package managers on Windows to manage their Playnite installations/updates. This way a user could not accidentally update Playnite via the app, which would likely break the managed installation.

Being able to disable the updates would mean not having to make the mistake of misremembering that Playnite was installed via the playnite.link installer and so proceeding to update, then only to realize that it was actually installed via package manager. I don't want to have to keep track of this information in my head (installed via website or package manager), but instead just disable updates and let my package manager do the tracking. I have a lot of software installed on my system, so this becomes a chore.

Thank you.

**Comment by JosefNemec** [comment] 2021-12-01 07:12
I do not support any external update methods and you should be only using Playnite's built-in updater to update it.

**Comment by redactedscribe** [comment] 2021-12-01 13:15
You provide a zipped version of the program so I would imagine that means you'd expect users to be able to download a future zipped version as a drop-in replacement and for everything to run as expected. This is all the package manager does essentially, so I'd argue there's nothing additional you'd really need to support. It's not vital to be able to disable update checking, but I'd prefer not having a daily desktop notification reminding me of an update's availability, and the permanent update icon in the top toolbar. I usually wait until I update to the next version of anything. If Playnite has a ini configuration file or something, perhaps an option to disable checking for updates could be added there, rather than directly in the UI? If you still see no reason for this option, then I don't think I'll have any further points to make and so will have to agree with your decision.

**Comment by JosefNemec** [comment] 2021-12-01 13:58
Just overwriting files with portable package won't break anything, but even portable packages can and should use built-in updater as preferred update method.

As far as installing/updating via package managers, there's still plenty of things they can break (permissions for example). I just don't support them and I don't want to deal with potential issues caused by them.

As far as option to disable update check, I'll consider it.

**Comment by penguinairlines** [comment] 2021-12-17 23:24
> I do not support any external update methods and you should be only using Playnite's built-in updater to update it.

I can appreciate that you do not want to spend your own time supporting, or at least building, a repository packager, but someone already has, and over 21,000 other downloads suggest that it's working pretty well. https://community.chocolatey.org/packages/playnite

I'm looking for the same feature as the OP, the ability to not receive Windows notifications from the built-in updater, since literally every platform except Windows (MacOS, Android, Linux, FreeBSD, etc.) support package managers natively since they are objectively a superior experience for managing packages and application installations. The Chocolatey package manager has been an excellent method to manage my Playnite installation, along with dozens of other apps, for years now. I've had no issues with updating Playnite via this method, and I intend to keep doing so. Having a dedicated updater is appreciated in the event that I run into any trouble, which has not yet occurred for my installation. 

+1 please add an enhancement to support enable/disable update notifications.

**Comment by RoinujNosde** [comment] 2022-04-13 01:07
Suggested settings:
- Enable/disable Playnite update checks
- Enable/disable add-ons update checks
- Set an interval for checking (on startup, everyday, every week, etc)

**Comment by redactedscribe** [comment] 2022-09-22 17:41
Playnite version 10 introduced "Options to control update check behavior", however the only options are "On every startup", "Once a day", and "Once a week". Adding a "Never" option would have addressed this issue.

**Comment by seriouslyunderappreciated** [comment] 2022-10-26 21:04
Please consider letting us disable auto updates entirely.

**Comment by JosefNemec** [comment] 2022-12-08 10:56
I'm going to close this. The main reason I don't want to add an option for completely disabling updates is because we had quite a lot of cases in the past with people reporting problems that have been already fixed, they just didn't bother updating or checking if there's an update available.

I will probably add an option to skip specific versions via #3200 in future, but adding an option to completely disable update checks is not going to happen.

**Closed by JosefNemec** 2022-12-08 10:56 UTC
Labels: enhancement

**Comment by epstein-suicider** [comment] 2023-10-26 11:13
I don't want your program pinging back home when you want it to.

**Comment by epstein-suicider** [comment] 2023-10-26 11:19
Why do you think your program should be able to ping home from everyone's computer without being disabled? Why do you think spyware without the ability to opt out is fine to add to your programs? I'll gladly enjoy turning it off using dnSpy, but I think we both would be happier if you simply added a checkbox. Add however many message boxes warning people your heart may desire, I don't care. You not wanting to provide simple functionality to prevent routine pings back home proves you don't care about end users' freedoms.
![image](https://github.com/JosefNemec/Playnite/assets/67754122/f77dd4f3-e554-4caa-b67e-67a3f2e7ba89)

**Comment by redactedscribe** [comment] 2023-10-26 11:27
It's true that disabling them completely would be useful to some users in some cases. If users really want to disable updating, they have to use a firewall to manage that and the regular need for Playnite to access the internet. IIRC, the concern was having outdated versions of Playnite installed in the wild, but in response to that I'd say build the kind of app people want to use and people will generally want to keep on updating.

**Comment by epstein-suicider** [comment] 2023-10-26 11:34
May I add, the function SendUsageDataAsync seems to be sending telemetry data back to Playnite servers on startup, with an "Install Instance ID" appended. I did not find a way to disable just this part either, offline mode does the trick, but I don't think I saw an individual switch to turn this off. The end user never seems to be alerted of this, and would be unaware that the program phones back home with telemetry data on every launch.
https://github.com/JosefNemec/Playnite/blob/4c03306ff4bf62ed2a244b20543f2839eb5483cf/source/Playnite/App/PlayniteApplication.cs#L1374

**Comment by JosefNemec** [comment] 2023-10-26 12:09
The "telemetry" only sends Playnite and Windows version, not other data. It will be fully removed in Playnite 11 since it won't be needed anymore. Its purpose was to see how big impact will have removal of Windows 7 and 8 support as well as 32bit support removal.

**Comment by epstein-suicider** [comment] 2023-10-26 12:21
It's fine, I've already ripped your program of its spyware; as for respecting every other's freedoms, such as the people who don't know how to patch it out, or most likely don't even know their computer is even phoning home, that's for you to decide

**Comment by JosefNemec** [comment] 2023-10-26 12:32
You should probably look up definition of "spyware". Playnite has no spyware in it.
