### ISSUE TITLE
Error when trying to launch a Windows Platform game

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#670] opened 2018-06-13 16:22 UTC
I get the following upon trying to launch Gears of War 4:

> System.IO.DirectoryNotFoundException: Cannot watch directory processes, C:\Program Files\WindowsApps\Microsoft.SpartaUWP_12.4.1.2_x64__8wekyb3d8bbwe not found.
   en Playnite.ProcessMonitor.<WatchDirectory>d__14.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   en System.Windows.Threading.DispatcherOperation.InvokeImpl()
   en System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   en MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   en MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   en System.Windows.Threading.DispatcherOperation.Invoke()
   en System.Windows.Threading.Dispatcher.ProcessQueue()
   en System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   en MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   en MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   en System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   en MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   en MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   en System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   en System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   en System.Windows.Application.RunDispatcher(Object ignore)
   en System.Windows.Application.RunInternal(Window window)
   en System.Windows.Application.Run(Window window)
   en PlayniteUI.App.Main()

Here's the .diag package: 
[PLAYNITE PACKAGE.zip](https://github.com/JosefNemec/Playnite/files/2099019/PLAYNITE.PACKAGE.zip)

The game launches fine but I get the error.
This started happening since I updated to  Playnite 4.30

**Comment by JosefNemec** [comment] 2018-06-13 16:36
That's weird, I don't remember making any changes to how Window Store games are handled, can you try to downgrade to 4.21 and confirm this was caused by 4.30 update? Also can you check if `C:\Program Files\WindowsApps\Microsoft.SpartaUWP_12.4.1.2_x64__8wekyb3d8bbwe` exists?

**Comment by JosefNemec** [comment] 2018-06-13 16:37
Also can you try re-importing the game to see if it fixes the issue?

**Comment by darklinkpower** [comment] 2018-06-13 16:57
Nice catch, I didn't remember that in fact, `C:\Program Files\WindowsApps\Microsoft.SpartaUWP_12.4.1.2_x64__8wekyb3d8bbwe` doesn't exist. The game is installed in another directory, it should be `E:\WindowsApps\Microsoft.SpartaUWP_12.4.1.2_x64__8wekyb3d8bbwe` for me.

I just reimported and that fixed the issue, I don't know why I didn't to that in the first place, my bad and thanks again for your help.

**Comment by JosefNemec** [comment] 2018-06-13 17:14
Did you reinstalled the game into different directory after importing it into Playnite? I'm wondering why would Playnite import wrong installation directory in the first place.

**Comment by darklinkpower** [comment] 2018-06-13 17:58
No I never did, I installed the game there since the beginning, but I think that by default it installs in program files and the C drive, but I installed it in another drive and directory, maybe that's what cause this?

**Comment by JosefNemec** [comment] 2018-09-27 09:56
Fixed in 4.5

**Closed by JosefNemec** 2018-09-27 09:56 UTC
Labels: bug
