### ISSUE TITLE
Highly customizable filters backed by search engine

### ISSUE THREAD

**Issue by code-sculptor** [JosefNemec/Playnite#135] opened 2017-10-08 04:19 UTC
Hi! Good work out there. I have an idea for quite important feature.

List of my games is now a mixture of all tags, including finished and dropped games. I don't want to see some of them (and for that I need more complex filter - to exclude 2 categories at once).

What would you say about using search engine like https://lucenenet.apache.org ? I suppose currently application is backed by traditional RDBMS. Even for general search, if it's not UI update taking so long, such search engine would improve its speed. I'm not sure if it's the best choice since I'm a Java developer and I can tell that Lucene is great on Java, however I never tried its port on .net. Well, maybe you know about better C# alternative.

Anyways, going back to filters, I think it would be marvellous to have possibility to:
1. Pick filter type from drop-down into set of filters (combined together with AND clause - I don't think anything more complex would be needed)
2. Per every picked filter in the set, have possibility to inverse/negate that filter,
3. Be able to store such set of filters under a name into a map of quick filters.

So, for example I would have a map:
"Automotive" => Filters(category("Automotive")),
"May play" => Filters(not(category("Abandoned")), not(category("Finished")))
"May play (different example approach)" => Filters(category("Plan to play"), category("May play again"))

**Comment by JosefNemec** [comment] 2017-10-08 08:18
Great idea! I'm definitively going to look more into this.

**Comment by oscarbidabehere** [comment] 2019-04-22 22:53
First of all thanks for your hard work, really nice program.
I'm tying to organize the library in categories but I think there are two features that are a "must have" in order to be able to keep the library organized over time.
- Filter by "games with no category"
- Filter by  "games not in X category"
For example I want to separate VR and non-VR games. This can be done with patience adding two categories to the corresponding game. The problem is that if in the future some games are added to the library I cannot tell which games don't have the corresponding category setup except by checking the whole library. Instead having the suggested filters the task would be trivial, like this:

1. You can set the category "VR" to the corresponding games
2. Then filter by category not in "VR" and add the category "Non-VR" to all of those.
3. When new games are added I would filter by "games with no category" and set the corresponding category.

I think these simpler features would add a lot to the usability. Also I noticed there are a lot of sorting options not available for filtering like CompletionStatus, PlayCount, etc.

**Comment by JosefNemec** [comment] 2019-11-05 11:47
I'm closing this since this should be in some part added via #1413

**Closed by JosefNemec** 2019-11-05 11:47 UTC
Labels: complex_high, enhancement
