### ISSUE TITLE
Unable to Rename ROM

### ISSUE THREAD

**Issue by azuravian** [JosefNemec/Playnite#3013] opened 2022-08-09 03:28 UTC
### Bug Description

I have games that have 1 or more entries for ROMS with the name "NewRom" under the installation tab.
I am unable to rename these ROMs.  The only way to rename them is to remove them and readd them.
Even when readding, I must name the ROM prior to selecting the file.  Otherwise the name is overwritten with "NewRom".

When testing, I found this happens no matter what the current ROM name is.  If I try to change the name, I am unable to.

### To Reproduce

1. Open a game that has an existing ROM entry under installation tab.
2. Make a change to the ROM name (not path).
3. Save
4. Reopen the game settings and the name will be reverted.

### Diagnostics ID

5faaf445-647d-4e58-88d7-d285c8c2be26

**Comment by JosefNemec** [comment] 2022-08-09 07:52
I can't reproduce it and there are no errors in your logs related to updating game information. Please retest this again while running in safe mode (you can restart to it from Help menu), if it works properly in safe mode, then it means the issue is caused by some 3rd party extension.

**Comment by azuravian** [comment] 2022-08-09 18:37
Well, after much banging my head around and trying multiple different sets of extensions, I found the issue.  This only occurs if you don't click the Save button, but hit Enter on the keyboard.  It seems that hitting Enter on my keyboard saves all changes except for the ROM title.

**Comment by JosefNemec** [comment] 2022-08-31 15:25
Fixed in devel.

**Closed by JosefNemec** 2022-08-31 15:25 UTC
Labels: bug
