### ISSUE TITLE
Overlay to handle operations via controller

### ISSUE THREAD

**Issue by Rallo00** [JosefNemec/Playnite#3890] opened 2024-12-16 19:22 UTC
### Feature description

Playnite is a great application that kinda transforms a computer in a console using the fullscreen mode, however it's missing an important feature that all consoles have nowadays: the overlay menu.

Usually most games for computers have an exit option in the main menu that allow to exit the game and return to playnite, that does not happen when using emulators or other applications. Having an overlay that can be opened or closed through a configurable button (XBOX button for example in Xbox controllers) can be a game changer. It can also be useful to restart, shutdown, closed frozen application or emulators. It is an important feature playnite should have.

An interesting application that does it perfectly is reWASD but unfortunately has a monthly subscription and it annoys me to install a different software for one simple feature.

Thanks in advance.

**Comment by Jeshibu** [comment] 2024-12-16 19:28
Duplicate of #1390 I think

**Comment by JosefNemec** [comment] 2024-12-16 19:45
closing as duplicate

**Closed by JosefNemec** 2024-12-16 19:45 UTC
Labels: enhancement
