### ISSUE TITLE
AoE2: African Kingdoms DLC imported as a game

### ISSUE THREAD

**Issue by xforeigner** [JosefNemec/Playnite#140] opened 2017-10-08 10:44 UTC
Please don't make scan **## Age of Empires 2 HD: The African Kingdoms**, since it isn't a standalone expansion and morelike a DLC.

**Comment by JosefNemec** [comment] 2017-10-08 12:30
Are you saying that African Kingdoms appears in Playnite as separate game?

**Comment by xforeigner** [comment] 2017-10-08 12:43
Yes indeed

**Comment by JosefNemec** [comment] 2017-10-09 16:33
Please go to "About Playnite..." menu and create diagnostics package for me. Thanks in advance.

**Comment by JosefNemec** [comment] 2017-10-18 18:33
I'm going to close this for now since there's no additional information from reporter and I'm unable to reproduce it. Feel free to reopen when you provide requested information.

**Comment by deextercz** [comment] 2017-11-29 16:12
[diag.zip](https://github.com/JosefNemec/Playnite/files/1514473/diag.zip)
![untitled](https://user-images.githubusercontent.com/23039506/33385237-67a32534-d528-11e7-98bc-1f9ec008a73a.png)
Diag file attached

**Comment by JosefNemec** [comment] 2017-12-29 20:57
I'm afraid there's nothing I can do about this, for some reason Steam API simply reports African Kingdoms as separate game. I recommend just hiding the game in library.

**Closed by JosefNemec** 2017-12-29 20:57 UTC
Labels: bug

**Comment by deextercz** [comment] 2017-12-30 08:04
According to this link
http://store.steampowered.com/app/355950/Age_of_Empires_II_HD_The_African_Kingdoms/
it should be dlc so I think it is bug on steam.
Could you discuss with them?
pá 29. 12. 2017 v 21:57 odesílatel Josef Nemec <notifications@github.com>
napsal:
