### ISSUE TITLE
Not detecting installed epic games?

### ISSUE THREAD

**Issue by XCEntUrIonPro** [JosefNemec/Playnite#1132] opened 2019-05-05 23:47 UTC
Hello, I've had this issue since installing the launcher and I've tried looking everywhere to see if there's a fix, but i couldn't find one, so maybe I'm a one off? Who knows. Anyway, the launcher isn't detecting my installed epic games and I need a fix. 
![error](https://user-images.githubusercontent.com/12616980/57202019-61523380-6f98-11e9-8906-a91be7a89e71.PNG)

**Comment by JosefNemec** [comment] 2019-05-06 06:34
Could you try reinstalling the game? I had reports saying that it usually fixes this.

**Comment by XCEntUrIonPro** [comment] 2019-05-06 14:27
Reinstalling the game didn't seem to fix the issue. Any other suggestions? or should I just wait for a future update.

**Comment by JosefNemec** [comment] 2019-05-06 14:29
Can you try reinstalling Epic client as well?

**Comment by XCEntUrIonPro** [comment] 2019-05-06 16:54
I tried reinstalling the epic client and it didn't fix the issue. I also tried reinstalling playnite but that didn't seem to fix it either.

**Comment by unrealed** [comment] 2019-06-11 12:48
Same, tho I haven't tried reinstallirng Playnite or Epic (but did try reinstalling a game and that didn't work). I'm wondering if it has anything to do with where it's installed, because my Epic Launcher is installed on my E: drive

**Comment by herrchin** [comment] 2019-07-14 19:19
I have the same issue, with the following detail:
On every Playnite startup I get a new notification of "Failed to import games from Epic. Epic Launcher is not installed." I also used a nonstandard installation location of "Z:\Epic Games Launcher"

**Comment by JosefNemec** [comment] 2019-07-16 17:18
Sadly I can't reproduce it. Can you go to `About` menu and create diagnostics package for me?

**Comment by herrchin** [comment] 2019-07-18 01:16
Absolutely. ID is 51ee9ac9-ef5a-493d-a24c-9ca083f4d05b . Let me know if there are other tests you'd like me to do!

**Comment by JosefNemec** [comment] 2019-07-28 17:50
Fixed in 5.1

**Closed by JosefNemec** 2019-07-28 17:50 UTC
Labels: bug

**Comment by JosefNemec** [comment] 2019-10-31 12:43
Thanks for the diag. data. I don't see any errors in logs related to Epic import.

Can you please check that this files exists on your PC?
`c:\Users\All Users\Epic\UnrealEngineLauncher\LauncherInstalled.dat`

And also that there are some `.item` files in this directory?
`c:\Users\All Users\Epic\EpicGamesLauncher\Data\Manifests\`
