### ISSUE TITLE
Playnite crashed when starting game in Uplay

### ISSUE THREAD

**Issue by Foshitz** [JosefNemec/Playnite#998] opened 2019-02-11 10:38 UTC
Hi,

Playnite had an unrecoverable error and crashed when trying to start Ghost Recon Wildlands from within the Uplay-client.
And the game did not start at all, until trying to start it a second time without restarting Playnite again.

Diagnostic Package = 27a58a59-7b15-4512-ad52-baa4a86c252c
![11feb2019-unrecoverable-error-crash](https://user-images.githubusercontent.com/16353951/52558011-68cacc00-2df1-11e9-947d-d7b39caa3ae5.JPG)

**Comment by JosefNemec** [comment] 2019-02-13 16:11
Are you able to reproduce this on demand? The logs doesn't make much sense to me since they say that game's installation directory doesn't exists (which is probably not true because game wouldn't be imported in that case). And also you mention that the crash occurred with "Ghost Recon Wildlands", but I can only see it happening with Division 2 in logs.

**Comment by Foshitz** [comment] 2019-02-28 05:30
No, the error only occurred during that first try. Like I said, the game started up normally on the second try and I haven't had that issue with any of my other games since then either. 
If it was related to the Division 2 Private Beta, I will keep an eye out during this weekend when it's time for their Open Beta.

**Comment by JosefNemec** [comment] 2019-06-07 08:32
I'm closing this until we find a way how to reliably reproduce this.

**Closed by JosefNemec** 2019-06-07 08:32 UTC
Labels: bug
