### ISSUE TITLE
Metadata images (Google search) not downloading when TLS 1.3 is enabled

### ISSUE THREAD

**Issue by DaBear78** [JosefNemec/Playnite#1978] opened 2020-08-31 17:54 UTC
Hi,

when I enable TLS 1.3 in Windows 10 and try to load any images through the integrated Google search on the "Media" tab of the metadata window the found images only show as grey boxes and they can't be downloaded. When using TLS 1.2 everything works as expected.

Greets,
DaBear78

**Comment by jaakkopirinen** [comment] 2020-10-26 01:58
Truly needs a fix. Thought my whole app is broken until realized this. Already uninstalled Playnite and reinstalled it. Fixed it by disabling TLS 1.3
It broke IGDB, VNDB & other metadata sources.

**Comment by JosefNemec** [comment] 2020-10-26 10:33
I can't reproduce this. What Windows 10 version do you have?

Also, after doing some investigation, this will probably not work properly until we switch to newer .NET runtime, but I might be able to do some workaround in the meantime if I manage to reproduce it on my end.

**Comment by JosefNemec** [comment] 2020-10-26 10:35
Also, please attach diagnostics id that was requested in the issue template.

**Comment by TheJAXi** [comment] 2020-10-26 11:59
> Also, please attach diagnostics id that was requested in the issue template.

Sorry I didn't do such thing. I'll look into it if the problem reoccurs. Atm on the newest Win 10 version 2004? Can't remember the build number. Not at home. I simply fixed it by turning the whole TLS 1.3 off. Also love your software & the community behind it (made myself a damn beautiful simple theme but a bit scared to publish it yet as I'm trying to figure out how to import plugins to it). Icon metadata could be nice (other than official store & steam). Also had a tiny problem with metadata loading wrong (I have my order set up as VNDB, IGDB, Official Store, Steam Store) and Playnite kept loading Official Store / IGDB instead of taking Visual Novel ones. I fixed that by going one by one through all my visual novels and downloading the metadata manually. Sorry for writing such a wall without any context. I'll try fixing these issues myself & report to you while creating/finishing the theme.

**Comment by JosefNemec** [comment] 2020-10-26 12:01
> I'll look into it if the problem reoccurs

Are you saying that it doesn't always happen and it's not reproducible on demand?

**Comment by JosefNemec** [comment] 2020-10-26 14:51
I am able to reproduce it with 20H2 Windows 10 build, I'll see if I can do something about it.

**Comment by JosefNemec** [comment] 2020-10-27 12:11
Fixed in 8.4

**Closed by JosefNemec** 2020-10-27 12:11 UTC
Labels: bug
