### ISSUE TITLE
Series options appearing in triplicate

### ISSUE THREAD

**Issue by R160K** [JosefNemec/Playnite#1371] opened 2019-08-14 21:31 UTC
I edited the "Series" datum on a few games to group them together. However, when I go to use "Series" as a filter, each series appears three times instead of once. All games in a particular series appear regardless of which option is ticked, so it can't just be a case of the games being divided between multiple series with the same name. Additionally, each series appears only once in the "Edit..." (F3) dialog.

![Issue](https://user-images.githubusercontent.com/5496317/63057802-fee7c800-bee2-11e9-9cfe-b677038baa3d.png)
![Issue2](https://user-images.githubusercontent.com/5496317/63057820-07d89980-bee3-11e9-92c9-3dab7e47e3ea.png)

**Comment by JosefNemec** [comment] 2019-08-16 08:20
Sadly, I can't reproduce it. Can you please provide step by step instructions that will replicate this behavior? Thank you

**Comment by R160K** [comment] 2019-08-25 21:59
Have just opened Playnite again and the problem seems to have gone away for the existing series. However, just tried creating a new series by selecting multiple games, right-clicking and choosing "Edit...", clicking the "+" next to "Series" and typing in a name. After that, when trying to filter games by series, the new one appears multiple times, although only twice this time (see below). Perhaps when you already have multiple series defined, the problem goes away and only affects the first few series you define. After exiting Playnite and starting it up again, all series (including the new one) show up only once each.
![Issue](https://user-images.githubusercontent.com/5496317/63656464-efdb0280-c78b-11e9-841b-68c40cc466bd.png)

**Comment by JosefNemec** [comment] 2019-09-11 12:55
I'm stupid, I was testing it with work-in-progress 5.7 update, where it doesn't happen anymore (I'm not sure why).

**Comment by JosefNemec** [comment] 2019-09-18 10:10
Fixed in 5.7

**Closed by JosefNemec** 2019-09-18 10:10 UTC
Labels: bug
