### ISSUE TITLE
Duplicate entries after adding PlayStation library

### ISSUE THREAD

**Issue by Rinma** [JosefNemec/Playnite#2065] opened 2020-10-18 09:56 UTC
**Describe the bug**
I authenticated my PlayStation account and pressed "Update Game Library -> PlayStation". After updating and importing metadata I have multiple entries of the same games (same Library, same Platform, ...)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/1405824/96364089-eacbd600-1138-11eb-8ff0-7af3d73910b5.png)

**Diagnostics ID**
239be42e-ee89-40b6-b56c-5b79bb53a129

**Comment by JosefNemec** [comment] 2020-10-18 10:08
It's because you have grouping by genres enabled and those games have multiple genres assigned to them. The problem is that we don't show groups on Grid view (#170), so those games look duplicated. If you switch to other views, you would see why it's that way.

**Closed by JosefNemec** 2020-10-18 10:08 UTC
Labels: bug
