### ISSUE TITLE
Options > Detail View > Features: don't work

### ISSUE THREAD

**Issue by IFD3** [JosefNemec/Playnite#1924] opened 2020-07-15 16:54 UTC
If you click in the options > Detail View and check "Features" those show not up in the Detail View

**Comment by JosefNemec** [comment] 2020-07-15 17:21
Can't reproduce.

Are you using custom theme? Do you have actually some features assigned to a game?

**Comment by IFD3** [comment] 2020-07-16 09:43
Oh man, I feel kinda stupid now.
Yeah I made a new Theme out of the basic and basically changed just the colors, comparing the Files showed me one single line was missing:

`<Label` Name="PART_ElemFeatures" Content="{DynamicResource LOCFeaturesLabel}" />

Now everything works as intended. Next time I'll merge after an update.

![Bild 024](https://user-images.githubusercontent.com/7597578/87655674-d7cff100-c758-11ea-8419-ee37f3afda79.png)

**Closed** 2020-07-16 09:53 UTC
Labels: bug
