### ISSUE TITLE
Option to add picture above covers for games (according to platform)

### ISSUE THREAD

**Issue by SeeDborg** [JosefNemec/Playnite#1815] opened 2020-05-15 21:12 UTC
It would be cool to be able to add automatically (and optionnally), a png picture above the cover for games who runs on an emulator (and why not all games according to the platform they run on)

For example, this :
https://imgur.com/hT3oibT

Would transform automatically into this :
https://imgur.com/gI4zWJA

Because it's a Gamecube game and I told Playnite to add this picture above all my Gamecube games : 
https://imgur.com/W20B1vE

I think the option should be located in the Library Manager.

**Comment by darklinkpower** [comment] 2020-05-15 21:14
Duplicate of https://github.com/JosefNemec/Playnite/issues/1450

**Comment by SeeDborg** [comment] 2020-05-15 22:16
Right, sorry !

**Comment by darklinkpower** [comment] 2020-05-16 01:00
If you have some ideas not on that issue you can always comment there. Remember to always check if an issue is already open by using the search function, although sometimes one or two can slip due to having different naming than your idea.

**Closed** 2020-05-16 06:44 UTC
Labels: enhancement
