### ISSUE TITLE
Very old problem: selected game not always updated on click

### ISSUE THREAD

**Issue by falcorr** [JosefNemec/Playnite#2982] opened 2022-07-10 22:22 UTC
### Bug Description

May've been around since the beginning or very early and never fixed. It's been present in many, many versions. I've previously reported it here or in the sub-Reddit, I forget. 

List View, at least. When either an entry is either selected and you then select another > right-click context menu > Edit, **and / or**, you have an entry selected and right click on another entry without left-click selecting it first > right-click... etc. I think it's at least the latter. It's led to me routinely clicking on an entry, away to another, and back before editing anything and accidentally changing the details of the wrong entry. Basically, the entry selection can't be trusted.

Windows 10 64bit across all this time and fresh reinstalls of. Issue limited to Playnite.

### Diagnostics ID

idratherpassonthis

**Comment by JosefNemec** [comment] 2022-07-23 09:29
Can you please attach video reproducing the issue? I can't reproduce it myself, every time I right-click on List view it selects the game first and context menu actions are applied to that selected game.

Also please attach diagnostics ID, it contains information that helps a lot when debugging these issues.

**Comment by Ishmaeel** [comment] 2022-08-14 06:53
I was able to reproduce this in the List View (Details and Grid are unaffected). It only happens when you right click on another game when the context menu is already open. Repro:

- Switch to "List View".
- Right click on GAME-A, context menu appears.
- Right click on GAME-B immediately. context menu appears again and selection seems to have shifted to GAME-B
- Select the "Edit" command from the contezt menu.
- See that the edit window displays details for GAME-A, not GAME-B.

**Comment by JosefNemec** [comment] 2022-09-01 15:55
I tried to replicate it using steps you provided and it seems to be working fine for me. I'm not sure where the issue might be on you side.

**Comment by Ishmaeel** [comment] 2022-09-01 19:23
Well, I don't know what to tell you, so, let me show you:

https://user-images.githubusercontent.com/5497977/187995728-fff5ba3f-5c5e-45f4-998d-5903e97a88b2.mp4

**Comment by JosefNemec** [comment] 2022-09-01 19:31
Can you try it in safe mode? You can restart in safe mode from main menu -> help. If it doesn't occur in safe mode, then it means it's caused by some installed extension.

From the video it looks the menu is somehow opened twice after you right-click on Maniac Mansion. At least that's what it looks like to me based on some flickering that clearly occurs after you right-click. 

It doesn't happen to me on multiple installations and PCs, so it must be something really specific to your PC or Playnite install.

**Comment by JosefNemec** [comment] 2022-09-01 19:31
Also please attach diagnostics ID I asked for.

**Comment by Ishmaeel** [comment] 2022-09-01 19:38
Exactly the same behavior under safe mode, and I don't have any extensions (except some library integrations) installed.

`466537ce-a09d-4dad-9cb8-a71d1c0cfca2`

**Comment by JosefNemec** [comment] 2022-09-02 18:11
Fixed in devel

**Closed by JosefNemec** 2022-09-02 18:11 UTC
Labels: bug
