### ISSUE TITLE
Game assigned to multiple categories creates duplicates

### ISSUE THREAD

**Issue by roob0** [JosefNemec/Playnite#2204] opened 2021-01-04 20:51 UTC
![1](https://user-images.githubusercontent.com/67685950/103577937-faf08780-4ed5-11eb-993a-ff9bcf50e7af.JPG)
![2](https://user-images.githubusercontent.com/67685950/103578017-23788180-4ed6-11eb-9c27-eebd5b6be099.JPG)

As many copies as categories are displayed, although I select a specific category / platform. This appens with all games (roms too)

**Comment by darklinkpower** [comment] 2021-01-04 20:53
It's not a bug, the game is being shown multiple times because the game has multiple values of the field you are grouping. You need to select only one value in the grouping field (Category in your case) for that game if you don't want to see it multiple times. 

You can see the reason in your first screenshot.

**Comment by JosefNemec** [comment] 2021-01-04 20:56
Closing based on darklink's comment.

**Comment by JosefNemec** [comment] 2021-01-04 20:56
Groups not being visible on Grid view will be fixed via #170

**Closed by JosefNemec** 2021-01-04 20:56 UTC
Labels: bug
