### ISSUE TITLE
Search window automatically closes erronously on certain actions after 10.5 update

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#3156] opened 2022-11-09 23:26 UTC
### Bug Description

Search window closes erronously on certain actions after 10.5 update. It acts as if it was automatically closed after losing focus.

If I had to guess, I think this issue was probably introduced by this fix in the 10.4 update

![image](https://user-images.githubusercontent.com/1389286/200965220-65da6bdd-2863-491f-8c0e-ab936bbdcd6c.png)

### To Reproduce

So far I've found the following ways to reproduce it:

A) Click on any button or search item

![image](https://user-images.githubusercontent.com/1389286/200962139-f4b13f82-7677-4dd0-8594-79fbfd9870ea.png)

B) It closes after performing a search with a plugin, no matter if it returns items or not. Can be reproduced with this extension https://playnite.link/addons.html#SteamSearch_78c7912a-32bb-4a42-8485-d348d10023ac

![image](https://user-images.githubusercontent.com/1389286/200963422-caf41493-370c-4f82-b728-406cd1b70560.png)

### Diagnostics ID

🤖

**Comment by JosefNemec** [comment] 2022-11-10 11:49
I can't reproduce this reliably for some reason, but I'll revert that original fix anyways since it looks like it's the root cause for this.

**Comment by JosefNemec** [comment] 2022-11-10 12:06
Fixed in 10.6

**Closed by JosefNemec** 2022-11-10 12:06 UTC
Labels: bug
