### ISSUE TITLE
Playnite doubles my playtime

### ISSUE THREAD

**Issue by lufadriad** [JosefNemec/Playnite#1991] opened 2020-09-07 16:38 UTC
Description:
My play time is not working as intended. it **doubles** my time on every game i play. it doesn't matter if its a steam game, battle net game even on the emulated ones 

To reproduce:
I just play something and the problem is happening in every game i play.

Extra:
i dunno if it's relevant but i better include these ones.

I have 2 extensions and a  custom theme:
Extensions:
-Add twitch link.
-how long to beat.

Theme:
eMixedNite

**Comment by JosefNemec** [comment] 2020-09-07 16:48
Please attach diagnostics package that was requested in issue template.

I can't reproduce this on my system. Can you try disabling 3rd party extensions to see if they are cause of the issue?

**Comment by lufadriad** [comment] 2020-09-07 17:03
well, i think i find it out that howlongtobeat was the problem this time. i disabled it and the time was working normal. thanks for the support tho.

**Comment by JosefNemec** [comment] 2020-09-07 17:06
Closing then, you should definitely report it to extension's author.

**Closed by JosefNemec** 2020-09-07 17:06 UTC
Labels: bug
