### ISSUE TITLE
Failed to download Steam library updates

### ISSUE THREAD

**Issue by OllieTerrance** [JosefNemec/Playnite#99] opened 2017-08-31 21:05 UTC
At startup, and after any changes to settings, I get this notification when the library starts to sync:

![Playnite Notifications](https://user-images.githubusercontent.com/4025899/29945101-c558889a-8e97-11e7-94e0-563454953776.png)

It doesn't appear to have failed though -- the library is updating as expected (though a fair few games are lacking their cover art).  No visible differences between imports from a local account or via username.  I have a private Steam account, but toggling to public doesn't seem to help either.

**Comment by JosefNemec** [comment] 2017-09-01 06:51
Can you please attach diagnostics package created from "About Playnite..." menu? Thanks

**Comment by OllieTerrance** [comment] 2017-09-01 18:50
📦 [playnite-steam.zip](https://github.com/JosefNemec/Playnite/files/1271222/playnite-steam.zip)

Retested on v1.3 with a clean config but it persists.  Unrelatedly, the diagnostics package fails to create on the first run, as the config.json file hasn't been written yet.

**Comment by JosefNemec** [comment] 2017-09-06 08:31
One more thing, could you please attach "loginusers.vdf" file from "config" folder inside your Steam installation?

**Comment by OllieTerrance** [comment] 2017-09-07 16:40
📄 loginusers.vdf:

```
"users"
{
        "<steam64>"
        {
                "AccountName"           "<username>"
                "PersonaName"           "<displayname>"
                "RememberPassword"              "1"
                "Timestamp"             "1504430154"
                "WantsOfflineMode"              "0"
                "SkipOfflineModeWarning"                "0"
                "mostrecent"            "1"
        }
        "<fs1-steam64>"
        {
                "AccountName"           "<fs1-username>"
                "PersonaName"           "<fs1-displayname>"
                "RememberPassword"              "0"
                "Timestamp"             "1457216729"
                "mostrecent"            "0"
        }
        "<fs2-steam64>"
        {
                "AccountName"           "<fs2-username>"
                "PersonaName"           "<fs2-displayname>"
                "RememberPassword"              "0"
                "Timestamp"             "1476557948"
                "mostrecent"            "0"
        }
}
```

Here, `fs1` and `fs2` are Steam users who have signed in to enable family sharing on this PC.

**Comment by fyrwit77** [comment] 2017-09-21 14:44
I have the same issue.

**Comment by JosefNemec** [comment] 2017-09-21 14:50
No solution yet. If you have this issue then I recommend specifying account directly by account name instead of selecting one from the list.

**Comment by fyrwit77** [comment] 2017-09-21 14:56
This sadly does not fix it. Still, the updates DO work, like OllieTerrance said. It just prints the error.

**Comment by JosefNemec** [comment] 2017-09-21 14:59
Could you please attach diagnostics package with account name set?

**Comment by fyrwit77** [comment] 2017-09-21 15:05
I just played around a bit and seem to have found the trigger of the error. It only occurs if you have steam library sharing enabled. Just disabled it and it works fine now.

**Comment by OllieTerrance** [comment] 2017-09-21 16:34
> It only occurs if you have steam library sharing enabled. Just disabled it and it works fine now.

Are you sharing your library with others, or are others sharing with you, or both?  (I have both, fwiw.)

**Comment by JosefNemec** [comment] 2017-09-26 11:02
I can't reproduce it (even when family sharing is enabled on multiple accounts), can somebody please post diag. package from version 1.4, without modifying any files that package creates? Thanks in advance

**Comment by CaptainCow95** [comment] 2017-10-08 00:11
I just downloaded version 2.2 and can reproduce it whenever I try to reload the games list, when it tries to update steam. It appears to have found all the installed games, but not the uninstalled ones even though I have it set to "Import all games". Let me know what kind of debugging information would help to figure this out.

**Comment by CaptainCow95** [comment] 2017-10-08 00:18
Found this stack trace in the logs:
2017-10-07 18:05:53.8571|ERROR:Failed to download Steam library updates.System.NullReferenceException: Object reference not set to an instance of an object.
   at Playnite.Providers.Steam.SteamLibrary.GetLibraryGames(String userName)
   at Playnite.Database.GameDatabase.UpdateOwnedGames(Provider provider)
   at PlayniteUI.MainWindow.<>c__DisplayClass33_0.<LoadGames>b__0()

**Comment by JosefNemec** [comment] 2017-10-08 07:46
Please go to main menu, "About Playnite..." and then click "Create diag. package" and upload created file. Thanks a lot.

**Comment by CaptainCow95** [comment] 2017-10-08 19:43
Here you go:
[steamNullReference.zip](https://github.com/JosefNemec/Playnite/files/1367144/steamNullReference.zip)

**Comment by JosefNemec** [comment] 2017-10-09 13:27
Are you guys sure that you have your profile visibility set to public? Playnite can't import private libraries yet and my tests show no games on profile provided by @CaptainCow95

**Comment by CaptainCow95** [comment] 2017-10-11 00:51
That would explain the error for my case. I thought that that was only required for specifying a steam name, and that using the "local user" dropdown didn't have that restriction.

**Comment by JosefNemec** [comment] 2017-10-11 06:59
Support for private accounts will be done in #90. I'm closing this then.

**Closed by JosefNemec** 2017-10-11 06:59 UTC
