### ISSUE TITLE
Can't import Twitch

### ISSUE THREAD

**Issue by networldsystems** [JosefNemec/Playnite#1366] opened 2019-08-13 19:16 UTC
Playnite 5.5 does not import Twitch for me. 

I changed my Twitch username a couple weeks ago. Thinking maybe Playnite stored some conflicting account info, I uninstalled Playnite and deleted any remaining files.

Installed a fresh copy of Playnite and went through the new user setup. All imports worked except Twitch. Followed instructions to log into the Twitch app. Tried logging out of Twitch and logging in when Playnite tried to authenticate -no change. Cleared web cache - no change.

Thanks.

**Comment by JosefNemec** [comment] 2019-08-13 19:29
What does "Can't import Twitch" mean? Do you get some error message or something? Also please go to "About Playnite" menu and create diag. package for me please.

**Comment by networldsystems** [comment] 2019-08-13 19:54
"Can't import Twitch" means ... sorry, I thought you would understand.

1) Clicked 'Authenticate"...

2) Clicked OK. Twich opened, was logged in ...
Clicked 'OK' - 'Waiting for user ...' dialog closes

4) back where I started
If I Update Game Library > Twitch ...
If I uncheck 'Import uninstalled games' ...

and 


 No error



Diag ID:6843c135-3428-42d9-81b8-635b1e1a3a86
Thanks,
Steve

    On Tuesday, August 13, 2019, 2:30:01 PM CDT, Josef Nemec <notifications@github.com> wrote:  
 
 
What does "Can't import Twitch" mean? Do you get some error message or something? Also please go to "About Playnite" menu and create diag. package for me please.

**Comment by networldsystems** [comment] 2019-08-13 23:07
I figured out the issue. I had to run Playnite as Administrator in order to authenticate Twitch.
Thanks,
Steve

    On Tuesday, August 13, 2019, 2:30:01 PM CDT, Josef Nemec <notifications@github.com> wrote:  
 
 
What does "Can't import Twitch" mean? Do you get some error message or something? Also please go to "About Playnite" menu and create diag. package for me please.

**Comment by JosefNemec** [comment] 2019-08-14 12:25
The issue is that you have Playnite installed in "Program Files" folder, which has strict access rules (that's one of the reasons why it's not Playnite's default install directory). And it's why running it as Admin fixes the issue.

However in this specific case the admin rights shouldn't be needed (the fail is in access to one of the 3rd party DLLs we use). I'll see if I can fix it.

**Comment by JosefNemec** [comment] 2019-08-14 13:23
Can you please test it with [this build](https://playnite.link/download/PlayniteTwitchFix.exe)? It should work even when running without admin rights.

**Comment by networldsystems** [comment] 2019-08-14 13:59
Will do. It 's on a different machine than the one I'm using now. I'll try it there. Do you want me to uninstall first?
Thanks,
Steve


    On Wednesday, August 14, 2019, 8:23:29 AM CDT, Josef Nemec <notifications@github.com> wrote:  
 
 
Can you please test it with this build? It should work even when running without admin rights.

**Comment by JosefNemec** [comment] 2019-08-14 16:15
You don't have to uninstall first, maybe just backup current files (the build is based on upcoming 5.6).

**Comment by networldsystems** [comment] 2019-08-14 19:08
I went through the settings and authenticated Twitch. It worked as desired. It showed the Twitch was authenticated, unlike the previous version.
Thanks,
Steve

    On Wednesday, August 14, 2019, 11:15:10 AM CDT, Josef Nemec <notifications@github.com> wrote:  
 
 
You don't have to uninstall first, maybe just backup current files (the build is based on upcoming 5.6).

**Comment by JosefNemec** [comment] 2019-09-18 10:01
Released in 5.7

**Closed by JosefNemec** 2019-09-18 10:01 UTC
Labels: bug
