### ISSUE TITLE
Application hangs during shutdown

### ISSUE THREAD

**Issue by qurao** [JosefNemec/Playnite#866] opened 2018-12-11 14:41 UTC
I leave Playnite running in the background at all times, and when I shut down my PC, the shutdown doesn't happen as Playnite hangs and needs user input to continue. This happens every single shutdown.
![img_20181211_153654](https://user-images.githubusercontent.com/6758468/49807677-fb4fe000-fd5a-11e8-8541-1ca4abfce833.jpg)

Additionally, it would be nice if the application would remember your last position between sessions, and if it could be launched minimized to tray, without needing to enable "minimize to tray."

**Comment by JosefNemec** [comment] 2018-12-11 14:43
Can you go to `About` menu and create diagnostics package for me please?

**Comment by qurao** [comment] 2018-12-11 14:45
> 
> 
> Can you go to `About` menu and create diagnostics package for me please?

Here you go: f49d0e3f-f4fc-473d-a6ef-8fda4f5e346b

**Comment by JosefNemec** [comment] 2019-08-05 14:13
Does this still happen with Playnite 5?

**Comment by craigt00** [comment] 2019-08-08 20:41
Hi @JosefNemec  I'm getting the same error when running Playnite 5.5 and can reproduce it with my local debug build (running outside of Visual Studio).  I'll do some investigation to try and track down the cause - It may be a little frustrating since I'm going to have to reset my machine a lot :)

**Comment by craigt00** [comment] 2019-08-08 21:10
Okay.  Found the cause after adding some additional logging. The CefTools.Shutdown() call below triggers the issue:

https://github.com/JosefNemec/Playnite/blob/fa8789702cd6d9c379276d19a254910ec9c290a7/source/Playnite/App/PlayniteApplication.cs#L422-L428

If I comment out the specific 'CefTools.Shutdown();' line then the issue disappears.  This obviously isn't the solution, but it may be caused by a bug in the CefSharp library.  I'll see what I can do to fix it and submit a pull request.

**Comment by JosefNemec** [comment] 2019-08-09 06:52
Thanks for looking into it. Since this occurs during shutdown maybe we just need to add check if CefSharp processes have been already killed (by the system shutdown) and don't call Shutdown from CefSharp at all.

Anyways it's obviously still an issue in CefSharp, but we could at least workaround it until it's fixed by them.

**Comment by JosefNemec** [comment] 2019-09-18 10:03
Fixed in 5.7

**Closed by JosefNemec** 2019-09-18 10:03 UTC
Labels: bug

**Comment by olepalm** [comment] 2019-10-03 05:41
I have a similar issue in 5.8

![playnite_crash](https://user-images.githubusercontent.com/5213037/66102034-3d2f6880-e5b1-11e9-9073-f9057778ac40.jpg)

**Comment by JosefNemec** [comment] 2019-10-03 12:28
@olepalm Can you go to "About Playnite" menu and create diag. package for me please?

**Comment by olepalm** [comment] 2019-10-03 15:36
@JosefNemec 

Gladly: `5a70f64d-e222-4d21-ae3f-64c7c6c6f0e9`

**Comment by InPhoenity** [comment] 2020-03-16 07:24
Hi,

Same issue than olepalm.
Diag : ea36a24e-403d-4ecc-bc38-f476a1be25e4
