### ISSUE TITLE
Crash when adding Android Platform

### ISSUE THREAD

**Issue by DennoCoil** [JosefNemec/Playnite#949] opened 2019-01-28 14:29 UTC
5356ecc8-828a-4d61-acc5-342d8711dc6e

Added an generic transparent Android icon and a generic smartphone cover, clicked save, and it crashed.

It seems like the problem is that Playnite doesn't know how to handle PNGs with transparency in them.

It seems to be the Icon selection itself and not the Default Cover.  Default Cover handled it fine

**Comment by JosefNemec** [comment] 2019-02-05 13:58
It crashed because `H:\File Management\android-icon.png` icon was not found when updating platform settings. Is it possible that you renamed/delete it before saving changes in Playnite? Anyways it shouldn't crash even if file is missing, just show some error message, so I'll fix that.

**Comment by JosefNemec** [comment] 2019-02-05 14:01
Never mind my previous comment, I've found the root cause somewhere else.

**Comment by DennoCoil** [comment] 2019-02-05 14:23
I used a trick that Windows Explorer uses to add icons and pictures from the internet instead of saving them manually to a drive and then adding them through Playnite's file browser.  I pick the select picture option to open up the file browser from within Playnite to select the picture, but I then use a internet URL in place of the file name in the browser and press select.  As long as the picture is readily available and searchable on the internet, Playnite usually adds them fine except for this one time where certain pictures in the icon part crashed the app.

Drag and Drop picture support might be better in the future because I can then have the edit window on one side of the screen and the web browser on the other side, and drag\drop pictures onto the covers and icons panel.

**Comment by JosefNemec** [comment] 2019-02-08 10:05
Fixed in 4.71

**Closed by JosefNemec** 2019-02-08 10:05 UTC
Labels: bug
