### ISSUE TITLE
Epic Launcher wont launch correctly on win64 system

### ISSUE THREAD

**Issue by grey-lovelace** [JosefNemec/Playnite#1552] opened 2019-11-24 05:11 UTC
This on trying to play or install a game. Seems to be an issue from pre-6.0 release. Looked in the code and it looks like it is deciding to use the `win64` or `win32` version of the exe depending on the current operating system.  While Epic has both installed on my machine, only the `win32` version actually launches correctly. The `win64` version of the exe will only bring up the launcher if it is already running in the background.

Not sure why Epic has it this way, but looks like when you launch the `win32` verison it actually launches a version of the 64 bit version on in the background depending on your OS.

Not sure how we would want to handle this. The problem goes away if either I have the epic launcher already running in the background when I try and launch the game, or if I go into each individual game and choose not to let the epic plugin manage my play action it also works correctly.

I am surprised no one else seems to be affected by this.

**Comment by JosefNemec** [comment] 2019-11-24 09:52
I can't reproduce it, games launch for me properly (I also have both 32bit and 64bit binaries installed). You might want to try and reinstall Epic launcher to see if it fixes the issue.

**Comment by grey-lovelace** [comment] 2019-11-24 15:08
> I can't reproduce it, games launch for me properly (I also have both 32bit and 64bit binaries installed). You might want to try and reinstall Epic launcher to see if it fixes the issue.

Thanks @JosefNemec , I tried reinstalling a couple of times. One last night right before I posted this. Should have mentioned that. Also looked at Epic launcher forums to see if there was anything about it there, but didn't find anything.

**Comment by JosefNemec** [comment] 2019-11-26 10:54
I still can't reproduce it, but even the official client shortcut points to `Win32` version (makes you think why they even bundle 64bit version then). I don't see a problem changing it to always using Win32 version if it fixes some rare issues like you are experiencing.

**Comment by JosefNemec** [comment] 2019-12-02 14:19
Fixed in 6.4

**Closed by JosefNemec** 2019-12-02 14:19 UTC
Labels: bug
