### ISSUE TITLE
Support for game logo media type

### ISSUE THREAD

**Issue by unrealed** [JosefNemec/Playnite#1682] opened 2020-02-29 17:35 UTC
You recently added the ability to import the Steam banner image as the background image, which is great in Details View. But, IMO, it looks much better on Steam because they place the game's logo on top of it in a specific place. It would be great to be able to recreate that effect in Playnite. 

I would really prefer to have a nice and big logo instead of the vertical poster on the right and the text title + icon on the left of the background image. Ideally, this option could also turn off those two so the top is simply a nice clear banner+logo, ideally placed wherever they're placed for Steam (IDK if they share that data)

**Comment by JosefNemec** [comment] 2020-02-29 18:32
I don't know about this. We would either have to add new media type and store that logo separately or do some image manipulation and combine those two together. Which could cause issues for some themes/settings depending how would we merge those two images. Plus this would be basically exclusive just to Steam games.

**Comment by unrealed** [comment] 2020-03-01 01:44
Would a new media type be that much of a problem? Isn't it kind of just "one more metadata"? Also Steam's one of the bigger, if not the biggest, library out there

**Comment by JosefNemec** [comment] 2020-03-01 07:51
It would still mean that you would have no logos for Origin, GOG, Uplay and others (I think Epic is currently the only other store that has them). Also emulated games would have no logos.

I'll leave this open for and we'll see what happens. Also linking #358 to this (I'm not sure I will be able to add full custom support since recent changes to themes).

**Comment by darklinkpower** [comment] 2020-03-01 15:54
Regarding emulated games and logos,[SteamGridDB](https://www.steamgriddb.com/) has an extensive logo database not only for steam and pc games, but for older emulated games too so if someone makes a plugin for it as sugested in #805, that problem could be solved

**Comment by spektor56** [comment] 2020-03-02 17:29
The launchbox metadata plugin and the emumovies metadata plugin both have logos for emulated games

**Comment by SlipperyJim** [comment] 2020-12-08 13:38
I commented on another issue that was effectively a duplicate of this one, so just commenting here too so I can follow this. I think having seperate metadata items for icons and logos would be great.

**Comment by JosefNemec** [comment] 2020-12-08 13:44
You can just subscribe to an issue to get notifications if you don't want to comment as well.

**Comment by JosefNemec** [comment] 2023-05-20 12:00
Same as #358. Will be supported in P11 via custom plugin fields. Direct built-in support for additional media types is not planned.

**Closed by JosefNemec** 2023-05-20 12:00 UTC
Labels: enhancement
