### ISSUE TITLE
Dead Space imported from Origin not opening properly.

### ISSUE THREAD

**Issue by Pixxel123** [JosefNemec/Playnite#1939] opened 2020-07-29 19:18 UTC
**Describe the bug**
When Dead Space is imported from Origin, on launch it opens for a second, then closes out, returning to Playnite. However, if added via Scan Automatically > Detect installed, a second entry is created, which works as it should, launching with no problems.

(A workaround: override the game's default startup by editing the Play action, untick "Managed by library plugin" and put type to Executable and the path to the game's working executable file)

**To Reproduce**
See description.

**Diagnostics ID**
365617f3-3e4b-4c75-80b9-25aafa8f8cb6

**Comment by JosefNemec** [comment] 2020-08-14 10:53
I don't know why, but I can't reproduce it on my system. It doesn't matter if Origin is already running prior to launching the game, Playnite seems to detect running state properly.

**Comment by JosefNemec** [comment] 2020-11-09 11:00
Should be fixed in 8.4.

**Closed by JosefNemec** 2020-11-09 11:00 UTC
Labels: bug
