### ISSUE TITLE
Fullscreen mode adds arrow key binding to game pad

### ISSUE THREAD

**Issue by jamie9090** [JosefNemec/Playnite#2107] opened 2020-11-10 10:08 UTC
**Describe the bug**

In fullscreen mode, Playnite adds a directional key binding to Xbox One controllers Dpad and left analog stick after launching a game. 

This causes double input issues in games. 

I was able to verify this by closing Playnite which fixed the issue. Desktop mode has no issue. 

I can see in Chrome that I am able to move the screen around as if using keyboard arrow keys, wirh playnite closed the expected behaviour is no action. 

Using input viewer tool, I can see computer sees Xbox One controller dpad and left stick as keyboard directional key presses. Instead it should not see anything except for game pad key registers 

**To Reproduce**
Enter playnite fullscreen mode then enter a game. If not occurring, try alt tabbing a few times to confuse Playnite a bit. 

**Diagnostics ID**
Sorry guys, doing this quickly from mobile. I updated to most recent version today. Issue still persists. I also use Rewasd but issue occurs with Rewasd disconnected and services exited. I am on Windows 10, latest publicly available OS version. Steam was exited as well.

**Comment by JosefNemec** [comment] 2020-11-10 10:39
> If not occurring, try alt tabbing a few times to confuse Playnite a bit.

Does this mean that the issue doesn't occur under normal circumstances? I can't reproduce this myself.

We only resend keys when Playnite app (its window) is focused and active. It's because UI toolkit we use doesn't support controllers natively, it's a workaround, sadly. This obviously should not happen if the game is also active, since only one window can have active focus in Windows, it must be some race condition caused by alt-tabbing.

**Comment by jamie9090** [comment] 2020-11-10 22:02
Hey Josef,

Thanks for your reply.

I play games exclusively in fullscreen mode. I get this issue even when
Playnite is not focused.

I was able to replicate this behaviour even when outside of the Playnite
fullscreen window (eg in Chrome or in Windows Explorer) and it occurs even
in exclusive fullscreen games.

I do alt tab a bit whilst using playnite (eg navigating internet with
keyboard, or jumping into Explorer) so it may be Playnite thinks its in
focus but it isn't? I also alt tab whilst in game, and Playnite is in
background mode. So it may be a factor.

But I also often get this issue without Alt Tab.

Please note once I get this issue, I have to quit Playnite to fix. It's not
like it's only there when alt tabbing. Once the issue appears, it is always
there as long as fullscreen playnite is open or in background.

Maybe playnite thinks its in focus even when not?

Thanks,
Jamie

**Comment by JosefNemec** [comment] 2020-11-11 06:41
Thanks for additional info. It's weird that nobody else reported this so far, because input handling hasn't changed since the initial Fullscreen mode implementation. I'll try to reproduce it somehow and see what I can do about it.

**Comment by JosefNemec** [comment] 2020-11-17 10:19
I'm having hard time reproducing it. Do you have exact steps how to make this happen?

**Comment by jamie9090** [comment] 2020-11-18 00:18
Hey Josef, Thanks for looking into this! The best behaviour I can suggest is that when I am playing a game that was launched via Playnite fullscreen, then I alt tab to perhaps check internet/files/downloads/etc.  After doing this, sometimes the game will get the double input issue. When the issue occurs, I just go "show desktop”, then open the game again which generally fixes it.  Now that I know how it happens, I’ve been able to manage the issue so that it doesn’t really bother me. So it actually feels like less of an issue. I’ll keep you posted from my end on what I find, but perhaps make it lower priority for now? Cheers,Jamie   From: Josef NemecSent: Tuesday, 17 November 2020 9:19 PMTo: JosefNemec/PlayniteCc: jamie9090; AuthorSubject: Re: [JosefNemec/Playnite] Fullscreen mode adds arrow key binding to game pad (#2107) I'm having hard time reproducing it. Do you have exact steps how to make this happen?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by JosefNemec** [comment] 2020-11-30 09:43
I'm going to close this for now. I just can't reproduce this and there are no other users reporting this issue. I would maybe check if this is not caused by some 3rd party as well.

If you find reliable way how to reproduce it, let me know.

**Comment by vilemyr568** [comment] 2021-07-29 15:11
Playnite seems to bind both the joystick, keyboard and D-Pad together/inputs both of them at the same time, so alt-tabbing basically places Playnite on the same priority as every other application (I guess?). 

Ex: I boot up GTA V, and after Alt-Tab midgame movement inputs such as walking/driving forward will activate phone, and holding LT in vehicle will make my character fire their weapon instead of braking (as if it binds both LB and RB together), and in the menu every input regardless of stick and P-pad would act as a double  input and navigate the.

Skyrim Special Edition had a similar issue after a crash (that of which was unrelated to Playnite), where I had to manually restore the Playnite window. After booting Skyrim Special Edition back up via Playnite after a crash to desktop or maximizing it after Alt-Tab, I would get the last mentioned issue in GTA where I would get double inputs while scrolling in the menus. 

I will see if I could reproduce the issue with other games. 

Thank you in advance!

**Comment by jamie9090** [comment] 2021-07-29 23:26
I can confirm I still get this issue.

My work around is whilst ingame to go "show desktop", and then re-open playnite (which is minimised), and then alt tab back to game.

It then works correctly.

**Comment by vilemyr568** [comment] 2021-07-30 00:29
Unfortunately the fix only works for GTA V and Assassin's Creed Origins for me, while the rest of the games (including Skyrim Special Edition which turns out just decides when it wants to work randomly :/) require a new instance of Playnite to be opened. 

Are you using the portable install by any chance, @jamie9090?

**Comment by jamie9090** [comment] 2021-07-30 00:46
Just to clarify - I can also confirm that I get the issue, even when I am not alt tabbing around. But honestly, it only happens sometimes. @JosefNemec 

@vilemyr568 are you using a custom theme, or one of the Playnite default themes?

**Comment by vilemyr568** [comment] 2021-07-30 00:50
I tried using both the default and Consoleish UI themes for fullscreen, and I only ever started experiencing the issue after I did a fresh reinstall of Playnite in portable yesterday.

I'll probably do a fresh reinstall right now without the portable version and let you know if it works.

**Comment by curtgrimes** [comment] 2021-09-17 04:30
I seem to have this issue when Steam is open in the background and I have Playnite focused in the foreground.

**Comment by Virtualizer** [comment] 2021-11-07 00:53
I have the same problem e.g. when starting Forza Horizon 5 via Playnite Fullscreen. First start will always mess up controller bindings (Xbox One Controller). If I close the game and immediately start the game again in Playnite, the controller does work though. For other games there are weird issues, too.

**Comment by JosefNemec** [comment] 2021-11-07 12:40
I will have fix for this in next update.

**Comment by Virtualizer** [comment] 2021-11-07 14:01
If we disable XInput support in Playnite Fullscreen settings, could that be a workaround for the problem? Have reWASD installed anyways, so it would be easy to create a gamepad profile for Playnite Fullscreen.

**Comment by JosefNemec** [comment] 2021-11-08 15:21
Fixed in master.

**Closed by JosefNemec** 2021-11-08 15:21 UTC
Labels: bug
