### ISSUE TITLE
I can't add my own media as metadata

### ISSUE THREAD

**Issue by OGBen** [JosefNemec/Playnite#1465] opened 2019-09-28 07:11 UTC
**Check for existing issue**
Issue has not already been found

**Describe the bug**
Whenever I right-click on a game and select edit, I head over to the media tab and try to add my own game background and icon image because the metadata download didn't find one on its own. It lets me successfully add any image i'd like and it shows up in the menu, but as soon as I press save the window closes, and the image/url is not actually saved, I could go back to the same media tab and find that my image/url is gone.

**To Reproduce**
Instructions should be clear from description of issue.

**Screenshots**

**Diagnostics ID**
If this is a crash report please include string ID you receive after using "Create diag. package` on crash dialog.

**Comment by JosefNemec** [comment] 2019-09-28 07:35
Can you go to "About Playnite" menu and create diag. package for me? I can't reproduce it myself.

**Comment by OGBen** [comment] 2019-09-28 09:19
> Can you go to "About Playnite" menu and create diag. package for me? I can't reproduce it myself.

I`ll create one for you now, but a restart of the launcher seemed to fix it. If it helps you reproduce the issue I had just installed the launcher and there was no computer restart or restarting of the launcher when this happened.

**Comment by JosefNemec** [comment] 2019-09-28 09:29
If restart fixed it then it's probably the same issue as #1452

**Comment by JosefNemec** [comment] 2019-10-14 13:04
I investigated it more and it in fact is the same issue as #1452, therefore I'm closing this one. It will be fixed in Playnite 6 (btw it only occurs if grouping of game list is enabled).

**Closed by JosefNemec** 2019-10-14 13:04 UTC
Labels: bug
