### ISSUE TITLE
Database import from previous playnite version fails.

### ISSUE THREAD

**Issue by Nilot352** [JosefNemec/Playnite#773] opened 2018-09-27 13:11 UTC
with the following message 
"Database import failed, cannot open  database"
I was using version 4.40 previously which works fine
 My database file is

**Comment by JosefNemec** [comment] 2018-09-27 13:17
Can you go to "About" menu and create diagnostics package for me please? Also can you attach screenshot of the error message? Because Playnite itself shouldn't report that message (at least I don't see it anywhere in our localization strings), so I'm wondering where is it coming from.

**Comment by qwerty108** [comment] 2018-10-13 15:01
This also happens to me.
If I downgrade to 4.40 it works fine, but any attempt to update shows "Database update failed"
![imagen](https://user-images.githubusercontent.com/3130558/46906793-d65ffd80-cece-11e8-8fe5-906fccf84a34.png)

[diagnosticsPackage.zip](https://github.com/JosefNemec/Playnite/files/2475565/diagnosticsPackage.zip)

**Comment by JosefNemec** [comment] 2018-10-13 16:04
@qwerty108 Could you please share your [database](https://github.com/JosefNemec/Playnite/wiki/Frequently-Asked-Questions#where-can-i-find-library-file-with-all-games) file with me? It would help a lot.

**Comment by JosefNemec** [comment] 2018-10-13 20:34
Thanks again for the database file. Root cause and the migration itself will be fixed in next update. In the meantime [here's your db file fixed](https://1drv.ms/u/s!AhVKpOJfcX7NgcdZIW7S9JcKanV0GA) so you don't have to wait for that update (use it with the latest 4.54).

**Comment by qwerty108** [comment] 2018-10-14 05:14
Confirmed that the fixed DB is working on 4.54. Thank you very much!

**Comment by JosefNemec** [comment] 2018-10-18 07:51
Released in 4.55

**Closed by JosefNemec** 2018-10-18 07:51 UTC
Labels: bug
