### ISSUE TITLE
Games being listed multiple times

### ISSUE THREAD

**Issue by spineduke** [JosefNemec/Playnite#1929] opened 2020-07-19 17:12 UTC
**Check for existing issue**
Please use issue search in the repository if the bug is something really obvious there's a high change it was already reported.

**Describe the bug**
Games are appearing in the Details View column multiple times 

**To Reproduce**
"Group by Tags" and either List view or Details view. the duplicates will show under the "None" tag

**Screenshots**

![clones](https://user-images.githubusercontent.com/68511752/87880662-1d601880-c9fc-11ea-91ef-9d35c7cb48bc.jpg)

**Diagnostics ID**
Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.

**Comment by shakeyourbunny** [comment] 2020-08-01 14:28
Are these duplicate from different libraries? if yes, there is / was already a discussion.

**Comment by spineduke** [comment] 2020-08-01 15:23
No, they all have the same source. I don't see these duplicates in grid view

**Comment by JosefNemec** [comment] 2020-10-10 12:38
Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.

**Comment by spineduke** [comment] 2020-10-14 14:06
I can confirm issue still present in 8.1 - it doesnt crash the app

here's my diag id
44151173-ce33-4b98-8bb4-45ce2eedddef

**Comment by JosefNemec** [comment] 2020-10-14 14:10
Can you upload your `%appdata%\playnite\library` directory and send it to me?  You can leave out `files` sub-directory (it would take most space and I don't need it for diagnostics.

**Comment by spineduke** [comment] 2020-10-14 14:19
that folder is empty

i have my database location pointed to another drive, if that matters.

**Comment by JosefNemec** [comment] 2020-10-14 14:24
Then please upload library from that other drive.

**Comment by spineduke** [comment] 2020-10-14 14:36
[PlayniteMetadata.zip](https://github.com/JosefNemec/Playnite/files/5378916/PlayniteMetadata.zip)

**Comment by JosefNemec** [comment] 2020-10-16 11:05
The issue is caused by corrupted game data. Did you use some 3rd party metadata extension or other extension that would modify game tags?

For example `1001 Spikes` has this assigned to it.

```
    "TagIds": [
        "7c68658b-0008-4702-a961-563d4ac3d404",
        "2e9948a2-cdeb-4519-80f0-a3ab5126abae",
        "2e9948a2-cdeb-4519-80f0-a3ab5126abae",
        "2e9948a2-cdeb-4519-80f0-a3ab5126abae"
    ],
```

I'll make it so that the invalid tag entries are ignored, but I would like to know what caused this in the first place (and if it's potentially some issue in Playnite).

**Comment by spineduke** [comment] 2020-10-16 11:13
Outside of the usual metadata sources (Steam), the only other extension I used was Game Media Tools by darklinkpower, to find games that don't have the correct media dimensions. It would tag games that didn't meet the specified requirements

**Comment by JosefNemec** [comment] 2020-10-16 11:14
Interesting, @darklinkpower had a similar issue with his library, I wonder if it was caused by `Game Media Tools`.

**Comment by JosefNemec** [comment] 2020-10-16 12:04
Fixed in `devel`.

**Closed by JosefNemec** 2020-10-16 12:04 UTC
Labels: bug

**Comment by darklinkpower** [comment] 2020-10-16 13:16
Is the issue that the game has tags assigned that don't exist? I remove tags from the tags database when there are no games assigned to it, but that shouldn't cause an issue since it's checked that 0 games are using them: https://github.com/darklinkpower/PlayniteScriptExtensions/blob/master/GameMediaTools/GameMediaTools.ps1#L412-L432

I need to refactor that script, it's a mess right now. I'll investigate the issue while at it.

**Comment by JosefNemec** [comment] 2020-10-16 13:33
Two issues here:
- assigned tags that don't exists
- same tag IDs assigned multiple times
