### ISSUE TITLE
There was an error when attempting to conigure your emulators: An item with the same key has already been added

### ISSUE THREAD

**Issue by Bboy486** [JosefNemec/Playnite#3767] opened 2024-06-20 01:21 UTC
### Bug Description

I'm trying to use the Emudeck plugin ( I reported this to the Dev) He is saying it is something in playnite that is conflicting. I don't know where to look to find what the conflict is and I've tried to uninstall and reinstall it. I have also removed all the emulators in Auto scans restarted but I still keep getting that error. I looked in the log but I didn't see a reference to this either

### To Reproduce

Install Emudeck plugin and under add on settings reload configuration 

### Diagnostics ID

a1217bbf-4cc0-4a7d-bddb-d2f7cdd2c9c0

**Comment by JosefNemec** [comment] 2024-06-20 08:13
I don't see the error you mentioned in the log, but if it's an error reported by the plugin, it needs to be fixed in the plugin. Nothing I can do about this from what I'm seeing.

If plugin dev analyzed this and deduced that the issue is in Playnite, they should report exactly where they are seeing this issue in Playnite, I don't see anything.

**Closed by JosefNemec** 2024-06-20 08:13 UTC
Labels: bug
