### ISSUE TITLE
Playnite preventing game process from being terminated

### ISSUE THREAD

**Issue by falcorr** [JosefNemec/Playnite#2188] opened 2020-12-23 23:45 UTC
**Issue**
For a very long time Playnite has had issues with the hook, or whatever it is. Playnite causing the game process to stay open after exiting, and only being able to kill it after closing Playnite. Playnite being unable to launch the game as it's kept the game's process open from last time. Instances where Playnite itself freezes until the game process is killed. Etc. It's especially prominent when games crash or don't exit normally.

**Describe the solution you'd like**
I'm sure I've brought this up ages ago, either here or on Reddit. In lieu of a fix, I'd simply now like the option to disable the hook to avoid the problems altogether. I can live without playtime being tracked and whatever else may be going on if it means I don't keep running into this.

Edit: #1054 two years ago.

**Comment by JosefNemec** [comment] 2020-12-24 09:02
1) Playnite doesn't hook itself to game process. The only process interaction that's happening is checking if a process is running.
2) I will need specific examples of games having this issue so I can debug this myself.
3) Are you using 3rd party extensions that could be causing this?

**Comment by JosefNemec** [comment] 2020-12-24 09:41
To clarify, we do ask Windows for two things about the process, startup path and parent process id. But that doesn't involve any "hooking" into the process.

I'm not saying that there's no potential issue in Playnite, but play time tracking hasn't changed in years now and only two people reported this issue so far. I will need specific examples of games or steps to reproduce this to be able to analyze this any further.

**Comment by falcorr** [comment] 2021-01-03 13:30
1. Whatever interaction is at play, it's Playnite. 
2. I don't have examples off the top of my head. It's usually not an issue but occurs frequently enough to be frustrating. I've noticed a game crashing out and not exiting gracefully or as intended is one way to cause it. I suggest examining how exactly Playnite checks a game or process has ended. I'd also suggest keeping this issue in mind when potentially related issues are reported, which I believe I've read about a few times here and in the sub-Reddit.
3. I have a couple of extensions these days but this issue existed long before I touched any.

**Comment by falcorr** [comment] 2021-01-03 13:31
Whether you can identify the issue or not, I'd find it very useful to have the ability to disable Playnite interacting with the game process.

**Comment by JosefNemec** [comment] 2021-01-03 13:48
> Whether you can identify the issue or not, I'd find it very useful to have the ability to disable Playnite interacting with the game process.

That's not something Playnite can enforce, only for manually added games. Play time tracking for games imported by a library plugin is completely in hands of the plugin and Playnite doesn't do any interaction with game processes in any way.

**Comment by MartinAngelov** [comment] 2021-01-03 13:58
@falcorr I would suggest using tool like [Process explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) to confirm what is actually  blocking the process termination. I've never expirnced the issue and don't see such a possibility (playnite to be the reason) from the source code.

**Comment by JosefNemec** [comment] 2021-01-03 17:35
I'll try to reproduce it with some crashing process to see what's happening. But it will be nearly impossible to fix unless I can reproduce it in my environment. If you find game/app that can reproduce this reliably, that would be very helpful.

**Comment by falcorr** [comment] 2021-01-09 02:09
> That's not something Playnite can enforce, only for manually added games. Play time tracking for games imported by a library plugin is completely in hands of the plugin and Playnite doesn't do any interaction with game processes in any way.

I run the large majority of my games away from their launchers, as manual adds. Unless they get regular updates or benefit significantly from official connectivity, I ditch the DRM. I'll try to keep it in mind and note instances.

**Comment by JosefNemec** [comment] 2021-03-10 07:45
Thanks for additional information. All this sounds to me like something not caused by Playnite, but some 3rd party instead. Especially if you can't kill the process after Playnite is no longer running. Also if this only started happening recently, because we haven't changed how processes are started for more then two years now (and no Playnite update itself for months now).

There's also no crash information in your logs, which means that those Playnite crashes are not caused by our code but by some 3rd party that causes our process to hard terminate. From what I've seen, this usually happens with apps that try to inject into our process, but shouldn't (they do it because Playnite is DX9 process). Things like game overlays (RivaTuner, MSI Afterburner etc.).

**Comment by JosefNemec** [comment] 2021-03-10 08:00
So I've tried it with Don't Starve and Goldberg and it works just fine for me, so I don't know. My plan for workaround was to spawn child Playnite process that would start a game and then immediately exit, but you if are saying that existing Playnite doesn't help, then there's no reason to do it that way.

The other issue is that you are the only person so far that reported this issue. That together with a fact that start processes via default .NET way of launching a process (which has been battle tested for more then a decade now), would really suggest to me that this is caused by some issue in your system, rather then issue in Playnite. I can't however say what could be that issue.

**Comment by JosefNemec** [comment] 2021-03-10 08:03
Lastly, does this only happen when using things like Goldberg? I don't know why you need to use it with original Don't Starve which doesn't have multiplayer...

**Comment by falcorr** [comment] 2021-03-10 08:44
It seems like Playnite to me. If Playnite is running and launches the game, it happens every time. If Playnite isn't running and I launch the game without it, it doesn't happen, every time. I also don't experience anything like this with any other programs. This has been occurring for a long time in these two forms (whether or not the process is still unable to be killed after Playnite is closed), possibly since I started using Playnite which would've been early in its life. 

That diagnostic code was taken upon reloading Playnite after finding it had crashed again. I don't know if that would mean it doesn't contain what you need. 

I use RivaTuner's overlay but I'm not sure I've been using it as long as Playnite has been crashing over the years. I'll try without it, anyway. 

This has happened with a variety of launch scenarios but I couldn't say off the top of my head which. I can say I only recently started adding Goldberg to my mix. As for using a Steam emulator with Don't Starve, it's because where possible I prefer to run my games without DRM and with the stability of manually managed updates so as to not break mods and change functionality sometimes for the worse. There are also other benefits like load times, which internet-blocked, modded Don't Starve benefits from, and portability which is useful in terms of backing up. And of course I'm not reliant on a third party to launch my games, should there be that kind of problem one day. 

As for no one else reporting the issue, it may be obscure but on top of that, many may not notice. It can be possible to launch some games over and over without realising you're littering task manager with stuck processes. I'm regularly looking at task manager and spotting these things. It may also be related to bypassing DRM or launching games directly via executable which I'm guessing isn't common. But, I still think is very worthy of support especially given Playnite's role as an alternative launcher (and presumably not wanting to be reliant on other launchers at the end of the day).

**Comment by JosefNemec** [comment] 2021-06-08 09:00
Small update. I'm still unable to reproduce this, but I have identified potential issue in our game tracking which could be causing this. I will make some changes in Playnite 9 and we'll see if it fixes the issue.

**Comment by LeeThompson** [comment] 2021-06-09 06:26
@JosefNemec I'd be willing to test an early build (mostly for the handle leak) but Playnite has caused this issue sometimes as well with Guild Wars 2.

**Comment by JosefNemec** [comment] 2021-06-15 12:38
Can you please test if this is still an issue with the latest 8.13 update?

**Comment by JosefNemec** [comment] 2021-08-02 15:15
Closing since there's no confirmation from affected users. It was most likely caused by #2352, which was fixed in 8.13

**Closed by JosefNemec** 2021-08-02 15:15 UTC
Labels: bug
