### ISSUE TITLE
Taskbar icon for client is installed game

### ISSUE THREAD

**Issue by TheDreka** [JosefNemec/Playnite#1286] opened 2019-07-27 19:19 UTC
Since upgrading to the 5.x branch (now at 5.3), the Playnite client now appears as Stardew Valley in my taskbar. I assume the specific game would be different for different users. The client is running on startup. Restarting the client has no effect.

![Annotation 2019-07-27 151005](https://user-images.githubusercontent.com/227006/61998660-5384e980-b081-11e9-8622-04c8bc1d9670.png)

![Annotation 2019-07-27 151032](https://user-images.githubusercontent.com/227006/61998664-597aca80-b081-11e9-8c40-e07fbef64d92.png)

The link Windows is using is to the start command for that game instead of the Playnite client.

![Annotation 2019-07-27 151144](https://user-images.githubusercontent.com/227006/61998665-5e3f7e80-b081-11e9-926f-a6c4ebe01d16.png)

Interesting side note - I have a second screen with a DisplayFusion taskbar replica. The correct icon, application name and jump list appear there. The issue seems to be localized to the Windows taskbar only.

**Comment by TheDreka** [comment] 2019-07-27 19:20
Personal note, I resisted the urge to name this issue "Playnite is now a chicken" for future searches.

**Comment by JosefNemec** [comment] 2019-07-27 19:45
This is a known issue already reported here (I can't find the original issue for some reason). The problem is that I can't reproduce it on any of my systems. And even if I could I don't think I can do anything about it (I have no control over what icon will be used in taskbar, it should use executable's icon, which clearly is not a chicken). It looks like a very rare bug in Windows.

**Comment by TheDreka** [comment] 2019-07-27 22:06
Noted. I may have found a partial cause. First, some troubleshooting:

- If I attempt to pin the bugged taskbar item, the icon reverts to the correct Playnite icon, although the name and main jump list link still point to Stardew Valley and its Playnite start command.
- If I pin the application manually from the folder (by dragging the application to the taskbar or choosing "Pin to taskbar" from the context menu), the pin has the correct name and jump list. It never reverts to Stardew Valley's entity.
- If I pin the application manually to the Start menu and then run it, it inherits the name from the Start menu and jump list. However, as soon as I remove the pinned Start menu item, it reverts back to the chicken.
- As it turns out, I have the installed games from Playnite pinned to my Start menu, including Stardew Valley. If I unpin the application that Windows thinks Playnite is, it chooses another from the list. For example, when I remove the shortcut for Stardew Valley, Windows assigns the shortcut and icon for "Risk of Rain 2" to the taskbar entry for Playnite.

Therefore, a possible reproduction may be creating desktop shortcuts from Playnite and pinning these shortcuts to the Start menu, without a shortcut to Playnite itself.

**Comment by TheDreka** [comment] 2019-07-27 22:09
Note, just because it may be possible to reproduce the error, does not mean I assume it's an error you can fix. Just giving as much information as I can in case it is something you can rectify.

**Comment by JosefNemec** [comment] 2019-07-29 12:21
I found original issue #813. #814 could possible fix this (as a side effect), but I'm not sure.

**Comment by TheDreka** [comment] 2019-07-30 18:09
Most likely no longer relevant, but, the only consistent reproduction I've been able to find so far is for the desktop shortcuts to exist PLUS an update to the Playnite client to be applied. Post-update Windows/the client behaves in this manner until the machine is restart. Afterwards it reverts to normal behavior.

**Comment by JosefNemec** [comment] 2019-11-07 10:54
I'm closing this. As stated previously, this is some bug in Windows, I have no way of forcing different icon there. Maybe #814 will fix this, but who knows.

**Closed by JosefNemec** 2019-11-07 10:54 UTC
Labels: bug
