### ISSUE TITLE
Playnite 10 crash on start up at 'Scanning Game Size'

### ISSUE THREAD

**Issue by rikuddo91** [JosefNemec/Playnite#3095] opened 2022-09-25 11:27 UTC
### Bug Description

Version 9 works perfectly fine but as soon I update to 10, it start scanning game size and the entire playnite get unresponsive and then crash without any dialog box. There's no log created or any other error to pinpoint the problem

When I reinstall back the version 9 on top of it, everything works fine again. 

### Diagnostics ID

Crash without any dialog or log

**Comment by darklinkpower** [comment] 2022-09-25 15:41
Can you check if the issue is fixed with this build? https://drive.google.com/file/d/1Ya5tv_FoIkmXpm4gq59LNdpbBej1MZll/view?usp=sharing

The build is meant for testing purposes, do not replace the files in your current installation directory.

If that doesn't work, please try with this other one and upload the logs here in a zip file after the crash https://drive.google.com/file/d/1E8RX-1KVzjm3JbESePEebiciD1NjQ_4s/view?usp=sharing

**Comment by rikuddo91** [comment] 2022-09-25 15:54
> Can you check if the issue is fixed with this build? https://drive.google.com/file/d/1Ya5tv_FoIkmXpm4gq59LNdpbBej1MZll/view?usp=sharing
> 
> The build is meant for testing purposes, do not replace the files in your current installation directory.
> 
> If that doesn't work, please try with this other one and upload the logs here in a zip file after the crash https://drive.google.com/file/d/1E8RX-1KVzjm3JbESePEebiciD1NjQ_4s/view?usp=sharing

Thanks for getting back, PlayniteSizeScanCrashTest2.zip worked for me. no crashes so far. I've reconnected all accounts and the 'game size scan' runs fine.

**Comment by darklinkpower** [comment] 2022-09-25 15:57
Thanks for the report. Your issue has already been fixed with https://github.com/JosefNemec/Playnite/pull/3085 and will be included in a future update

Just for testing purposes, can you try with the build in the second link and upload the logs please? It will say in the logs the name of the game that caused the issue

**Comment by rikuddo91** [comment] 2022-09-25 16:21
> Thanks for the report. Your issue has already been fixed with #3085 and will be included in a future update
> 
> Just for testing purposes, can you try with the build in the second link and upload the logs please? It will say in the logs the name of the game that caused the issue

Sorry, where's the log file generated. I can't seem to find it anywhere in the main folder.

**Comment by darklinkpower** [comment] 2022-09-25 16:27
It will be `Playnite.log` in the directory where you extracted that build files.

**Comment by BooneElledge** [comment] 2022-09-26 22:13
Similar issue (but I posted on reddit), attached is a zip of my log 
[playnite.log](https://github.com/JosefNemec/Playnite/files/9649963/playnite.log)

**Comment by JosefNemec** [comment] 2022-12-10 17:26
Is this still happening with the latest Playnite update? There's been multiple fixes related to game size scanning since this issue has been opened.

**Comment by rikuddo91** [comment] 2022-12-10 18:17
> Is this still happening with the latest Playnite update? There's been multiple fixes related to game size scanning since this issue has been opened.

No, it's seems to be fixed for me. Updated to latest versions and it's working perfectly fine for me.

**Closed** 2022-12-10 18:18 UTC
Labels: bug
