### ISSUE TITLE
[Browser] Studios appear as publishers and vice versa

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#1266] opened 2019-07-26 21:24 UTC
Playnite merges studios and publishers into the same "company" category. This causes their respective sections in the browser to be cluttered with empty entries : 

![Sans titre-2](https://user-images.githubusercontent.com/38838369/61982219-4ffb4f00-affc-11e9-8fd0-24b083e59c9e.jpg)

**Comment by JosefNemec** [comment] 2019-07-27 10:04
I don't think we can do anything about this. It doesn't really makes sense to have separate library database for developers and publishers since you could get duplicates in case where developer also publishes the game.

Also if this is a problem of explorer section having entries that have no games assigned to them, then it's a issue for all fields. For example Tags would also display all tags you have in library no matter if a game is assigned to them.

**Comment by JosefNemec** [comment] 2019-07-28 16:45
I'm going to duplicate this to #1301 even that it's a newer issue because it more clearly explains that the issue is for all game fields.

**Closed by JosefNemec** 2019-07-28 16:45 UTC
Labels: bug
